### ISSUE TITLE
Having issues with Web Automation example - tool not for Google Colab

### ISSUE THREAD

**Issue by richylyq** [tebelorg/RPA-Python#102]
Hi,

I am trying the RPA for WEB AUTOMATION on Google Colab, but i am getting this error when i r.init()

```
import rpa as r

r.init()

[RPA][ERROR] - following happens when starting TagUI...

False
```

**Comment by kensoh** [comment]
Hi @richylyq the tool is not designed to work in Google Colab. It has to be installed locally on your computer or some VPS. This is because it requires access to the computer web browser and screen in order to perform automation tasks. Colab I think is only a hosted Python session which will not work. Using the tool with a Jupyter notebook or Pythin interaction session works.

**Comment by richylyq** [comment]
> Hi @richylyq the tool is not designed to work in Google Colab. It has to be installed locally on your computer or some VPS. This is because it requires access to the computer web browser and screen in order to perform automation tasks. Colab I think is only a hosted Python session which will not work. Using the tool with a Jupyter notebook or Pythin interaction session works.

Hey @kensoh 
Thanks for the prompt reply, got it working on my local machine, but i wasn't able to get it running on Jupyter Notebook. Will explore further on my local machine then. Thanks once again!

**Comment by kensoh** [comment]
Welcome! If your Jupyter notebook is installed using Anaconda, you may need to pip install the package from Anaconda command prompt to make sure it's accessible to the notebook environment.
