### ISSUE TITLE
Work with multiple windows - try open new tabs and use popup() or use visual

### ISSUE THREAD

**Issue by Atrivkumar** [tebelorg/RPA-Python#105]
When I have multiple windows of chrome open, the TagUI works only with the first window which is open. Unfortunately non of the activities like click or type work on second window.

**Comment by kensoh** [comment]
The answer is similar to here - https://github.com/tebelorg/RPA-Python/issues/106#issuecomment-584223201

Due to above Chrome backdoor limitation, you can try to do everything visually using the visual automation method. Alternatively, you can try to open new tabs from the main existing page and then use popup() function to set context and control the new tabs.

But it is not straightforward to try to open new tab on an existing webpage. Probably use visual automation to right click on something then click on the new tab menu.

Will recommend that if the visual automation method above is not suitable, try to separate your automation into 2 parts, first part to get data from first website and store it, then another part to write the data to second website.

**Comment by Atrivkumar** [comment]
Hi Ken,

Thanks for your response . Let me explain my use case. I have a website. I login to the website. Once I login I click on a button which opens the content in new tab rather than existing tab. Now when I use any functions like click and type. It will try to find elements in tab1. How do I switch to tab2 in this scenario ?

**Comment by kensoh** [comment]
Oh I see.. This use case can work on most websites. You can use the popup() to do so.

```py
r.click('login_identifier')
# new tab opens up

r.popup('unique_string_in_url_of_new_tab')
# then do your actions on the new tab

# reset to do actions on original tab
r.popup()
```

**Comment by kensoh** [comment]
Closing for now until further inputs!
