### ISSUE TITLE
ask() always takes the input in plain text - pending more details

### ISSUE THREAD

**Issue by Atrivkumar** [tebelorg/RPA-Python#107]
Ask() function always takes input in plain text and the text enter get displayed in the prompt. If I want to prompt the Ask() function to take the password from the user . It should mask the characters entered.

**Comment by kensoh** [comment]
By default, debug() is off and there is no log file containing the text that user enters or any UI interactions. Can you provide a simple replication script how the password shows up in log file?

In the upstream TagUI project, there is no functionality to mask interactions with web page unless it is run in quiet mode. However, for this package I run it in default verbose mode in order to capture the log and then delete at the end of the automation if debug() is off (default off).

**Comment by Atrivkumar** [comment]
Hi Ken,

When I use ask() function, there will be a prompt to take input from the user. When user start typing, the characters are shown in the prompt box. If user is inputting the password, it is visible. I am expecting some kind of masking may be * char when user input the password.

**Comment by kensoh** [comment]
Hi @Atrivkumar I assume you mean the Chrome popup. This is not supported in Chrome browser using JavaScript prompt() and has to be developed as a separate popup page.

Thus I'm afraid this function is not available in TagUI upstream project and in this package. Will close this issue for now as this feature is not supported.

If you can, try not to prompt for password but let user key in through the normal login page, for example doing a wait() for user to login or to do a hover() for some element that only appears after login. In that way the input will be masked on the webpage.
