### ISSUE TITLE
Right Click and Context Menu - keyboard, click image, click text using OCR

### ISSUE THREAD

**Issue by hydrotik** [tebelorg/RPA-Python#108]
Is there any support for selecting items in the right click menu? Not seeing any information anywhere about that. Seems hitting the arrow down a specific number of times then clicking enter would have the same affect which I am about to test. seems like there might be a more elegant way to handle this?

Cheers

**Comment by kensoh** [comment]
Hi Donovan, that's right, there isn't an API to do something specifically for right-click menu. It's not part of the HTML DOM but is part of Chrome browser app, so it has to be handled in the same way as dealing with desktop apps.

Besides using down arrow with keyboard(), below are 3 ways which this can be done. There could be more ways that I don't know of yet haha, because the tool is quite versatile. For eg, figuring out the JS function to call for the menu item and using dom() to initiate without clicking.

**sample code**
```py
import rpa as r
r.init(True)
r.url('https://github.com/tebelorg/RPA-Python')
r.rclick('LICENSE.txt')

# use keyboard() to do the selection
r.keyboard('[down][down][enter]')

# click on an image snapshot of the menu item
# see sample image below this code block
r.click('new_tab.png)

# click using OCR text search by finding the text on the screen
# when an image file does not exist, search will be done via OCR
r.click('Open Link in New Tab.png');
```

Note that above assumes that Chrome browser is already in focus (foreground). If not, there must be an additional step to click on Chrome browser icon on the taskbar or docker to make sure the window is in the foreground for above interactions to be done there.

I personally prefers using the OCR search method as it is the cleanest. But it will take slightly longer time than the other 2 ways because the whole screen will be analysed to find the best match for the text provided to search. It'll depend on the use scenario which method is best.

**new_tab.png**

![ new_tab](https://user-images.githubusercontent.com/10379601/74895826-ab908e00-53cd-11ea-86ae-b243cb7ec942.png)
