### ISSUE TITLE
print(r.read('    ')) not working - works now after enabling VA with r.init(True)

### ISSUE THREAD

**Issue by Jamesbeagle** [tebelorg/RPA-Python#110]
when testing your simple OCR use case it seems that the r.read function is not executing (at least on windows)
are any additional libraries required?

**Comment by kensoh** [comment]
Hi James, what is your Python code and image snapshot that replicates the issue? read() can read from a web element identifier, image snapshot or a rectangle boundary.

For OCR, Java JDK is required. During the run, there should be a message asking user to install Amazon Corretto (OpenJDK) if Java is not available. Also, to use read() using OCR, init() should be run with init(True) in order to load the computer vision and OCR engine.

**Comment by Jamesbeagle** [comment]
Firstly thanks for the response, this is an awesome package!!
I have it working :) I needed to specify the full path of the image rather than just the image name in the working folder.
