### ISSUE TITLE
is it possible to speed up the mouse movement? - yes use vision() function

### ISSUE THREAD

**Issue by asagao-web** [tebelorg/RPA-Python#111]
Thanks very much for great tool! I really enjoy using this tool.
Is it possible to speed up mouse movement?
I had used sikuliX and i had a setting of mouse speed and was very useful.

**Comment by kensoh** [comment]
Thanks @asagao-web for sharing your appreciation and I'm glad you have fun using it!

Yes, you can use the vision() function to send any custom SikuliX commands to the SikuliX engine that comes with the package. Below will set the mouse to teleport from current position to new position in 0 seconds. Eg after setting this, doing `r.hover(0,0)` will teleport mouse cursor to upper left corner of screen instead of moving over in the default 0.5 seconds.

```py
r.vision('Settings.MoveMouseDelay = 0')
```

More on this SikuliX command -
https://sikulix-2014.readthedocs.io/en/latest/scripting.html?#Settings.MoveMouseDelay

**Comment by asagao-web** [comment]
thank you very much for your reply!
