### ISSUE TITLE
api() method issue - no api() function, use Python requests package instead

### ISSUE THREAD

**Issue by soorejmg** [tebelorg/RPA-Python#116]
Hi, 
I am trying to fire a api call to download an image file. I want to to store the content of it in a variable and then later want to paste to a word document for a report preparation. I don't want to save the file using download function and then later copy it and paste in word document.

My Questions:-
1. Is this possible ? If not possible, which way would be the best to use?
2. When using t.api(url), i am seeing the value as succes, but when trying to print the api_result or t.api_result, it shows the variable dont exist. What is wrong here?

**Comment by kensoh** [comment]
Not sure why you missed the messages, when you r.api(), you should get the messages below -
```
[RPA][INFO] - although TagUI supports calling APIs with headers and body,
[RPA][INFO] - recommend using requests package with lots of online docs
```

**Comment by kensoh** [comment]
The solution is to use the Python requests package instead of the in-built API capability of TagUI.

This is because requests is very mature, powerful and lots of docs and examples online.

It would be the best-in-class and best practice for Python user to consume API services.

Link to requests package - https://requests.readthedocs.io/en/master/

**Comment by soorejmg** [comment]
Thanks Kensoh. This was useful :)
