### ISSUE TITLE
[RPA][ERROR] - cannot find example.png - Windows display zoom level

### ISSUE THREAD

**Issue by pierrekublik** [tebelorg/RPA-Python#119]
Hey All, 
I looked through the Forum but only found a related, but not the same error. 
I want to use the following Code:

r.init(True, False)
r.click("Zertifikate.PNG")
r.close()

I get the error message: "- cannot find Zertifikate.PNG"
The file "Zertifikate.PNG" is in the same Folder like my jupyter Notebook. 
I made the screenshot via "Windows" + "shift" + "S" for my Zertifikate.PNG
I use Jupyter Notebook via Anaconda.

If I use the coordinates of the Picture with r.click, it clicks on the Image. 
But why does it not work with the png file?
Attached is the complete Log and the Jupyter Code.

![fehlermeldung](https://user-images.githubusercontent.com/63077223/78379290-6a95b700-75d2-11ea-8719-ea17c1eae308.jpg)
![jupyter hub ausschnitt](https://user-images.githubusercontent.com/63077223/78379294-6b2e4d80-75d2-11ea-867f-7149a21b4933.jpg)

It took me the whole day now and I couldnt find the solution for Windows. 
I would be so glad if you can help me.

Btw: I am relatively new to programming.

Best regards

Pierre

**Comment by kensoh** [comment]
Hi Pierre, thanks for trying out this RPA package for Python! Hope you'll have fun using it.

The error happens when the provided image cannot be found on the screen. There are a few ideas to try to find out what was not working. 

1. From the error log it looks like the image file exists on your desktop Python folder, double check that the file exists there. It looks like it does.

2. Are you using multiple monitors (laptop monitor and a separate monitor)? It might not work as the tool is designed to work with a single screen. If yes, try disconnecting so that you are only using your laptop monitor.

3. Try changing your Windows system display zoom level to the recommended % or 100%. Try both to see if it helps. This is a common error [mentioned here](https://github.com/tebelorg/RPA-Python#rpa-for-python-snake). The reason is the snapshot of the image may actually be at a different zoom level from your desktop zoom level. So trying to do a match will fail as the image sizes are different to the computer vision engine.

Kind Regards,
Ken

**Comment by pierrekublik** [comment]
Hey kensoh, 

It was the display zoom. my Settings were 150 % and now it is 100% and it works fine.
You are a real genius, really apprecciate your help.

Looked over the Forum the whole day but acctually the answer was on page 1... learning from mistakes..

And yes, I really enjoy the package. I tested few Things I usually do with UiPath and it works in a similar manner.
And the best Thing: It is for free… just amazing.

Best regards

Pierre

**Comment by kensoh** [comment]
You're welcome Pierre! Feel free to post any issues you encounter when using the tool, or any suggestions on how the tool can be improved. With a simple but powerful API, it's designed to make development and deployment of automation very fast, have fun! 🚀

**Comment by ashoktcr** [comment]
Hello 
I am using MacOS Catalina and I am getting the same error "cannot find file.png"
Do I need to open the file, or folder to find it ?
Or I need to give exact file name "print(r.read('/Library/WebServer/Documents/as/RPA/upwork/testpdf.pdf'))" ?

**Comment by ashoktcr** [comment]
It works when I open the png file, but not working for pdf
