### ISSUE TITLE
snap() outside viewport - most likely is website intentionally blocking

### ISSUE THREAD

**Issue by PolyScrub** [tebelorg/RPA-Python#122]
Hello,
I am trying to use .snap() for elements located below a page, outside the viewport, however the images produced come out blank. I am aware this is a known limitation, and as of now I have tried 2 workarounds I found in the RPA-Python and TagUI forums:

1. Scrolling the page down with 
`r.dom('window.scrollBy(0,1000))`
Referencing https://github.com/tebelorg/RPA-Python/issues/115 

2. Running Chrome in headless mode and increasing height in tagui_config.txt
Referencing https://github.com/kelaberetiv/TagUI/issues/291 

Both solutions, and a combination of both, do not seem to work for me. Is there anything I should take note of, or are their other existing workarounds?

Thanks

**Comment by kensoh** [comment]
Hi @PolyScrub, by default when an element identifier is provided, the tool will auto-scroll down or up to the position on the page where the element is, before interacting with it.

However, if the element is not actually existing in the webpage yet, ie the website design is such that the element is only loaded and searchable after using scrolls down to load new items, then the auto-scroll will not work because in the first place the element does not yet exist.

There is a 3rd solution, which is to actually simulate the scrolling down as if it is done by user. You can run init(True) to enable this visual automation and keyboard automation feature. After that you can initiate a click on the browser first by providing an image snapshot of something unique on the browser.

This is to make sure that the browser is already in focus and in the foreground before you send below keypresses. Finally you can run something like below to simulate the user scrolling down the page, adjust accordingly to what works for your website. Or do a loop or something to scroll until the element is detected using present().

```
r.keyboard('[pagedown][pagedown]')
r.keyboard('[down][down][down]')
```

If this 3rd method fails, can you post your minimal script that can replicate the issue.

**Comment by PolyScrub** [comment]
This is the code i used:
```
import rpa as r

r.init(True)

r.url('https://pixabay.com/')

num = 9
#can change value of num to adjust number of images to be snapped
i = 1

while i < num:
    target = '//*[@id="content"]/div[2]/div[1]/div[1]/div['+ str(i) + ']'
    filename = 'img' + str(i) + '.png'
    r.snap(target, filename)
    i = i + 1
    print(i)
    if(i == 5):
        r.click('q')
        r.keyboard('[pagedown]')


#XPath of  snapped elements
#//*[@id="content"]/div[2]/div[1]/div[1]/div[1]
#//*[@id="content"]/div[2]/div[1]/div[1]/div[2]
#//*[@id="content"]/div[2]/div[1]/div[1]/div[3]
#...
```

r.keyboard('[pagedown]') does not seem to work. When the code reaches the 'if' statement inside the 'while' loop there is also a delay, and my address bar is also clicked while the script was running.

Regarding visual automation, I am currently using Ubuntu 18.04, and have thus followed https://sikulix-2014.readthedocs.io/en/latest/newslinux.html to setup visual automation. I have also tried using both "r.init(True)" and "r.init(visual_automation = True)"

Below is the rpa_python.log output:
```

START - automation started - Mon Apr 06 2020 19:27:30 GMT+0800 (+08)

LIVE MODE - type done to quit
 [RPA][STARTED]
[RPA][0] - listening for inputs
[RPA][1] - https://pixabay.com/
[RPA][1] - listening for inputs
[RPA][2] - exist_result = exist('//*[@id="content"]/div[2]/div[1]/div[1]/div[1]').toString()
[RPA][2] - listening for inputs
[RPA][3] - dump exist_result to rpa_python.txt
[RPA][3] - listening for inputs
[RPA][4] - snap //*[@id="content"]/div[2]/div[1]/div[1]/div[1] to img1.png
[RPA][4] - listening for inputs
[RPA][5] - exist_result = exist('//*[@id="content"]/div[2]/div[1]/div[1]/div[2]').toString()
[RPA][5] - listening for inputs
[RPA][6] - dump exist_result to rpa_python.txt
[RPA][6] - listening for inputs
[RPA][7] - snap //*[@id="content"]/div[2]/div[1]/div[1]/div[2] to img2.png
[RPA][7] - listening for inputs
[RPA][8] - exist_result = exist('//*[@id="content"]/div[2]/div[1]/div[1]/div[3]').toString()
[RPA][8] - listening for inputs
[RPA][9] - dump exist_result to rpa_python.txt
[RPA][9] - listening for inputs
[RPA][10] - snap //*[@id="content"]/div[2]/div[1]/div[1]/div[3] to img3.png
[RPA][10] - listening for inputs
[RPA][11] - exist_result = exist('//*[@id="content"]/div[2]/div[1]/div[1]/div[4]').toString()
[RPA][11] - listening for inputs
[RPA][12] - dump exist_result to rpa_python.txt
[RPA][12] - listening for inputs
[RPA][13] - snap //*[@id="content"]/div[2]/div[1]/div[1]/div[4] to img4.png
[RPA][13] - listening for inputs
[RPA][14] - exist_result = exist('q').toString()
[RPA][14] - listening for inputs
[RPA][15] - dump exist_result to rpa_python.txt
[RPA][15] - listening for inputs
[RPA][16] - click q
[RPA][16] - listening for inputs
[RPA][17] - keyboard [pagedown]
[RPA][17] - listening for inputs
[RPA][18] - exist_result = exist('//*[@id="content"]/div[2]/div[1]/div[1]/div[5]').toString()
[RPA][18] - listening for inputs
[RPA][19] - dump exist_result to rpa_python.txt
[RPA][19] - listening for inputs
[RPA][20] - snap //*[@id="content"]/div[2]/div[1]/div[1]/div[5] to img5.png
[RPA][20] - listening for inputs
[RPA][21] - exist_result = exist('//*[@id="content"]/div[2]/div[1]/div[1]/div[6]').toString()
[RPA][21] - listening for inputs
[RPA][22] - dump exist_result to rpa_python.txt
[RPA][22] - listening for inputs
[RPA][23] - snap //*[@id="content"]/div[2]/div[1]/div[1]/div[6] to img6.png
[RPA][23] - listening for inputs
[RPA][24] - exist_result = exist('//*[@id="content"]/div[2]/div[1]/div[1]/div[7]').toString()
[RPA][24] - listening for inputs
[RPA][25] - dump exist_result to rpa_python.txt
[RPA][25] - listening for inputs
[RPA][26] - snap //*[@id="content"]/div[2]/div[1]/div[1]/div[7] to img7.png
[RPA][26] - listening for inputs
[RPA][27] - exist_result = exist('//*[@id="content"]/div[2]/div[1]/div[1]/div[8]').toString()
[RPA][27] - listening for inputs
[RPA][28] - dump exist_result to rpa_python.txt
[RPA][28] - listening for inputs
[RPA][29] - snap //*[@id="content"]/div[2]/div[1]/div[1]/div[8] to img8.png
[RPA][29] - listening for inputs
```

**Comment by kensoh** [comment]
Hi @PolyScrub I'm afraid I'm not able to find a good solution. It looks like this webpage has built-in algorithms to prevent auto-downloading of images. For eg, when I try your code, the image alignment returns does not behave normally to give correct image location on the webpage. Also, it looks like an image cannot be clicked on if it is not already showing on the screen, that is not a usual behaviour of websites.

The most I could go is the following code. But it is also not working properly. When trying to hover away to prevent text caption it does not work. Also, when going back to previous page, sometimes the alignment gets reset to the top. My conclusion is this website intentionally has code embedded that makes it hard to download automatically. I can understand why, as they would consider the images as their assets.

Would recommend not trying to beat their anti-scrapping logic, because once broken they will probably update new methods to prevent the auto-download from working.

```py
import rpa as r
  
r.init()
r.url('https://pixabay.com')

num = 9

i = 1
while i <= num:

    # scroll down slightly per image
    r.dom('window.scrollBy(0,100)')

    # form target XPath and filename
    target = '(//*[@class="item"])['+ str(i) + ']'
    filename = 'img' + str(i) + '.png'

    # click on target image
    r.click(target)

    # to avoid text caption on image
    r.hover('logo')

    # snap image to target filename
    r.snap('media_container', filename)
    i = i + 1
    print(i)

    # go back to main page
    r.dom('window.history.back()')

r.close()
```

**Comment by PolyScrub** [comment]
@kensoh Noted. Thanks for your help!
