### ISSUE TITLE
Browser pop up message hangs & blocks execution - use visual automation

### ISSUE THREAD

**Issue by millancho** [tebelorg/RPA-Python#125]
Hi Ken!
I'm having this issue regarding a thread that keeps on running forever after a popup message appears when I click a button on Chrome through the UI. 
 
Here is an example of the message:
![image](https://user-images.githubusercontent.com/45853155/79403090-8a729680-7f53-11ea-80d8-24578d1e1228.png)

I've tried killing the process with things like sys.exit(r.click('//*[@id="generalForm"]/table[6]/tbody/tr/td/input')) but it keeps on going forever.

Any idea on how to fix this?

**Comment by millancho** [comment]
[RPA][30] - click //*[@id="generalForm"]/table[2]/tbody/tr[4]/td[2]/input
[RPA][30] - listening for inputs
[RPA][31] - exist_result = exist('//*[@id="generalForm"]/table[6]/tbody/tr/td/input').toString()
[RPA][31] - listening for inputs
[RPA][32] - dump exist_result to rpa_python.txt
[RPA][32] - listening for inputs
[RPA][33] - click //*[@id="generalForm"]/table[6]/tbody/tr/td/input

These are the last 7 lines of the logging when I turn debug to True

**Comment by kensoh** [comment]
Hi @millancho, yes this is expected behaviour. The reason is because a popup message box like this is a blocking event. That means control is never returned to RPA for Python until user manually clicks the button.

However, there is a workaround, you can try it to see if that works for your scenario. The workaround is to use visual automation and keyboard and mouse automation to do the automation steps, including launching of Chrome browser and entering the address.

Just do how a user will normally open Chrome and run something, there is also shortcut to go to address field or simply use the type() function using visual automation.

https://github.com/tebelorg/RPA-Python#visual-automationsee_no_evil

In this way, because the Chrome process is not connected natively to RPA for Python, such a popup window will not be blocking execution of your Python code. Try it and let me know if you run into problems!
