### ISSUE TITLE
Create EXE

### ISSUE THREAD

**Issue by MikeZnnam** [tebelorg/RPA-Python#130]
Is it possible to create an executable file out of the python script which uses your lib? I tried pyinstaller, but the created exe does not do anything.

Best,
Mike

**Comment by kensoh** [comment]
I haven't tried that, it looks like there are a few ways to create standalone exe to run a Python script. Another one mentioned here is py2exe - https://stackoverflow.com/questions/5458048/how-to-make-a-python-script-standalone-executable-to-run-without-any-dependency

However, due to the nature of how the package works (it'll download dependencies automatically when first run), with the standard methods above, it might still not work. Can you try if py2exe works for your use scenario?

Do share your use scenario so that I can figure out if there are other ways to achieve it. Main criteria needed for this package is to have python command available to run the Python script you created for automation. Internet access without firewall blocking to github.com is needed as well, but that can be overcome with the pack() and update() functions for offline deployments.

**Comment by MikeZnnam** [comment]
After reinstalling pyinstaller I tried again to create the exe and proceed ist on another notebook. And now its working 😃 All libs are kind of wrapped in the folder. That is awesome and brings up completely new possibilites! Next step now is trying to create a script which helps creating RPA scripts with Python RPA. I‘m kind of on fire now :P

**Comment by kensoh** [comment]
Oh wow that's very cool running as a standalone, I haven't tried something like that. Yes that is entirely possible and you can create very sophisticated stuffs with that. Have fun!
