### ISSUE TITLE
Read/Click one item after the other - use XPath identifier in a for loop

### ISSUE THREAD

**Issue by MikeZnnam** [tebelorg/RPA-Python#132]
I got a list of items. In sum 200. 
With Count() it is easy to figure out the whole amount: r.count("Bearbeiten mit Doppelklick")

But how is it possible to read one item after the other. The items have no unique IDs. All items are named "Bearbeiten mit Doppelklick". 

I tried various ways to place the number somewhere in the statement, but none is working. E.g.: r.read('Bearbeiten mit Doppelklick)[{120}]')

![grafik](https://user-images.githubusercontent.com/50210738/80457323-65a4f880-892f-11ea-9554-2320414cef42.png)

**Comment by kensoh** [comment]
Oh yes this is a common use case, you can try using XPath. In this case try the following -

```py
r.read('(//*[@title = "Bearbeiten mit Doppelklick"])[' + str(n) + ']')
```

You can do the above in a loop, example `for n in range(1,201):` to loop from 1 to 200, because XPath the element count starts from 1. Similar things can be done with CSS locators, but personally prefer XPath for all the wonderful things that can be done with it. Super flexible. 

XPath is a way of identifying webpage elements, can google for more info, I haven't really seen a single webpage that covers succinct good content for it. Most either is too much details for automation use cases, or too brief.

**Comment by kensoh** [comment]
Closing issue for now till further inputs!
