### ISSUE TITLE
r.init() - The system cannot find the path specified - user folder read-only

### ISSUE THREAD

**Issue by RedHyphen** [tebelorg/RPA-Python#134]
Hello,

When i run the sample (Yahoo search) python script in Windows 10 Home ("python3 sample.py"), r.init() triggers the output shown below.

![Capture](https://user-images.githubusercontent.com/54621344/80706775-72863f80-8b1b-11ea-9e8b-c9ca4dc9b1ea.PNG)

The rpa_python.log also shows nothing:

```
// NORMAL ENTRY FLOW FOR RPA FOR PYTHON ~ TEBEL.ORG



live
```

Regarding setup, I downloaded the zip folder of the master branch, ran pip3 install rpa inside the Windows console and then ran the python script

**Comment by kensoh** [comment]
Hi @RedHyphen there is no need to download from master branch of the zip. The step to install is simply `pip install rpa` or pip3 / pip2 depending on your environment.

After installing the package, the first time you run r.init(), it should auto-download the upstream TagUI project and install it automatically on your computer. It will also tell you the folder where TagUI will be installed. Do you see that happening or do you see any error messages shown during the auto-installation?

If you have missed the messages during that initial auto-installation, try doing `import rpa as r; r.setup() to force a re-installation of the TagUI dependency and let me know what you see.

I'm assuming above screenshot is all the message you see, and no other message saying don't use a folder with space, which is a known limitation - https://github.com/tebelorg/RPA-Python/issues/98

**Comment by RedHyphen** [comment]
Here is what's produced:

![Capture](https://user-images.githubusercontent.com/54621344/80732427-e1c15b00-8b3e-11ea-8d2f-db9655b031c3.PNG)

Apparently the tagui folder dosen't show up in my Roaming folder.

**Comment by kensoh** [comment]
I'm not sure why, from above message there is a `done. syncing TagUI with ...`

That message appears after the code makes sure that there is a tagui folder under the folder shown above. `C:\User\XXX\AppData\Roaming`. But you are saying that there is no tagui folder there. And for some reason, automating installing the MSVCR110.dll file failed with `cannot find the path specified. It could be some file access permission issue on your computer or some network related issue, implemented by your company IT policy.

Can you check -

1. What is the full path for the Roaming folder. Is there a space or a special character that makes the full path not accessible to the Python module?

2. Can you try on another computer (your work computer or your personal laptop or your friend computer), to see if the same error happens? If not check what is the difference in OS setup.

**Comment by RedHyphen** [comment]
I took a look at my Appdata folder, and it turns out it's on read only. However, disabling it does not seem to work. 

Instead I just changed all occurrences of `os.environ['APPDATA']` to some folder I had on my desktop, and now r.setup() and my RPA-Python scripts now run properly. Guess the problem's solved.

Is this a safe solution? Or is there a reason why you set the destination folder for the TagUI installation to default to the Appdata folder?

**Comment by kensoh** [comment]
Oh no wonder.

Yes if you change all occurrences of that it should work fine. The catch is when you update the package in future to a new release, the changes will be gone and you have to change again.

This APPDATA folder on Windows is the standard folder for applications to store their data, so there are normally many app folders there to store their data. I assume maybe in your case, your laptop is a company laptop that has an IT policy not allowing people to install apps freely or control the user data that can be saved on the Windows user account, that's why its read-only.

**Comment by kensoh** [comment]
Closing issue for now, but feel free to add on any inputs or questions!

**Comment by rotry0** [comment]
I'm running into the same problem, but I don't quite understand the solution @RedHyphen. Can you explain in a little more detail for this beginner here?

**Comment by podvillage-bit** [comment]
I had the same issue and it was so frustrating as I couldn't figure out for long time. Im glad I found this thread. thank you

still not sure why this happened though as the folder was writable and other apps are installed in there. I can create folders manually w no issue.

here is my solution: I manually changed the setup() function in tagup.py code. instead of "home_directory = tagui_location()", I hardcoded path to my documents folder home_dicrectory = "c:\\users\\username\\documents\\". ran python in command line, ran import rpa as r, then r.setup().  now it worked and installed tagui to documents folder. I then copied tagui to appdata\roaming\ dir and now r.init() worked. by doing this I voided changing 'AppData'. Hope this could help someone.
