### ISSUE TITLE
Windows task scheduler error - python.exe

### ISSUE THREAD

**Issue by ongkokl** [tebelorg/RPA-Python#141]
Hi there

I trying to run from windows task scheduler with a batch file.
"C:\Users\ongkokl\AppData\Local\Continuum\anaconda3\python.exe C:\folder\script.py"

But got the below "RPA" error "
![error](https://user-images.githubusercontent.com/50367330/80910079-b5385980-8d5f-11ea-9cfd-98bcab16f992.PNG)

**Comment by ongkokl** [comment]
Found the solution , changed the batch file 

Cd c:\users\your personal folder

**Comment by kensoh** [comment]
Hi @ongkokl yes, it looks like there is `Access is denied.` error message above.

This happens because the Task Scheduler normally starts running in C:\Windows\System32 or something like that. It is a system protected folder so a normal user permission will not be able to write to that folder, hence the error.

Also, the `your personal folder` must not have space in it. There is a limitation in one of the tools dependencies (CasperJS) that will trigger error if the full path of the script has space. It will treat that as 2 separate input parameters.

**Comment by iCreamble** [comment]
Hi.
This problem is happening to me on every folder I run the .bat from.
It happens when I use subprocess.call from another python, or if I use a .bat file...
It happens even if the folder I'm running from is the same folder as the original .py script.
Resuming: when I double click the script.py, the automation runs smoothly. But when I call the script from some other source, it gives this permission error.
Am I doing something wrong?

**Comment by kensoh** [comment]
Hi @iCreamble for this file permission error, I've personally come across a strange issue which may be related.

How did you install Python? Is it from the Windows store?

When I tried installing Python from Windows store (it will auto-install from there if user types python in command prompt and there is no python installed), I found that the Python installed is very strange. Output files creating from the python command are hidden and not even accessible from other processes and command prompt / explorer. It is as if the Python installation has its own access permissions and files created can only be accessed from within that Python.

After I uninstall and install Python from python.org, things works as expected.
