### ISSUE TITLE
The script sometimes works, sometimes not - Jython not available

### ISSUE THREAD

**Issue by Dima1506** [tebelorg/RPA-Python#150]
```python
import rpa as r
import os
r.init(visual_automation = True)
r.url('https://datastudio.google.com/navigation/reporting')
r.click('Publisher Dashboard 2.0 (Storytel Hub - Russia Self Publishing Portal)$
r.click("button collapse")
r.click("Consumption by title")
r.hover(900, 300)
#r.click("1")
#r.close()
```
The process sometimes does not start during initialization. Then I leave it and the following comment appears:
```bash
CTraceback (most recent call last):
  File "rpa_m.py", line 5, in <module>
    r.init(visual_automation = True)
  File "/usr/local/lib/python3.8/dist-packages/tagui.py", line 550, in init
    tagui_out = _tagui_read()
  File "/usr/local/lib/python3.8/dist-packages/tagui.py", line 118, in _tagui_read
    global _process; return _py23_decode(_process.stdout.readline())
KeyboardInterrupt
```
I use Ubuntu 18.04 Server and xfce.
Java OpenJDK=1.8.
Python3.8
Tagui 6.0

**Comment by kensoh** [comment]
Hi @Dima1506, I'm afraid I have not gotten feedback on this before and can't help other than pointing out that your error log above shows the `KeyboardInterrupt` exception, which happens when user key in Control+C or Delete, from Python docs -

https://docs.python.org/3/library/exceptions.html#KeyboardInterrupt

You can try adding a `r.debug(True)` before `r.init()` to see if there are more clues, but I doubt so. It seems to be some user or process or perhaps some special characters that is being sent to the tool that causes this. Also, your error message shows rpa_m.py, there isn't such a file in this package, perhaps this is a modified file you made.

**Comment by Dima1506** [comment]
I stopped him, it just did not start for about 15 minutes, i.e. init was launched and it all didn’t move anything to us and returned nothing. And the only information that I had. I will look now with debug thanks

**Comment by Dima1506** [comment]
> Hi @Dima1506, I'm afraid I have not gotten feedback on this before and can't help other than pointing out that your error log above shows the `KeyboardInterrupt` exception, which happens when user key in Control+C or Delete, from Python docs -
> 
> https://docs.python.org/3/library/exceptions.html#KeyboardInterrupt
> 
> You can try adding a `r.debug(True)` before `r.init()` to see if there are more clues, but I doubt so. It seems to be some user or process or perhaps some special characters that is being sent to the tool that causes this. Also, your error message shows rpa_m.py, there isn't such a file in this package, perhaps this is a modified file you made.

I add r.debug(True) and gave maximum priority to Python. And
![Screenshot from 2020-06-13 19-39-00](https://user-images.githubusercontent.com/13039142/84574268-f8013e80-adad-11ea-9b36-ec4922771caf.png)

**Comment by kensoh** [comment]
I assume that you have already followed below link from readme for Linux - :penguin: **Linux -** visual automation mode requires special setup on Linux, see how to [install OpenCV and Tesseract](https://sikulix-2014.readthedocs.io/en/latest/newslinux.html)

This error happens when the Jython software that comes packaged with this tool is somehow unavailable to work on your system. Try the following -

1. download Jython interpreter from https://raiman.github.io/SikuliX1/downloads.html
2. install the interpreter and google if any errors encountered on your Linux
3. try again to see if it works, if not it could be the user running the Python is different and does not have access to the installed Jython. make sure the terminal is the same user as the user installing Jython
4. if it still fails, try installing SikuliX manually on your system - http://sikulix.com and raise an issue to SikuliX GitHub page for errors encountered - https://github.com/RaiMan/SikuliX1/issues
