### ISSUE TITLE
Get InnerHTML from Browser - see this, innerHTML is text content

### ISSUE THREAD

**Issue by fgomezvalverde** [tebelorg/RPA-Python#153]
Hello.

Thank you for the great work. 

Im trying to get the InnerHTML from the DomElement,
I already try :
`r.read() and r.text` but both got me the text without HTML structure.

Then I tried using 
` r.dom("document.documentElement.innerHTML")` but with no result.

There is another way to get the HTML from the browser??

Cheers.

**Comment by kensoh** [comment]
For dom(), try `r.dom("return document.documentElement.innerHTML")`. However, from my experience, innerHTML property is really text string. There isn't a function in upstream TagUI project that can return the HTML structure of a particular element with its children, because that is not a typical use case for RPA to try to automate in a manual process.
