### ISSUE TITLE
How do I catch "[RPA][ERROR]" - some suggestions to check if error is encountered

### ISSUE THREAD

**Issue by ronisc** [tebelorg/RPA-Python#156]
Hi,

I would like to know how to catch [RPA][ERROR] so a script might continue differently if an error found.
For example, let's say you run:

`r.click('SomePic.PNG')`

and the PNG can't be found.
The script is throwing  [RPA][ERROR] ,saying that the picture can't be found,
**but** the script is running continue doing the rest regardless.
In that case, I would like to stop or do different things.

I have tried to wrap the command with 'try:', 
but as the error is handled try doesn't catch it. 

How do I catch "[RPA][ERROR]" ?

**Comment by udupa-varun** [comment]
I'd like to know the recommended way to do this too. But what I tried (new to RPA, great job!) seems to work. 
I'm running `r.click('SomePic.PNG')` only if `r.present('SomePic.PNG')` returns `True`. 
You could also check using `r.exist('SomePic.PNG')`, but I believe that waits for the timeout period before responding.

**Comment by kensoh** [comment]
Hi RPA for Python users, 🅗🅐🅟🅟🅨 ②⓪②①!

It has been many months since I last worked on this personal side project. Just want to shout out that this project is very much alive, and I hope to look into the 30+ issues raised since July (and bug-fixes if required) soon when I get a moment again.

Below are details if you are interested, why I'm away past few months and why I believe my darkest days are over 🍀🤞🏻🙏🏻

---

Since May last year, I've stopped all work to juggle with [my mum's critical illness](https://github.com/tebelorg/RPA-Python/issues/144), taking care of my toddler, and doing housework chores like cleaning and cooking. TBH, my wife and I felt that taking care of a baby and giving her the best nutrition (nursing and home-cooked organic food) and care requires at least 1.5 full-time headcount. There is no life to speak of, other than trying to stay afloat with baby care needs, and keep finding alternative ways to treat my mum, where there're some wins.

Eg importing soy-based tube feeds from Netherlands / Germany / Australia --> after switching away from milk-based tube feeds for 2 weeks she stops requiring dialysis. She started requiring 3x a week dialysis for more than 3 months, after admitting to the hospital. Also, applying herbs like mashed garlic or diced onions to her feet somehow consistently improve her breathing and lung function. Have to keep trying alternative healing methods when her recovery keeps hitting plateau in hospital.

She has been discharged from the hospital a month ago and recovering at home, though very slowly. A longterm medication seems to be one of the contributing causes for her condition. After stopping it, there seems to be improvement to her breathing capacity. She is still bed-bound, but over the course of the year I hope she'll regain strength to move about, and hopefully lungs to recover sufficiently to not require oxygen tank support through a tracheal mask (a hole through her throat).

---

Since November, I've gone back to work at [AI Singapore](https://www.aisingapore.org), a government-funded programme to accelerate AI in Singapore. I'm with Product Engineering team, focusing on RPA and [TagUI (open-source RPA tool)](https://github.com/kelaberetiv/TagUI), which RPA for Python is a wrapper for. There are pretty interesting stuffs on [TagUI 2021 roadmap](https://www.linkedin.com/posts/kensoh_tagui-rpa-v614-release-just-made-it-in-time-activity-6747502665758072833-6YUu). 2020 was the year which my family was going to move to the UK and work, after I receive its tier 1 exceptional tech talent visa. Then everything changed with the virus outbreak, and my mum's illness. The best thing that happened to me in 2020 was being able to go back to work at AI Singapore - I'm grateful.

I've just hired someone to help with housework, cooking and supporting my wife with baby care. I hope this new arrangement will allow me to deliver on my work at AI Singapore, and soon be able to reply countless friends' messages which circumstances leave me with no choice but go missing for months, and then look into the issues raised here!

Eg of the cost of best-in-class nutrition standard researched and set by wife. Baby just felt restless and broke her plate. Even Corelle's break-resistant plate breaks. Why not use plastic plate? Cuz plastic can leech toxins to the food on it. Why not use Silicon plate? Cuz there is no white silicon materials for plate. Why white? Cuz that helps to improve visibility of the food instead of contrasting against some pink colour or some other colours. I would be spending much time clearing up the mess of 70 over pieces of plate fragments, while baby gets nursed to calm down, if not for our newfound helper.

That's why I feel like my darkest days are over and now seeing glimpses of light at the end of the tunnel.

---

My vision for RPA for Python remains - I would like it to be the ***go-to Python package for RPA***.

A best-in-class tool in Python users toolbox which you combine with other cool packages to build amazing stuffs.

**Comment by udupa-varun** [comment]
@kensoh - Glad to hear you are staying positive. Good luck to you and the family!

**Comment by kensoh** [comment]
Thanks @udupa-varun ! Hi @ronisc what @udupa-varun said is correct.

For your usage scenario, if you do an error check on the steps that are potentially problematic, would it work for you?

It can be done by using r.present() or r.exist() to check, or using following to detect if False is returned.

```
if not r.click('abc'):
    # step to do something
    quit()
```

```
if not r.click('abc'):
    # function to do something and quit()
```

Also, this RPA for Python package is based on a forked version of TagUI open-source RPA tool.
Feel free to join Telegram community group chat to post any questions - https://t.me/rpa_chat
