### ISSUE TITLE
Unable to open file: rpa_python.js - PHP needs to be installed on Ubuntu, see this eg

### ISSUE THREAD

**Issue by dqtrung1702** [tebelorg/RPA-Python#157]
I am newbie with everything, help me plz
here my code:
```
import rpa as r

import os

os.chdir('/data/RPA/')

r.init()

 (venvdsmb) root@78337-DSMB02:/data/RPA# python3 test.py
[RPA][ERROR] - following happens when starting TagUI...

/root/.tagui/src/tagui: line 256: php: command not found
Unable to open file: /data/RPA/rpa_python.js

  phantomjs://code/bootstrap.js:113 in __die
Unable to load script /data/RPA/rpa_python.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die


```
I run: chmod -R 777 /data/RPA/ too. 

Thanks

**Comment by maoyuanqi** [comment]
Comment for better reach. I've met the same issue, or similar. Here is my error message:

Unable to load script C:\Users\Administrator\PycharmProjects\pythonProject\rpa_python.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die

I am currently running this on an AWS EC2 Windows Instance Server. hope to get any feedback

**Comment by xiphl** [comment]
I encountered this error the first time i run: r.init() from a machine that had no internet (I made use of r.pack() to transfer the necessary files over)
and saw the following msg: 
```
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - unzipping TagUI (~200MB) from rpa_python.zip to below folder...
[RPA][INFO] - C:\Users\IEUser\AppData\Roaming
[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][INFO] - now installing missing Visual C++ Redistributable dependency
[RPA][INFO] - MSVCR110.dll is still missing, install vcredist_x86.exe from
[RPA][INFO] - the vcredist_x86.exe file in C:\Users\IEUser\AppData\Roaming\tagui or from
[RPA][INFO] - https://www.microsoft.com/en-us/download/details.aspx?id=30679
[RPA][INFO] - after that, TagUI ready for use in your Python environment
```
The second time round I ran r.init() (without addressing the error msgs above) , I saw the same error msg as above:
```
[RPA][ERROR] - following happens when starting TagUI...

Unable to load script C:\Users\IEUser\Documents\rpa_python.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die
```

What solved the problem for me is to follow the instructions and download & install a newer version of vcredist_x86 from the Microsoft link given and the error message never appeared again.

**Comment by kensoh** [comment]
Hi RPA for Python users, 🅗🅐🅟🅟🅨 ②⓪②①!

It has been many months since I last worked on this personal side project. Just want to shout out that this project is very much alive, and I hope to look into the 30+ issues raised since July (and bug-fixes if required) soon when I get a moment again.

Below are details if you are interested, why I'm away past few months and why I believe my darkest days are over 🍀🤞🏻🙏🏻

---

Since May last year, I've stopped all work to juggle with [my mum's critical illness](https://github.com/tebelorg/RPA-Python/issues/144), taking care of my toddler, and doing housework chores like cleaning and cooking. TBH, my wife and I felt that taking care of a baby and giving her the best nutrition (nursing and home-cooked organic food) and care requires at least 1.5 full-time headcount. There is no life to speak of, other than trying to stay afloat with baby care needs, and keep finding alternative ways to treat my mum, where there're some wins.

Eg importing soy-based tube feeds from Netherlands / Germany / Australia --> after switching away from milk-based tube feeds for 2 weeks she stops requiring dialysis. She started requiring 3x a week dialysis for more than 3 months, after admitting to the hospital. Also, applying herbs like mashed garlic or diced onions to her feet somehow consistently improve her breathing and lung function. Have to keep trying alternative healing methods when her recovery keeps hitting plateau in hospital.

She has been discharged from the hospital a month ago and recovering at home, though very slowly. A longterm medication seems to be one of the contributing causes for her condition. After stopping it, there seems to be improvement to her breathing capacity. She is still bed-bound, but over the course of the year I hope she'll regain strength to move about, and hopefully lungs to recover sufficiently to not require oxygen tank support through a tracheal mask (a hole through her throat).

---

Since November, I've gone back to work at [AI Singapore](https://www.aisingapore.org), a government-funded programme to accelerate AI in Singapore. I'm with Product Engineering team, focusing on RPA and [TagUI (open-source RPA tool)](https://github.com/kelaberetiv/TagUI), which RPA for Python is a wrapper for. There are pretty interesting stuffs on [TagUI 2021 roadmap](https://www.linkedin.com/posts/kensoh_tagui-rpa-v614-release-just-made-it-in-time-activity-6747502665758072833-6YUu). 2020 was the year which my family was going to move to the UK and work, after I receive its tier 1 exceptional tech talent visa. Then everything changed with the virus outbreak, and my mum's illness. The best thing that happened to me in 2020 was being able to go back to work at AI Singapore - I'm grateful.

I've just hired someone to help with housework, cooking and supporting my wife with baby care. I hope this new arrangement will allow me to deliver on my work at AI Singapore, and soon be able to reply countless friends' messages which circumstances leave me with no choice but go missing for months, and then look into the issues raised here!

Eg of the cost of best-in-class nutrition standard researched and set by wife. Baby just felt restless and broke her plate. Even Corelle's break-resistant plate breaks. Why not use plastic plate? Cuz plastic can leech toxins to the food on it. Why not use Silicon plate? Cuz there is no white silicon materials for plate. Why white? Cuz that helps to improve visibility of the food instead of contrasting against some pink colour or some other colours. I would be spending much time clearing up the mess of 70 over pieces of plate fragments, while baby gets nursed to calm down, if not for our newfound helper.

That's why I feel like my darkest days are over and now seeing glimpses of light at the end of the tunnel.

---

My vision for RPA for Python remains - I would like it to be the ***go-to Python package for RPA***.

A best-in-class tool in Python users toolbox which you combine with other cool packages to build amazing stuffs.

**Comment by kubow** [comment]
Hello @kensoh 
my antivirus (kaspersky) also messed up with phantomjs (even with installation - I had to do all things manually).
Now I had various errors when I try to enable manually, thus I would like to start from over.
How can I approach?  
I tried uninstalling and installing again but nothing changed.

**Comment by Lossme8** [comment]
> I am newbie with everything, help me plz
> here my code:
> 
> ```
> import rpa as r
> 
> import os
> 
> os.chdir('/data/RPA/')
> 
> r.init()
> 
>  (venvdsmb) root@78337-DSMB02:/data/RPA# python3 test.py
> [RPA][ERROR] - following happens when starting TagUI...
> 
> /root/.tagui/src/tagui: line 256: php: command not found
> Unable to open file: /data/RPA/rpa_python.js
> 
>   phantomjs://code/bootstrap.js:113 in __die
> Unable to load script /data/RPA/rpa_python.js; check file syntax
> 
>   phantomjs://code/bootstrap.js:113 in __die
> ```
> 
> I run: chmod -R 777 /data/RPA/ too.
> 
> Thanks

Hi have you, or has anyone got a workaround for this? I am facing a similar blocker? 
Any pointers would be highly appreciated.

**Comment by kensoh** [comment]
Hi @dqtrung1702 @maoyuanqi and @Lossme8, in the above error message, there is mention of PHP missing.

During initial run, downloading and installing of TagUI, if it is detected that there is PHP missing, there should be a message like below telling user to install PHP. This is because some Linux system like Ubuntu does not have PHP. Is it true that you guys are running on Ubuntu? Try installing PHP using below instructions to see if that helps and let me know?

```
[RPA][INFO] - PHP is not installed by default on your Linux distribution
[RPA][INFO] - google how to install PHP (eg for Ubuntu, apt-get install php)
[RPA][INFO] - after that, TagUI ready for use in your Python environment
[RPA][INFO] - visual automation (optional) requires special setup on Linux
[RPA][INFO] - see the link below to install OpenCV and Tesseract libraries
[RPA][INFO] - https://sikulix-2014.readthedocs.io/en/latest/newslinux.html
```

**Comment by kensoh** [comment]
Following is a working Google Colab notebook showing how the package can be run in Ubuntu -

https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

With PHP installed and working, the error that you encounter will be resolved. Closing issue for now.

Also, this RPA for Python package is based on a forked version of TagUI open-source RPA tool.
Feel free to join Telegram community group chat to post any questions - https://t.me/rpa_chat

**Comment by miuniao28z** [comment]
> Comment for better reach. I've met the same issue, or similar. Here is my error message:
> 
> Unable to load script C:\Users\Administrator\PycharmProjects\pythonProject\rpa_python.js; check file syntax
> 
> phantomjs://code/bootstrap.js:113 in __die
> 
> I am currently running this on an AWS EC2 Windows Instance Server. hope to get any feedback

The same issue i have. It work after installed Visual C++ Redistributable.
 ps: https://tagui.readthedocs.io/en/latest/setup_troubleshooting.html#troubleshooting-windows
