### ISSUE TITLE
ERROR - use .tag extension for flow filename - pending checks and more clues

### ISSUE THREAD

**Issue by e2com** [tebelorg/RPA-Python#166]
C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\python.exe D:/workspaces/python/python_sample/RPA/pra-test.py
[RPA][ERROR] - following happens when starting TagUI...

ERROR - use .tag extension for flow filename
ERROR - automation aborted due to above 
gawk: cmd. line:2: fatal: cannot open file `D:\workspaces\python\python_sample\RPA\rpa_python.raw' for reading (No such file or directory)
gawk: cmd. line:2: fatal: cannot open file `D:\workspaces\python\python_sample\RPA\rpa_python.js' for reading (No such file or directory)

[RPA][ERROR] - use init() before using url()

Process finished with exit code 0

----------------------------------------------------------------------
안녕하세요...
RPA 을 배워볼까 하는데... 위와 같은 오류가 발생 됩니다. 
어떤 대안이 있을까요?

Hi!!!
I'm going to learn RPA... I get the above error.
What are the alternatives?

**Comment by caoyanbin1993** [comment]
me too

**Comment by caoyanbin1993** [comment]
‘’‘PS E:\500-Program\python\tagui> python main.py
[RPA][ERROR] - following happens when starting TagUI...

ERROR - use .tag extension for flow filename
ERROR - automation aborted due to above 
gawk: cmd. line:2: fatal: cannot open file `E:\500-Program\python\tagui\rpa_python.raw' for reading (No such file or directory)
gawk: cmd. line:2: fatal: cannot open file `E:\500-Program\python\tagui\rpa_python.js' for reading (No such file or directory)

[RPA][ERROR] - use init() before using url()  
[RPA][ERROR] - use init() before using type() 
[RPA][ERROR] - use init() before using read() 

[RPA][ERROR] - use init() before using snap() 
[RPA][ERROR] - use init() before using close()‘’‘

**Comment by lfernandes** [comment]
Here is similar.

```
[RPA][ERROR] - following happens when starting TagUI...
ERROR - cannot find rpa_python
ERROR - automation aborted due to above

...
```

**Comment by chlimaferreira** [comment]
I have the same error.
Did you manage to solve?

**Comment by kensoh** [comment]
Hi RPA for Python users, 🅗🅐🅟🅟🅨 ②⓪②①!

It has been many months since I last worked on this personal side project. Just want to shout out that this project is very much alive, and I hope to look into the 30+ issues raised since July (and bug-fixes if required) soon when I get a moment again.

Below are details if you are interested, why I'm away past few months and why I believe my darkest days are over 🍀🤞🏻🙏🏻

---

Since May last year, I've stopped all work to juggle with [my mum's critical illness](https://github.com/tebelorg/RPA-Python/issues/144), taking care of my toddler, and doing housework chores like cleaning and cooking. TBH, my wife and I felt that taking care of a baby and giving her the best nutrition (nursing and home-cooked organic food) and care requires at least 1.5 full-time headcount. There is no life to speak of, other than trying to stay afloat with baby care needs, and keep finding alternative ways to treat my mum, where there're some wins.

Eg importing soy-based tube feeds from Netherlands / Germany / Australia --> after switching away from milk-based tube feeds for 2 weeks she stops requiring dialysis. She started requiring 3x a week dialysis for more than 3 months, after admitting to the hospital. Also, applying herbs like mashed garlic or diced onions to her feet somehow consistently improve her breathing and lung function. Have to keep trying alternative healing methods when her recovery keeps hitting plateau in hospital.

She has been discharged from the hospital a month ago and recovering at home, though very slowly. A longterm medication seems to be one of the contributing causes for her condition. After stopping it, there seems to be improvement to her breathing capacity. She is still bed-bound, but over the course of the year I hope she'll regain strength to move about, and hopefully lungs to recover sufficiently to not require oxygen tank support through a tracheal mask (a hole through her throat).

---

Since November, I've gone back to work at [AI Singapore](https://www.aisingapore.org), a government-funded programme to accelerate AI in Singapore. I'm with Product Engineering team, focusing on RPA and [TagUI (open-source RPA tool)](https://github.com/kelaberetiv/TagUI), which RPA for Python is a wrapper for. There are pretty interesting stuffs on [TagUI 2021 roadmap](https://www.linkedin.com/posts/kensoh_tagui-rpa-v614-release-just-made-it-in-time-activity-6747502665758072833-6YUu). 2020 was the year which my family was going to move to the UK and work, after I receive its tier 1 exceptional tech talent visa. Then everything changed with the virus outbreak, and my mum's illness. The best thing that happened to me in 2020 was being able to go back to work at AI Singapore - I'm grateful.

I've just hired someone to help with housework, cooking and supporting my wife with baby care. I hope this new arrangement will allow me to deliver on my work at AI Singapore, and soon be able to reply countless friends' messages which circumstances leave me with no choice but go missing for months, and then look into the issues raised here!

Eg of the cost of best-in-class nutrition standard researched and set by wife. Baby just felt restless and broke her plate. Even Corelle's break-resistant plate breaks. Why not use plastic plate? Cuz plastic can leech toxins to the food on it. Why not use Silicon plate? Cuz there is no white silicon materials for plate. Why white? Cuz that helps to improve visibility of the food instead of contrasting against some pink colour or some other colours. I would be spending much time clearing up the mess of 70 over pieces of plate fragments, while baby gets nursed to calm down, if not for our newfound helper.

That's why I feel like my darkest days are over and now seeing glimpses of light at the end of the tunnel.

---

My vision for RPA for Python remains - I would like it to be the ***go-to Python package for RPA***.

A best-in-class tool in Python users toolbox which you combine with other cool packages to build amazing stuffs.

**Comment by kensoh** [comment]
Hi Guys, the error `ERROR - use .tag extension for flow filename` can only appear if TagUI human language version is installed (v6.14 etc). For RPA for Python, it uses a forked version of TagUI (v5.17) which will not show this message.

Can you try to remove the human language version of TagUI if you have installed, and delete the TagUI that this package installed, and try again? For Mac Linux, the location of TagUI for this package is in ~/.tagui folder and for Windows it is in %APPDATA%\tagui folder.

Below are some checks from issue #190 which are for other causes of init() not working, but is different from `.tag extension` error message issue. Lastly, this RPA package is based on a forked version of TagUI open-source RPA tool. Free feel to join Telegram group chat for TagUI community to post any questions - https://t.me/rpa_chat

---

Hi Guys, can you try the latest package with `pip install rpa --upgrade` and let me know if it works now?

- There has been a fix implemented to run on macOS properly, in response to a recent macOS change
- For Ubuntu, still require to install PHP with `apt-get update; apt install php;`
- For Linux OSes, the default for this package is to use Chrome, so Chrome browser needs to be installed
- For Linux or macOS, Chrome does not allow a user to run it as root, a hack is needed if you really need root
- Using Chromium browser is possible but a simple hack is required to change the package default to use Chromium
- Using Microsoft Edge is also possible but a hack would be needed until upstream TagUI supports Edge option

Below is a working Google Colab notebook with some of the above hacks implemented fyi - 
https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing
