### ISSUE TITLE
Lets say.. I am opening "https://www.amazon.in" now I will type "iphone 11" in search bar then hit ENTER. It will be listing few related items below.. now I want to click on one of them say "Apple iPhone 11 - Purple". Its getting opened in new tab.. (by default becuase of amazon source page). Next command wa to take screenshot of it.. so I used rpa.snap('page', 'iphone.png'). Its taking screenshot of the previous opened tab in which I have related items.. In comment I have pasted the code I am using. Please help to fix it. 

### ISSUE THREAD

**Issue by asheesh123** [tebelorg/RPA-Python#173]

**Comment by asheesh123** [comment]
`import rpa as r
r.init(visual_automation=True)
r.url('https://www.amazon.in/')

r.type('//*[@id="twotabsearchtextbox"]', 'iphone 11[enter]')

r.click('Apple iPhone 11 - Purple')

r.snap('page', 'results.png')
r.close()
`

**Comment by ck81** [comment]
TagUI works only with the primary browser window.  That's the page that TagUI is connected.  When your browser opens up new tabs, TagUI has not connections with those pages.  Hence it cannot interact with those pages.

For your case, the common way of using TagUI is like this:
1) Go to your Amazon page
2) using `r.read()` to grab the URLs of all those links you are interested.  You can do this easily with a for loop and the right XPath to the links
3) Once you have the URLs, e.g. in an array, you now use `r.url()` to go to each link so that the page you are interested in is displayed in the same window
4) Loop through all the links one by one and grab any information you are interested in

Using this approach, there will be only one browser tab.  All information you want to grab will be through this main page.

Hope this helps.

**Comment by asheesh123** [comment]
Resolved

**Comment by kensoh** [comment]
Adding on @asheesh123 , you can use the popup() function to specify the new tab to automate on -
https://github.com/tebelorg/RPA-Python#pro-functions

However, the best way would probably be what @ck81 suggested to build array of URLs and process them directly.
