### ISSUE TITLE
无法 r.init() - looks like network issue blocking downloads from github.com, see ideas

### ISSUE THREAD

**Issue by wuhao5925968** [tebelorg/RPA-Python#189]
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - C:\Users\86132\AppData\Roaming

**Comment by waileong94** [comment]
Having same issue here, file dont seem to be downloading

**Comment by vhills** [comment]
同问，有没有人解答下，下载完还有一个无法下载
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - C:\Users\vhills\AppData\Roaming
[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][ERROR] - failed downloading from https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui...
<urlopen error [Errno 11004] getaddrinfo failed>

**Comment by kensoh** [comment]
Hi RPA for Python users, 🅗🅐🅟🅟🅨 ②⓪②①!

It has been many months since I last worked on this personal side project. Just want to shout out that this project is very much alive, and I hope to look into the 30+ issues raised since July (and bug-fixes if required) soon when I get a moment again.

Below are details if you are interested, why I'm away past few months and why I believe my darkest days are over 🍀🤞🏻🙏🏻

---

Since May last year, I've stopped all work to juggle with [my mum's critical illness](https://github.com/tebelorg/RPA-Python/issues/144), taking care of my toddler, and doing housework chores like cleaning and cooking. TBH, my wife and I felt that taking care of a baby and giving her the best nutrition (nursing and home-cooked organic food) and care requires at least 1.5 full-time headcount. There is no life to speak of, other than trying to stay afloat with baby care needs, and keep finding alternative ways to treat my mum, where there're some wins.

Eg importing soy-based tube feeds from Netherlands / Germany / Australia --> after switching away from milk-based tube feeds for 2 weeks she stops requiring dialysis. She started requiring 3x a week dialysis for more than 3 months, after admitting to the hospital. Also, applying herbs like mashed garlic or diced onions to her feet somehow consistently improve her breathing and lung function. Have to keep trying alternative healing methods when her recovery keeps hitting plateau in hospital.

She has been discharged from the hospital a month ago and recovering at home, though very slowly. A longterm medication seems to be one of the contributing causes for her condition. After stopping it, there seems to be improvement to her breathing capacity. She is still bed-bound, but over the course of the year I hope she'll regain strength to move about, and hopefully lungs to recover sufficiently to not require oxygen tank support through a tracheal mask (a hole through her throat).

---

Since November, I've gone back to work at [AI Singapore](https://www.aisingapore.org), a government-funded programme to accelerate AI in Singapore. I'm with Product Engineering team, focusing on RPA and [TagUI (open-source RPA tool)](https://github.com/kelaberetiv/TagUI), which RPA for Python is a wrapper for. There are pretty interesting stuffs on [TagUI 2021 roadmap](https://www.linkedin.com/posts/kensoh_tagui-rpa-v614-release-just-made-it-in-time-activity-6747502665758072833-6YUu). 2020 was the year which my family was going to move to the UK and work, after I receive its tier 1 exceptional tech talent visa. Then everything changed with the virus outbreak, and my mum's illness. The best thing that happened to me in 2020 was being able to go back to work at AI Singapore - I'm grateful.

I've just hired someone to help with housework, cooking and supporting my wife with baby care. I hope this new arrangement will allow me to deliver on my work at AI Singapore, and soon be able to reply countless friends' messages which circumstances leave me with no choice but go missing for months, and then look into the issues raised here!

Eg of the cost of best-in-class nutrition standard researched and set by wife. Baby just felt restless and broke her plate. Even Corelle's break-resistant plate breaks. Why not use plastic plate? Cuz plastic can leech toxins to the food on it. Why not use Silicon plate? Cuz there is no white silicon materials for plate. Why white? Cuz that helps to improve visibility of the food instead of contrasting against some pink colour or some other colours. I would be spending much time clearing up the mess of 70 over pieces of plate fragments, while baby gets nursed to calm down, if not for our newfound helper.

That's why I feel like my darkest days are over and now seeing glimpses of light at the end of the tunnel.

---

My vision for RPA for Python remains - I would like it to be the ***go-to Python package for RPA***.

A best-in-class tool in Python users toolbox which you combine with other cool packages to build amazing stuffs.

**Comment by wjl1627** [comment]
>>> r.init()
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - C:\Users\JalanWang\AppData\Roaming
[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][ERROR] - failed downloading from https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui...
<urlopen error [Errno 11004] getaddrinfo failed>


I also encountered this problem to solve.

**Comment by wjl1627** [comment]
this url "https://raw.githubusercontent.com/" is not found...

**Comment by wjl1627** [comment]
Solved, refer to the following connection.
[https://www.cnblogs.com/sinferwu/p/12726833.html](url)

**Comment by HelloZhou3301** [comment]
> Solved, refer to the following connection.
> [https://www.cnblogs.com/sinferwu/p/12726833.html](url)

when i open the url, there is nothing linked to id, can you tell me how to solve the problems in r.init()

**Comment by HelloZhou3301** [comment]
> [RPA][INFO] - setting up TagUI for use in your Python environment
> [RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
> [RPA][INFO] - C:\Users\86132\AppData\Roaming

hava you solved the problem?

**Comment by wjl1627** [comment]
> > Solved, refer to the following connection.
> > [https://www.cnblogs.com/sinferwu/p/12726833.html](url)
> 
> when i open the url, there is nothing linked to it, can you tell me how to solve the problems in r.init()

If you are a windows system.

> C:\Windows\System32\drivers\etc\hosts
add :

**Comment by HelloZhou3301** [comment]
> 同问，有没有人解答下，下载完还有一个无法下载
> [RPA][INFO] - setting up TagUI for use in your Python environment
> [RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
> [RPA][INFO] - C:\Users\vhills\AppData\Roaming
> [RPA][INFO] - done. syncing TagUI with stable cutting edge version
> [RPA][ERROR] - failed downloading from https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui...
> <urlopen error [Errno 11004] getaddrinfo failed>

你在tagui.py里面找出这几个判断，然后直接改成return True看看，记得将源码备份一个

**Comment by wjl1627** [comment]
> > 同问，有没有人解答下，下载完还有一个无法下载
> > [RPA][INFO] - setting up TagUI for use in your Python environment
> > [RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
> > [RPA][INFO] - C:\Users\vhills\AppData\Roaming
> > [RPA][INFO] - done. syncing TagUI with stable cutting edge version
> > [RPA][ERROR] - failed downloading from https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui...
> > <urlopen error [Errno 11004] getaddrinfo failed>
> 
> 你在tagui.py里面找出这几个判断，然后直接改成return True看看，记得将源码备份一个

还没解决？？？上面方式不行就要科学上网，改hosts

**Comment by HelloZhou3301** [comment]
我在windows上没有这些info，但是init之后它在窗口显示‘[tagui] START&nbsp; - listening for inputs’，然后就一直不动了，您知道怎么解决吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tebelorg/RPA-Python"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 中午11:38
收件人:&nbsp;"tebelorg/RPA-Python"<RPA-Python@noreply.github.com&gt;;
抄送:&nbsp;"周楚程"<1070160286@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tebelorg/RPA-Python] 无法r.init() (#189)





   
同问，有没有人解答下，下载完还有一个无法下载
 [RPA][INFO] - setting up TagUI for use in your Python environment
 [RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
 [RPA][INFO] - C:\Users\vhills\AppData\Roaming
 [RPA][INFO] - done. syncing TagUI with stable cutting edge version
 [RPA][ERROR] - failed downloading from https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui...
 <urlopen error [Errno 11004] getaddrinfo failed&gt;
  
你在tagui.py里面找出这几个判断，然后直接改成return True看看，记得将源码备份一个
  
还没解决？？？上面方式不行就要科学上网，改hosts

**Comment by StoneFeng** [comment]
I have the same issue, anyone solved the problem ?

**Comment by kensoh** [comment]
Hi Guys, I've put in a new release v1.30 over the weekend. You can see if `pip install rpa --upgrade` solves the problem.

If it is due to connection issue due to firewall and internet, @fi-do has a PR (https://github.com/tebelorg/RPA-Python/pull/207) which lets user set the installation directory (you can download the required files manually first from https://github.com/tebelorg/Tump/releases/tag/v1.0.0 and https://github.com/tebelorg/Tump/tree/master/TagUI-Python).

I'll be working with him to merge back to master, but you can use his solution in the meantime (https://github.com/tebelorg/RPA-Python/pull/207)

**Comment by kensoh** [comment]
Adding on, you can also use pack() or update() to generate a zip file on a computer with internet access.

Then move the generated file to your company computer to use the package.

**Comment by kensoh** [comment]
You can also join Telegram group chat for TagUI community to post any questions - https://t.me/rpa_chat

PS - this RPA package is based on a forked version of TagUI open-source RPA tool
