### ISSUE TITLE
r.init() or t.init() hangs - get latest package version, try this checks and let me know

### ISSUE THREAD

**Issue by prashanttrivedi47** [tebelorg/RPA-Python#190]
import rpa as r
r.init()

or

import tagui as t
t.init()

Both halt didn't get response from this

Already installed- phantomjs, php, rpa
Platform - ubuntu

**Comment by fePereira** [comment]
Having same issue here, trying to setup a new environment on a blank Ubuntu 18.04.5 LTS.

**Comment by fePereira** [comment]
Returned True for: r.init(chrome_browser = False)

**Comment by prashanttrivedi47** [comment]
> Returned True for: r.init(chrome_browser = False)

But we need a browser to open

**Comment by fePereira** [comment]
> > Returned True for: r.init(chrome_browser = False)
> 
> But we need a browser to open

So do I

**Comment by prashanttrivedi47** [comment]
> > > Returned True for: r.init(chrome_browser = False)
> > 
> > 
> > But we need a browser to open
> 
> So do I

If you will give chrome_browser=True, so how Chrome browser open if you will try r.url(link), if you able to do that so please let me know

**Comment by prashanttrivedi47** [comment]
> > > > Returned True for: r.init(chrome_browser = False)
> > > 
> > > 
> > > But we need a browser to open
> > 
> > 
> > So do I
> 
> If you will give chrome_browser=True, so how Chrome browser open if you will try r.url(link), if you able to do that so please let me know

I think, you should try ahead of init

**Comment by fePereira** [comment]
> > > > Returned True for: r.init(chrome_browser = False)
> > > 
> > > 
> > > But we need a browser to open
> > 
> > 
> > So do I
> 
> If you will give chrome_browser=True, so how Chrome browser open if you will try r.url(link), if you able to do that so please let me know

Unable to do so, worked only on visual_automation... I've a web automation setup working now somehow with 'chenhan/lubuntu-desktop-18.10' vagrant box. Couldn't figure out why didn't worked on a blank 18.04...

**Comment by gnaaromat** [comment]
I have the same problem on Elementary OS (18.04 equivalent)
b 
It does not work from a jupyter lab notebook.
I can write a script and run it from an ssh connection: Will also never time out.
The same script running from a Terminal (now I connected through xrdp to the machine) works fine. Script also works fine on win10.
Somehow it can't init tagui from a non-gnome-bound terminal.

**Comment by PravinAlhat** [comment]
I am using Mac and it's absolutely working fine for me.

import rpa as r
r.init()
r.url(URL)

It opens up the chrome browser and loads the desired URL. I will pass chrome_browser = False when I want to perform OCR automation i.e. r.int(visual_automation = True, chrome_browser = False). For visual automation, I will just pass visual_automation = True to r.init(). Otherwise, by default, it does open the browser with r.init(). Please help me to understand the scenario where we only pass the argument chrome_browser = False to r.init() which may be something I am not aware of.
I am using Pycharm so not sure about the jupyter lab notebook.

**Comment by prashantboss** [comment]
I have found a permanent solution for that is only you have to install curl in your machine "sudo apt-get install curl", that's it

**Comment by gnaaromat** [comment]
Not really a solution, without curl it shouldn't have worked anyways..

@PravinAlhat Log into your machine with SSH then try running the script (or in my case I'm connecting to a notebook server from another machine - notebook server was started via cron startup).
As long as I remote desktop into my machine and open a terminal on the UI, it works. If I login through SSH, it doesnt. Even if I have a remote desktop session open at the very same time.

**Comment by kensoh** [comment]
Hi RPA for Python users, 🅗🅐🅟🅟🅨 ②⓪②①!

It has been many months since I last worked on this personal side project. Just want to shout out that this project is very much alive, and I hope to look into the 30+ issues raised since July (and bug-fixes if required) soon when I get a moment again.

Below are details if you are interested, why I'm away past few months and why I believe my darkest days are over 🍀🤞🏻🙏🏻

---

Since May last year, I've stopped all work to juggle with [my mum's critical illness](https://github.com/tebelorg/RPA-Python/issues/144), taking care of my toddler, and doing housework chores like cleaning and cooking. TBH, my wife and I felt that taking care of a baby and giving her the best nutrition (nursing and home-cooked organic food) and care requires at least 1.5 full-time headcount. There is no life to speak of, other than trying to stay afloat with baby care needs, and keep finding alternative ways to treat my mum, where there're some wins.

Eg importing soy-based tube feeds from Netherlands / Germany / Australia --> after switching away from milk-based tube feeds for 2 weeks she stops requiring dialysis. She started requiring 3x a week dialysis for more than 3 months, after admitting to the hospital. Also, applying herbs like mashed garlic or diced onions to her feet somehow consistently improve her breathing and lung function. Have to keep trying alternative healing methods when her recovery keeps hitting plateau in hospital.

She has been discharged from the hospital a month ago and recovering at home, though very slowly. A longterm medication seems to be one of the contributing causes for her condition. After stopping it, there seems to be improvement to her breathing capacity. She is still bed-bound, but over the course of the year I hope she'll regain strength to move about, and hopefully lungs to recover sufficiently to not require oxygen tank support through a tracheal mask (a hole through her throat).

---

Since November, I've gone back to work at [AI Singapore](https://www.aisingapore.org), a government-funded programme to accelerate AI in Singapore. I'm with Product Engineering team, focusing on RPA and [TagUI (open-source RPA tool)](https://github.com/kelaberetiv/TagUI), which RPA for Python is a wrapper for. There are pretty interesting stuffs on [TagUI 2021 roadmap](https://www.linkedin.com/posts/kensoh_tagui-rpa-v614-release-just-made-it-in-time-activity-6747502665758072833-6YUu). 2020 was the year which my family was going to move to the UK and work, after I receive its tier 1 exceptional tech talent visa. Then everything changed with the virus outbreak, and my mum's illness. The best thing that happened to me in 2020 was being able to go back to work at AI Singapore - I'm grateful.

I've just hired someone to help with housework, cooking and supporting my wife with baby care. I hope this new arrangement will allow me to deliver on my work at AI Singapore, and soon be able to reply countless friends' messages which circumstances leave me with no choice but go missing for months, and then look into the issues raised here!

Eg of the cost of best-in-class nutrition standard researched and set by wife. Baby just felt restless and broke her plate. Even Corelle's break-resistant plate breaks. Why not use plastic plate? Cuz plastic can leech toxins to the food on it. Why not use Silicon plate? Cuz there is no white silicon materials for plate. Why white? Cuz that helps to improve visibility of the food instead of contrasting against some pink colour or some other colours. I would be spending much time clearing up the mess of 70 over pieces of plate fragments, while baby gets nursed to calm down, if not for our newfound helper.

That's why I feel like my darkest days are over and now seeing glimpses of light at the end of the tunnel.

---

My vision for RPA for Python remains - I would like it to be the ***go-to Python package for RPA***.

A best-in-class tool in Python users toolbox which you combine with other cool packages to build amazing stuffs.

**Comment by HelloZhou3301** [comment]
> import rpa as r
> r.init()
> 
> or
> 
> import tagui as t
> t.init()
> 
> Both halt didn't get response from this
> 
> Already installed- phantomjs, php, rpa
> Platform - ubuntu

hello，i have the same problem, have you solved it, can you tell me the solution?

**Comment by prashanttrivedi47** [comment]
> > import rpa as r
> > r.init()
> > or
> > import tagui as t
> > t.init()
> > Both halt didn't get response from this
> > Already installed- phantomjs, php, rpa
> > Platform - ubuntu
> 
> hello，i have the same problem, have you solved it, can you tell me the solution?

Please check by installing curl
sudo apt-get install curl

**Comment by HelloZhou3301** [comment]
what about the solution in windows10, i can use 'curl --help' however, when i init,it still halt: in command promt shows '[tagui] START&nbsp; - listening for inputs' but can't continue




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tebelorg/RPA-Python"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月3日(星期三) 下午4:57
收件人:&nbsp;"tebelorg/RPA-Python"<RPA-Python@noreply.github.com&gt;;
抄送:&nbsp;"周楚程"<1070160286@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tebelorg/RPA-Python] r.init() or t.init() is halt (#190)





   
import rpa as r
 r.init()
 or
 import tagui as t
 t.init()
 Both halt didn't get response from this
 Already installed- phantomjs, php, rpa
 Platform - ubuntu
  
hello，i have the same problem, have you solved it, can you tell me the solution?
  
Please check by installing curl
 sudo apt-get install curl

**Comment by mmu-acid21** [comment]
Please note my comment above. If there is no real error message you can find and simply tries to init forever or just breaks on taglib init, you probably dont have a screen attached to whatever session you tried. 

Not sure how this would be possible on Windows though, even if you used jupyter lab through the network it should have the user's screen(and inputs) attached.

For @kensoh to be able to debug this, I think we should start collecting our environments in a taglib issue.

So again: This is not an RPA-Python issue but a taglib issue

**Comment by gnaaromat** [comment]
Please note my comment above. If there is no real error message you can find and simply tries to init forever or just breaks on taglib init, you probably dont have a screen attached to whatever session you tried.

Not sure how this would be possible on Windows though, even if you used jupyter lab through the network it should have the user's screen(and inputs) attached.

For @kensoh to be able to debug this, I think we should start collecting our environments in a taglib issue.

So again: This is not an RPA-Python issue but a taglib issue

**Comment by prashanttrivedi47** [comment]
> Please note my comment above. If there is no real error message you can find and simply tries to init forever or just breaks on taglib init, you probably dont have a screen attached to whatever session you tried.
> 
> Not sure how this would be possible on Windows though, even if you used jupyter lab through the network it should have the user's screen(and inputs) attached.
> 
> For @kensoh to be able to debug this, I think we should start collecting our environments in a taglib issue.
> 
> So again: This is not an RPA-Python issue but a taglib issue

Please firstly check phantomjs in your env. this is dependency you have to need to run rpa, if not in your env it will halt after init() bcz it require to run chrome in automation

**Comment by prashanttrivedi47** [comment]
Environment required to run RPA -> PHP, CURL, PhantomJS, SlimmerJs(Optional), Java

**Comment by HelloZhou3301** [comment]
> import rpa as r
> r.init()
> 
> or
> 
> import tagui as t
> t.init()
> 
> Both halt didn't get response from this
> 
> Already installed- phantomjs, php, rpa
> Platform - ubuntu

I think you can change your path to chrome.exe in `/tagui/src/tagui.cmd`. In tagui.cmd there is a command :`set chrome_command=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` change the path, then it may work

**Comment by kensoh** [comment]
Hi Guys, can you try the latest package with `pip install rpa --upgrade` and let me know if it works now?


- There has been a fix implemented to run on macOS properly, in response to a recent macOS change
- For Ubuntu, still require to install PHP with `apt-get update; apt install php;`
- For Linux OSes, the default for this package is to use Chrome, so Chrome browser needs to be installed
- For Linux or macOS, Chrome does not allow a user to run it as root, a hack is needed if you really need root
- Using Chromium browser is possible but a simple hack is required to change the package default to use Chromium
- Using Microsoft Edge is also possible but a hack would be needed until upstream TagUI supports Edge option

Below is a working Google Colab notebook with some of the above hacks implemented fyi - 
https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

Also, free feel to join Telegram group chat for TagUI community to post any questions - https://t.me/rpa_chat

PS - this RPA package is based on a forked version of TagUI open-source RPA tool
