### ISSUE TITLE
ERROR - use .tag extension for flow filename - likely accidentally overwrite with TagUI

### ISSUE THREAD

**Issue by 9trees** [tebelorg/RPA-Python#194]
Hi I've been trying to setup python rpa in pycharm venv and keep facing the following error.
*I've sorted out path issues

cleared missing .dll issue
setpath to php, so php is working
###Leaving pycharm i tried running "tagui live" its working but if i run tagui rpa_python chrome nothing works.

r.setup()
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - C:\Users\sivashankar.palraj\AppData\Roaming
[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][INFO] - TagUI now ready for use in your Python environment
True
r.init()
[RPA][ERROR] - following happens when starting TagUI...
ERROR - use .tag extension for flow filename
ERROR - automation aborted due to above
gawk: cmd. line:2: fatal: cannot open file C:\Users\sivashankar.palraj\PycharmProjects\rpa_testing\rpa_python.raw' for reading (No such file or directory) gawk: cmd. line:2: fatal: cannot open file C:\Users\sivashankar.palraj\PycharmProjects\rpa_testing\rpa_python.js' for reading (No such file or directory)
False

it fails running line no 520 tagui_cmd = tagui_executable + ' rpa_python ' + browser_option
in tagui.py

**Comment by kensoh** [comment]
Hi RPA for Python users, 🅗🅐🅟🅟🅨 ②⓪②①!

It has been many months since I last worked on this personal side project. Just want to shout out that this project is very much alive, and I hope to look into the 30+ issues raised since July (and bug-fixes if required) soon when I get a moment again.

Below are details if you are interested, why I'm away past few months and why I believe my darkest days are over 🍀🤞🏻🙏🏻

---

Since May last year, I've stopped all work to juggle with [my mum's critical illness](https://github.com/tebelorg/RPA-Python/issues/144), taking care of my toddler, and doing housework chores like cleaning and cooking. TBH, my wife and I felt that taking care of a baby and giving her the best nutrition (nursing and home-cooked organic food) and care requires at least 1.5 full-time headcount. There is no life to speak of, other than trying to stay afloat with baby care needs, and keep finding alternative ways to treat my mum, where there're some wins.

Eg importing soy-based tube feeds from Netherlands / Germany / Australia --> after switching away from milk-based tube feeds for 2 weeks she stops requiring dialysis. She started requiring 3x a week dialysis for more than 3 months, after admitting to the hospital. Also, applying herbs like mashed garlic or diced onions to her feet somehow consistently improve her breathing and lung function. Have to keep trying alternative healing methods when her recovery keeps hitting plateau in hospital.

She has been discharged from the hospital a month ago and recovering at home, though very slowly. A longterm medication seems to be one of the contributing causes for her condition. After stopping it, there seems to be improvement to her breathing capacity. She is still bed-bound, but over the course of the year I hope she'll regain strength to move about, and hopefully lungs to recover sufficiently to not require oxygen tank support through a tracheal mask (a hole through her throat).

---

Since November, I've gone back to work at [AI Singapore](https://www.aisingapore.org), a government-funded programme to accelerate AI in Singapore. I'm with Product Engineering team, focusing on RPA and [TagUI (open-source RPA tool)](https://github.com/kelaberetiv/TagUI), which RPA for Python is a wrapper for. There are pretty interesting stuffs on [TagUI 2021 roadmap](https://www.linkedin.com/posts/kensoh_tagui-rpa-v614-release-just-made-it-in-time-activity-6747502665758072833-6YUu). 2020 was the year which my family was going to move to the UK and work, after I receive its tier 1 exceptional tech talent visa. Then everything changed with the virus outbreak, and my mum's illness. The best thing that happened to me in 2020 was being able to go back to work at AI Singapore - I'm grateful.

I've just hired someone to help with housework, cooking and supporting my wife with baby care. I hope this new arrangement will allow me to deliver on my work at AI Singapore, and soon be able to reply countless friends' messages which circumstances leave me with no choice but go missing for months, and then look into the issues raised here!

Eg of the cost of best-in-class nutrition standard researched and set by wife. Baby just felt restless and broke her plate. Even Corelle's break-resistant plate breaks. Why not use plastic plate? Cuz plastic can leech toxins to the food on it. Why not use Silicon plate? Cuz there is no white silicon materials for plate. Why white? Cuz that helps to improve visibility of the food instead of contrasting against some pink colour or some other colours. I would be spending much time clearing up the mess of 70 over pieces of plate fragments, while baby gets nursed to calm down, if not for our newfound helper.

That's why I feel like my darkest days are over and now seeing glimpses of light at the end of the tunnel.

---

My vision for RPA for Python remains - I would like it to be the ***go-to Python package for RPA***.

A best-in-class tool in Python users toolbox which you combine with other cool packages to build amazing stuffs.

**Comment by fi-do** [comment]
Hey 9trees,
why do you call setup ? I would try to initialize my r object with the init function.
`r.init()`
Please rename your flow file to "rpa_python.tag". And also execute tagui with the complete name of the flow file.
`tagui rpa_python.tag chrome`

Have you checked if the file rpa_python.js really exists in the folder?

Hope it will help you.

**Comment by kensoh** [comment]
Thanks @fi-do! Adding on, @9trees the error message on .tag extension only happens on TagUI v6.14 but the TagUI version that RPA for Python is using is a forked version which is a v5.X. I believe what likely has happened is you have downloaded the latest TagUI and accidentally overwrite the copy downloaded by this package. You can try deleting the folder or renaming the folder to force download. On Windows, the folder RPA for Python use will be `os.environ['APPDATA'] + '/' + 'tagui'`

**Comment by kensoh** [comment]
This issue should be similar to https://github.com/tebelorg/RPA-Python/issues/212

**Comment by ZhaoJiangJie** [comment]
As @kensoh said above, I encountered the same error, the error has disappear and work normally since I am using v5.11 instead of v6.14.
