### ISSUE TITLE
[RPA][ERROR] - use init() before using url() 

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#198]
Hello,
Currently, I started learning about RPA Python. I am almost new. I need a help.
when I try to write code in python, it is showing the below information: 
[RPA][INFO] - to use RPA for Python on Windows, avoid space in folder path name, 
[RPA][ERROR] - use init() before using url()

Can anyone please help me? where is the problem?
![problem 01](https://user-images.githubusercontent.com/76218957/103925254-873dbd00-5117-11eb-80e7-92d8e0de8f19.JPG)

**Comment by arunkhemlai** [comment]
> [RPA][INFO] - to use RPA for Python on Windows, avoid space in folder path name,

Make sure that the path to your source code does not contain 'spaces'

**Comment by emshihab008** [comment]
Thank you for your information. I have another question. I have seen that the directory of TAGUI setup is default (:c/users/......) . But the problem is that my default user folder name contains "space" . In this case, how can I change the path location of TAGUI setup?
Because when I ran the code in python, TAGUI Setup has started automatically and selected path location automatically.

**Comment by fi-do** [comment]
Hey emshihab008,
it looks like there is currently no easy way to configure the installation directory during Python initialization. 

One suggestion is to override the value of home_directory at the setup function in tagui.py. And add tagui src to your Windows environment path.
Another suggestion is to install tagui manually and override your env variables.

Really hope this helps you, unfortunately I can't check it because I do not have Windows system.

**Comment by NS-27** [comment]
I am also having this issue on a company laptop, but there does not seem to be any spaces in the folder path or my username...

**Comment by kensoh** [comment]
Adding a note that in upstream TagUI project, there's an open issue to review any permanent solution for space issue -

https://github.com/kelaberetiv/TagUI/issues/987

**Comment by jsantos42** [comment]
@emshihab008 I ran across the same error. It turns out I didn't have openJDK installed. That fixed the issue!
