### ISSUE TITLE
Is it possible to use Firefox/Chromium? - Chromium yes, Firefox requires v59 only

### ISSUE THREAD

**Issue by matt32106** [tebelorg/RPA-Python#201]
Sorry I couldn't find documentation on this, but is it possible to init firefox (or chromium) instead of chrome? and how?
If it matters this is on a linux box.

**Comment by fi-do** [comment]
Hey matt32106,
the following symlink worked for me:
`ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome`
Maybe this workaround leads to problems, but [check](https://github.com/kelaberetiv/TagUI/issues/336) it out for yourself.

**Comment by kensoh** [comment]
Thanks @fi-do for sharing this hack!

Hi @matt32106 another way is to modify tagui file directly to call Chromium instead. 

In Linux, the file should be `~/.tagui/src/tagui`, change the chrome_command setting to below to run Chromium -

```
chrome_command="chromium-browser"
```

For Firefox, v59 is possible but it is very old version already. If you want to try, first look for the tagui.py by doing `r.__file__`, that folder contains the tagui.py file. After that, in the file search for `browser_option` and change it from chrome to firefox.

Note that this has not been tested for a very long time since v59 is a long time ago, so it may not work as expected or at all.

**Comment by kensoh** [comment]
Adding on, automating Microsoft Edge is also doable with a 2-3 lines of change in tagui.cmd. But this is for Windows only.
