### ISSUE TITLE
RPA not working in VDI machine - pending checks and more details of replication

### ISSUE THREAD

**Issue by rsidella** [tebelorg/RPA-Python#202]
Hi ,

Need some help , We wrote a program in python using RPA  to open an App , click some button images  on app and publish the content. Program works fine on windows machine but it  does not work on VDI machine, RPA (r. Click ) is giving error saying not able to find the file, same code works fine on windows but not on VDI. Any idea if RPA works on VDI machine.

Appreciate your quick response.

-Koti

**Comment by kensoh** [comment]
Hi Koti, can you check the following?

Make sure the folder is the correct folder with the image file. In your Python script, just before the r.click(), you can do the following to print the output of the current directory. Then you can check if there is really an image file there.

```py
import os; print(os.getcwd())
```
I haven't hear feedback from other users that the tool can't run on virtual desktop. Most importantly there must be a real user session that is logged in, this is so that there is a display screen being rendered. Without a display screen rendered, computer vision can't be used to click on the image identifier.
