### ISSUE TITLE
'utf-8' codec can't decode byte 0x80 in position 65: invalid start byte on init() - chcp?

### ISSUE THREAD

**Issue by hc-hyun** [tebelorg/RPA-Python#215]
![109378088-05962e80-7913-11eb-9bdb-a2dffb3fc667](https://user-images.githubusercontent.com/79739657/109383515-43eb1800-792a-11eb-90e0-6aed84faaeba.png)

Dear kensoh,
I got this error when try to call init(). I'm not sure but, It seems that tagui's initail message has undecodeable text.

C:\Users\hc.hyun>tagui c:\tagui\flows\samples\1_google.tag
START - automation started - Sat Feb 27 2021 15:38:00 GMT+0900 (?�?쒕?援??쒖???

FYI, My windows use korean. If possible, please check this issue. Thanks in advance!

**Comment by hc-hyun** [comment]
C:\Users\{{user}}\AppData\Roaming\tagui\src\tagui_header.js

// save start time to measure execution time
//var automation_start_time = Date.now(); casper.echo('\nSTART - automation started - ' + Date().toLocaleString());
var automation_start_time = Date.now(); casper.echo('\nSTART - automation started');

FYI, I fixed like above for test, and then error was gone.

**Comment by kensoh** [comment]
Thanks @hc-hyun for sharing back your solution! For Windows command prompt, I believe there is a need to use `chcp` command to change code page to the correct language in order to display the local language correctly.

Below is an example but for Chinese - http://www.walkernews.net/2013/05/19/how-to-get-windows-command-prompt-displays-chinese-characters/

I'll close this issue for now, but if this is a common issue for Korean users, then it is probably a good idea to discuss whether to hack this thing permanently so that the date of automation start does not show up and cause this error.
