### ISSUE TITLE
Headless mode cannot find element error? - bug with newer Chrome versions [fixed]

### ISSUE THREAD

**Issue by prashanttrivedi47** [tebelorg/RPA-Python#216]
Script running in alpine image docker container
running in chromium headless mode

can not find a xpath -  
eg 1.    r.type('/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div[1]/div/div[1]/div/div[1]/input', 'something@mail.com'))
eg 2. 
r.type('//*[@id="identifierId"]', 'something@mail.com')

=> this return a False and error
=>r.init() and r.url('https://www.google.com') returns True

[RPA][ERROR] - cannot find /html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div[1]/div/div[1]/div/div[1]/input

Can you please tell me that why r.type() is returning a error ?

Note: script running normally in ubuntu but not in container docker

**Comment by Dka233** [comment]
I don't think this is the better way to find the place in website to write your 'something@mail.com'. For example, if you want to write something in the comment box in GitHub you should write: 

r.type('//*[@id="new_comment_field"]', 'something@mail.com') as you write in your eg2. 

If you are getting an error maybe it is because your form is inside of an iframe, I had this kind of problem.

Regards.

**Comment by fi-do** [comment]
Hey @prashanttrivedi47,
can you give the following hack a [try](https://github.com/tebelorg/RPA-Python/issues/109#issuecomment-594280514)?

Hope it will help you,
fi-do

**Comment by prashanttrivedi47** [comment]
> Hey @prashanttrivedi47,
> can you give the following hack a [try](https://github.com/tebelorg/RPA-Python/issues/109#issuecomment-594280514)?
> 
> Hope it will help you,
> fi-do

I have already tried , I have changed from chrome to headless but didn't work

**Comment by kensoh** [comment]
Thanks @prashanttrivedi47 for raising this! The package is not designed to run headless mode, but this should be fixed.

I believe this is likely due to a bug in newer Chrome version. When it runs in headless mode, one of the parameters used can no longer support calling a relative directory but the absolute directory to the TagUI Chrome user profile is now required.

More details on the issue - https://github.com/kelaberetiv/TagUI/issues/890

Can you try make the following changes to your tagui file to see if that works. In a future release this will be fixed.

https://github.com/kelaberetiv/TagUI/commit/3da665f3baa0a5a62378c7d0a646f8f803758df3

The tagui file that you want to modify is ~/.tagui/src/tagui (where ~ is your user home directory)

**Comment by kensoh** [comment]
This is fixed in v1.31, available with `pip install rpa --upgrade`
