### ISSUE TITLE
Hangs at setting up TagUI for use in your Python environment - likely network issue

### ISSUE THREAD

**Issue by HelloZhou3301** [tebelorg/RPA-Python#217]
![image](https://user-images.githubusercontent.com/42287015/109743939-776cc180-7c0c-11eb-9a5c-bdc00ae2b21d.png)

**Comment by Edwardlove** [comment]
I also encountered the same problem，Maybe you can try to modify the init() source code ，make sure the path for tagui is right，and ignore some 'if' , it works to me, I can't install tagui by pychram for some reason, maybe the 'great wall' I guess. so I downloaded tagui from github, mabe tagui version is different, in rpa souce code, some path in _tagui_delta() can not be found in my tagui file.

**Comment by kensoh** [comment]
Hi @HelloZhou3301 and @Edwardlove, are you still facing this issue?

This issue usually happens because from your network when the package tries to download from github.com domain it is not successful and keeps trying. The TagUI that is running on your computer seems to be downloaded separately because it is v6.14. For RPA for Python it is based on a fork of TagUI optimised for Python purpose and it should show v5.X.

Below are the Python commands to try to replicate. You are also likely to hang there the process.

**for python 2**
```py
import urllib; urllib.urlretrieve('https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Linux.zip', 'TagUI_Linux.zip')
```
\
**for python 3**
```py
import urllib.request; urllib.request.urlretrieve('https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Linux.zip', 'TagUI_Linux.zip')
```
\
If download works, then other possible reason could be write access problem to /home/zhou folder though v unlikely.

**Comment by kensoh** [comment]
If replicating really hangs, you can try commenting away below block in tagui.py and then
downloading directly to `/home/zhou` from other ways which you can download files.
```py
        if not download(tagui_zip_url, home_directory + '/' + tagui_zip_file):
            # error message is shown by download(), no need for message here
            return False
```
The location of tagui.py file can be found with r.__file__, that same folder there is a tagui.py file.
