### ISSUE TITLE
Explore whether it's viable to package TagUI as part of the package on pypi.org

### ISSUE THREAD

**Issue by kensoh** [tebelorg/RPA-Python#226]
A user use case is in his company, can do pip install rpa. But the TagUI dependencies that gets pulled in from github.com domains are blocked. Opening this issue to explore whether packaging together is possible so the download from pypi.org does not get blocked.

Main blocker is pypi.org upload limit is 60MB. Anything beyond is blocked from publishing. Perhaps can get special exclusion from pypi.org team / maintainers??

**Comment by kensoh** [comment]
Adding on an update that user tried using urllib.request and setting proxy but got 403, seems like the url is getting blocked. He doesn't think packaging it with the python code is the right approach. For his company's case, probably someone would have to submit a request to get the tool onboarded.

**Comment by fi-do** [comment]
Hey @kensoh,
when this issue came up I started to tinker around with the tagui archive.
My first though was to use different compression algorithms, but there was no big impact.

Secondly, I was checking which files/directory take a huge amount of space in the archive. The reasons are Sikulix and Phantomjs for the large memory requirement. So my suggestion was to remove the jar files and extend the installation to download sikulix and phantomjs directly from bitbucket and launchpad. So the archive was small enough to fit in a pypi project. 
But as mentioned, this packaging would be not the right approach.

Maybe reworking the whole package structure is not the right way for this problem. Possibly extend the infrastructure with some little mirrors could be an approach? So basically if someone can't access this host, another host maybe around the area will be tried out.

**Comment by kensoh** [comment]
Thanks @fi-do for sharing your thoughts!!

Yes SikuliX comes in the form of a large .jar file (due to OpenCV and Tesseract also embedded in it). Otherwise, just PhantomJS alone won't exceed the 60MB limit. In addition, for Windows there is PHP in the download and that will add on to the total size.

However, if large files were to be downloaded from separate sources, it still would not work for above user's environment. His intranet is very secured and only allows downloading Python packages from mirrors of pypi.org and not GitHub and most probably not LaunchPad or BitBucket.

For reference, below is the URL to request additional size limit - 
https://github.com/pypa/pypi-support/issues/new/choose

And the guidelines for a successful request -
https://github.com/pypa/pypi-support#guidelines-for-upload-limit-requests

One way I can think of is creating another dummy package that automatically breaks up a large zip into a few releases capped at 50MB. That way, it is possible to download that dummy package's multiple releases and automatically combines them into a single zip for further processing.

However, I find that way to be somewhat hackish to go around PyPi's usage guidelines. If their guidelines are meant to block certain usage, then going around like that with a dummy package won't be a permanent robust solution. I'll check more with the user who raised this!

**Comment by kensoh** [comment]
Shelving this idea for now. Though it might be possible to do so, it doesn't seem to be the right way to host at pypi.org.

See if other users bring up this issue going forward, to determine whether to reopen this thread and evaluate again.
