### ISSUE TITLE
Bundling RPA .py script using py2app for macOS - pending user testing and logs

### ISSUE THREAD

**Issue by ibnmukthar** [tebelorg/RPA-Python#241]
So as a quick and easy way to share my automation with my family or co-workers to use I decided to use Py2App to bundle my RPA script which is using RPA and Tkinter packages. When directly running the RPA script it works perfectly, GUI opens up, and when I click the button to automate everything runs properly. 
This is the setup.py script I used to bundle the rpa script:

```
from setuptools import setup
APP = ['WorkflowAutomator.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'site_packages': True,
    'iconfile': 'robot.icns',
    'packages': ['rpa', 'tkinter'],
    'plist': {
        'CFBundleName': 'Workflow Automator',
    }
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
```

Then I created the .app by executing:
`python3 setup.py Py2App`
So now when I click the to open the .app executable application, the GUI opens up fine. But when I click the button to automate my workflow, Java opens up but nothing else happens. 
I've already enabled the application to control the computer in System Preferences, so I'm not sure what's gone wrong here.

**Comment by kensoh** [comment]
Hi @ibnmukthar I haven't heard from users using Py2App or share their experience with this. To get started, try the following -

In your Python automation script, include r.debug(True). This will retain execution logs like rpa_python.log which you can attach back here. Since this is macOS installation, you can try running below command from your friend mac laptop to see what is the real problem. Let me know if the following works. Then maybe issue is with computer vision, which you'll need to install OpenJDK 64-bit separately. That is not 'auto-installable' but a warning message will appear during running if it is missing.

```
~/.tagui/src/tagui ~/.tagui/src/samples/1_yahoo
```
