### ISSUE TITLE
r.init() returns False when running on Google Colab - see working Colab notebook

### ISSUE THREAD

**Issue by weihenglim** [tebelorg/RPA-Python#247]
After installing the necessary components and running
```
import rpa as r
r.init()
```
it returns False with not much information to go off on
```
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - /root
[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][INFO] - TagUI now ready for use in your Python environment
[RPA][INFO] - visual automation (optional) requires special setup on Linux,
[RPA][INFO] - see the link below to install OpenCV and Tesseract libraries
[RPA][INFO] - https://sikulix-2014.readthedocs.io/en/latest/newslinux.html
[RPA][ERROR] - following happens when starting TagUI...
False
```
Help would be appreciated.

**Comment by kensoh** [comment]
Hi @weihenglim can you share your code to prep environment and install the package before running?

Below is an example for TagUI the human language version. A few things to consider will be which browser because on Ubuntu need to install browser. Depending on whether Chrome or Chromium gets installed, modification may be needed to run the correct browser. Also, as Colab doesn't have a display, the tool can only run in headless mode, which also needs to modify some file to do so. Lastly, Ubuntu requires PHP to be installed.

https://github.com/kelaberetiv/TagUI/issues/913

**Comment by weihenglim** [comment]
Hi @kensoh,  below is the code snippet for the environment prep
```
!apt-get update; apt install php; apt install chromium-browser; 
!pip install rpa
```
I have also set `chrome_command="chromium-browser"` in `~/.tagui/src/tagui`

**Comment by kensoh** [comment]
Hi @weihenglim here's the link to a working Colab notebook. There's a need to make some modifications to use Chromium browser instead and in headless mode (because there is no display screen on Colab) and as root (default Colab user).

Can you share more about how you are using the package this way? Running on Colab though you can develop and test RPA script, you can't see the web browser and have to make use of functions like r.snap() or r.text() to 'see' the webpage.

**https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing**

```py
# setup RPA environment by installing PHP, Chromium web browser and RPA for Python
!apt-get update; apt install php; apt install chromium-browser; pip install rpa
 
# run r.setup() to download TagUI, hack to run Chromium headless mode as root user
import rpa as r; r.setup(); r.dump(r.load('/root/.tagui/src/tagui').replace('"google-chrome"', '"chromium-browser"').replace('export tagui_web_browser', 'tagui_web_browser="headless"\nexport tagui_web_browser').replace('--disable-gpu', '--disable-gpu --no-sandbox'), '/root/.tagui/src/tagui')
```
```py
# run sample web automation workflow on RPA for Python GitHub page
# r.close() not needed at the end since Colab will self-destruct
r.init()
r.url('https://www.google.com')
r.type('//*[@name="q"]', 'decentralization[enter]')
print(r.read('result-stats'))
r.snap('page', 'results.png')
```
```py
# validate that the search results image snapshot exists and show the file's properties
!ls -l results.png
```
```py
# [OPTIONAL] with Chrome browser you can download RPA output files to computer or phone
from google.colab import files; files.download('results.png')
```

**Comment by weihenglim** [comment]
Hi @kensoh, thanks for the working solution.

I am currently using RPA for data scraping automation so running in headless mode is not an issue.
