### ISSUE TITLE
PyCharm not detecting OpenJDK - pending enabling Java version in PyCharm

### ISSUE THREAD

**Issue by sangasangasanga** [tebelorg/RPA-Python#248]
I have installed OpenJDK. However, when I run sample scripts (visual automation) in pycharm, there is an error.
![image](https://user-images.githubusercontent.com/34553270/117272641-f6d97400-ae8d-11eb-8328-f320bd1e105e.png)
![image](https://user-images.githubusercontent.com/34553270/117273529-cc3beb00-ae8e-11eb-8c84-835bd4279ea7.png)

**Comment by kensoh** [comment]
Hi @sangasangasanga, a possible cause could be PyCharm environment does not have access to this Java.

Can you try the following in PyCharm and let me know is the Java version output, and whether 0 is returned?

```py
import os
print(os.system('java -version'))
```

**Comment by sangasangasanga** [comment]
hi @kensoh this is the output it returns
![image](https://user-images.githubusercontent.com/34553270/117389059-597a5080-af1e-11eb-9e50-d22c1978440d.png)

**Comment by kensoh** [comment]
I see, this looks like the root cause, from PyCharm environment the Java is not accessible.

I'm not familiar with PyCharm, but found the guide below on choosing the Java version that PyCharm uses. Can you see if the information there is useful to help you choose and make Java available?

https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

**Comment by kensoh** [comment]
Also, this is needed only if you run r.init(True) to enable computer vision, OCR, low-level keyboard and mouse control.

For web-base automation this is usually not needed.
