### ISSUE TITLE
Using Edge, r.init(chrome_browser=False) still opens a browser - hack limitation

### ISSUE THREAD

**Issue by TheBoojah** [tebelorg/RPA-Python#250]
I'm using the 'hack' to use edge (chromium) instead of chrome, which is working perfectly.
However running r.init(visual_automation = True, chrome_browser = False) opens edge anyway.

Not a big issue, but I hope this can be fixed if edge is officially supported. Please let me know if there is a workaround though.
Thanks!

**Comment by kensoh** [comment]
Hi @TheBoojah I see, yes any hack only workaround the limitation as the package and TagUI does not yet support Edge. In future release later this year I believe this will be supported because MS IE is phasing out and people are moving to Edge.

Oh I think you are using your own downloaded copy of TagUI. Because the copy that RPA for Python uses is a custom forked version. That one does not work with - in the options. Because Edge is not supported, I don't think you can easily hack to both enable Edge and also enable the scenario where you can run without opening browser.

I'll recommend not using a downloaded copy of TagUI v6.14 because you should be facing problems using it with RPA for Python. That version and the forked version for this package has deviate in their codebase and only the forked is designed and tested to work well with this package.

**Comment by TheBoojah** [comment]
I see, thanks!
Yeah, my network is blocked so the auto setup was not able to download the files. (pip worked fine to download the rpa python package however. Its just github that is blocked here.) I thought that I manually downloaded the same file that the code does (github.com/tebelorg/Tump/releases/download/v1.0.0/tagui_zip_file), but I was messing around a lot so there might be mistakes from my side there, I might have missed something in the _tagui_delta function.
I'll keep this in mind if other stuff misbehaves, but so far it seems to be working alright except for this issue. I'll try the pack() function if stuff keeps misbehaving...

**Comment by kensoh** [comment]
I see, sure! Yes, use r.pack() and r.update() from your personal laptop with internet will be the recommended way to move external files into the intranet. The dependency might be able to request pypi.org to allow attached large files as part of the release, but that is usually a bad practice for pypi.org guideline. Will keep a lookout if more users having problem with accessing github.com and see if there are other hosting sites which allow access from their network.

Will close the issue for now, but I believe upstream TagUI will add Edge support later this year and this package will also inherit that option.
