### ISSUE TITLE
pip install rpa:  Defaulting to user installation because normal site-packages is not writeable

### ISSUE THREAD

**Issue by TetraGenius** [tebelorg/RPA-Python#254]
When using
pip install rpa:  
is this a problem?  "Defaulting to user installation because normal site-packages is not writeable"

**Comment by kensoh** [comment]
It seems that this issue pops up for [many people for affecting various Python packages](https://www.reddit.com/r/learnpython/comments/fm5kqs/trying_to_install_a_package_but_normal). But there isn't a clear solution other than asking users to install just for that user instead of global. 

I'll think this warning can be ignored, especially if the package is planned to be used from just the current user account. But to explore, a few things I'll try will be doing `sudo pip install rpa`, or doing `pip install rpa` from a user account instead of root (if root is being used), and lastly double-check that current user has sufficient write permissions in site-packages folder. The folder can be found by doing `import rpa as r; print(r.__file__)`.
