### ISSUE TITLE
Some questions about anti-crawling - some experiences and ideas to consider

### ISSUE THREAD

**Issue by VV-A-VV** [tebelorg/RPA-Python#267]
Hi,

I've used crawlers like selenium before, but it sometimes gets detected by the anti-crawl mechanism and pops up the captcha. But RPA doesn't seem to, and I'm confused because I've noticed that the underlying mechanism of RPA for python is very similar to selenium. Why is RPA effective in avoiding detection？

Also, I've noticed that RPA sometimes fails to request a web page (the network is fine) and has to interrupt the program and repeat the operation several times before it succeeds, does this mean that the site suspects that this is an RPA operation?

**Comment by kensoh** [comment]
Hi @VV-A-VV thank you for your feedback. Seleniums uses WebDriver which in turns uses DevTools Protocol to control the browser. In this situation, there will likely be additional header information that is embedded as part of the browser instance that websites can detect the Selenium's 'signature'.

RPA for Python is built on a fork of TagUI. For TagUI, I wrote the communications layer directly using DevTools Protocol, without using any middle-man tool. Also, I do not make changes to any header for browser session in order to simulate a real user browser as much as possible. Probably of these 2 factors, it is less likely to be detected as an automated browser.

Adding on, when you do web browser automation using computer vision only `r.init(visual_automation = True, chrome_browser = False)`, and opening and running Chrome etc using computer vision steps and keyboard step, this will further reduce the chance of being detected as automated browser.

This is because controlling Chrome from backend means automation tool needs to open a websocket connection from Chrome during initialisation. This could also be used by website as the clue that something is automated. Note that it is still possible to detect if the website monitor keyboard and mouse movements for human user behaviour. Robots move mouse and type on keyboard in a very clean and consistent way, not with a lot of 'noise' in movements and typing delay between keystrokes like humans.

---

If a webpage sometimes work and sometimes not work, and browsing it manually works, then it is likely due to bot detection and refusing to serve the webpage. You can try the computer vision method above to see if that helps. Or slowing down your actions on the webpage (adding some using time.sleep() between each record during batch automation). If doing manually also not work means maybe the website is detecting your IP as robot and trying to block you.

**Comment by VV-A-VV** [comment]
Thank you very much for your reply! It has helped me a lot.

**Comment by BeanHhb** [comment]
Hi all,
I meet an anti-crawling problem these few days and sinserely want your advice.(Althought this issues is closed)
The website(http://www.gsxt.gov.cn/),  the open government system i guess it is okay to show in here.
When i open it by tagui (ps. only this step is automate) and manually do some search base on the browser,  it turns to 404 page which the website provided.
How the website can detective it? If just like @kensoh says, the browser initialisation opens websocket connection that makes it be detectived?
I wonder if can open an manual browser and do rpa steps like url()，type()，click()? 
Thanks~

**Comment by BeanHhb** [comment]
Sorry to pardon you again,
continue my problem above.
It make me strange that the browser opened by tagui is without chrome account. So I login chrome acount in automatic browser and sync account info. After that, i try it again and the anti-crawling disappears. 
My problem is solved maybe, but im still confused about it.

**Comment by kensoh** [comment]
Hi @BeanHhb, for my laptop without a Chrome account, it seems to work. Yes there are many ways for website to detect if a user is automation robot or real user. There is no 1 simple way because every website is different, and it will also handle users from different countries differently (by recognising IP address range).

![Screenshot 2021-06-12 at 10 28 33 AM](https://user-images.githubusercontent.com/10379601/121762535-0b81e980-cb69-11eb-9c01-c6f753f81b9e.png)

In general, trying to do things which normal users will do will help to minimise detection, though it is up to users to decide if they wish to respect the website owner's wish to not serve automated users. Also, over time, robot-detection technology will improve and be able to detect if website owner really want to (eg through browser fingerprinting technologies and mouse/keyboard monitoring algorithms to classify user as human or robot).

But yes, by using keyboard(), click(), type() using images to control the browser you can minimise detection. For eg something like below (you need to capture image snapshots as needed for eg the search.png for the search bar).

```
r.init(visual_automation = True, chrome_browser = False)
r.keyboard('[start]')
r.keyboard('chrome[enter]')
r.wait(3)
r.keyboard('[ctrl]l')
r.keyboard('https://google.com[enter]')
r.type('search.png', 'testing 123[enter]')
```

**Comment by BeanHhb** [comment]
tks for your reply @kensoh,
I will try the example you provide.
