### ISSUE TITLE
how to control the new page popuped from the <a> in current page?

### ISSUE THREAD

**Issue by BeanHhb** [tebelorg/RPA-Python#271]
hi kensoh,
My problem is just like the description in title.
When I want to r.read() the element of new page, it comes error that no found element.
It may seems simple to you, right?
tks~

**Comment by BeanHhb** [comment]
I use r.url([<a>/@href]) rather than r.click() the <a> which open a new page.
It can help.
tks

**Comment by kensoh** [comment]
Hi @BeanHhb yes what you found is a solution, read the URL then use url() to visit the page and automate.

Another way is use the popup() function, that function lets user specify which tab to automate on. This is needed because there can be web elements that match in all open tabs. So popup() will specifically set which tab to automate.

https://github.com/tebelorg/RPA-Python#pro-functions
