### ISSUE TITLE
Can I deploy and run this rpa to capture screenshot of webpage on AWS server - yes

### ISSUE THREAD

**Issue by SaiAinala3** [tebelorg/RPA-Python#276]
I want to develop a tool to capture screenshots of web pages using Python when a URL is given. And I would like to deploy this in the AWS and run. So, it should run like a Flask app and should save screenshot images on that server without opening any browser.

Can we develop it if the server doesn't have any chrome or other browsers installed on it?

**Comment by fi-do** [comment]
Hey @SaiAinala3,

I really do not have any experiences with executing tagui on an aws server. But under normal circumstances you were able to execute tagui in an headless mode. An browser will be needed, but not opened with a gui.

Example:

```
import rpa as r
r.init(headless_mode=True)
r.url("www.google.de")
r.wait(1)
r.snap(element_identifier="page", filename_to_save="test.png")
r.close()

```

Hope it will help you,
fi-do

**Comment by kensoh** [comment]
Adding on to @fi-do's reply, it sounds like you meant that there is restriction on installing Chrome on your AWS server. If there is no restriction you can install Chrome and run headless. Here is a complete working example of running this on a Linux server - https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

If there is still an issue with this, you can edit tagui.py (in the folder `print(r.__file__)`) the following line and remove `+ browser_option`. By doing so, you will run in the built-in PhantomJS browser. However, it does not work very well because most websites are tested and designed to work with Chrome and not PhantomJS.

```
tagui_cmd = tagui_executable + ' rpa_python ' + browser_option
```
