### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'rpa_python' - pending some checks

### ISSUE THREAD

**Issue by shahzebutt** [tebelorg/RPA-Python#283]
I want to run tagui in docker container. I used Ubuntu:20.10 image. I installed all the dependadancies like PHP, OpenJDK etc.
when I do rpa.init(headless_mode=True). RPA search for .tagui folder in /home/username/.
Ususally the package is successfully downloaded but then gives an permission error. Permission denied: 'rpa_python'.

I also tried to copy then whole .tagui package in my docker image and also open all the permission by "chmod -R 777 /home/username/.tagui"   but still no success.

Btw its working fine on my local machine. Can anyone help me that what can be the issue?

**Comment by kensoh** [comment]
Hi @shahzebutt this is an interesting problem, I haven't heard this from users before.

Permission denied normally happens if a process does not have the write access, but this shouldn't happen if the Python process can create the file in the first place. Are you running as root user or normal user? Here are some ideas to explore -

1. Here's an Ubuntu setup on Google Colab, using root user and Chromium. Maybe you can compare to see why -
https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

2. Here's a Docker image containing RPA for Python, maybe you can get more clues why that works but not in your environment - https://hub.docker.com/r/openiap/nodered-tagui ([Dockerfile here](https://github.com/open-rpa/openflow/blob/master/OpenFlowNodeRED/Dockerfiletagui))

3. Try setting `r.debug(True)` before your `r.init()` to see if there are further clues on the error
