### ISSUE TITLE
No function works after application login pop-up is opened - pending some checks

### ISSUE THREAD

**Issue by FARBEX97** [tebelorg/RPA-Python#284]
My script works well until a desktop application icon is doble-clicked through r.dclick([application logo]).

The applicacion opens as expected, but any _r.function()_ used after the login pop-up appears seems like it is not working. It does not show any error or message, the script just ends like there is no more statements to execute.

When I've done it manually, I checked that double-clicking the application makes it active and any keyboard input gets typed in.

I've seen there is a similar issue #272 but doesn't solved my problem.

My script:
```
import rpa as r

r.init(visual_automation = True, chrome_browser = False)
r.dclick(PATH-TO-ICON)
r.wait(10)            # login pop-up usually appears at 3 seconds
r.click(960,560)
r.wait(2)
r.close()
```

**Comment by FARBEX97** [comment]
I have been trying different workarounds but nothing seems to work.

Starting this desktop application somehow prevents the next commands to execute, but when I close the application, the next commands are executed.

By far, I tried:
* Starting one thread that runs the program, and then starting other with the rpa commands, all by using the threading module in the Python standard library.
* Starting a bat file from the Python script that runs the desktop application in another command line.

No matter what I do to separate this two processes, when I open this application, the script waits until I manually use the mouse/keyboard.

**Comment by kensoh** [comment]
Hi @FARBEX97 this is an interesting scenario! I haven't come across a user who encounter this.

Can you try the following to gather more information why this could be happening?

1. Put a `r.debug(True)` before `r.init()` to try to capture all communications messages from the Python process to TagUI
2. Check `r.tagui_location()` folder, under it is tagui folder (Windows) or .tagui folder (macOS/Linux). Go into that folder and then under src/tagui.sikuli can you share the logs there what is happening there?
3. Can you insert a print('test') after your r.wait(10)? to see if execution reaches there or if it is the click that breaks it.
4. Can you tell me more about what OS you are using and what application is that?

It sounds like for some reason, that application is able to block either the Python or TagUI process from continuing, unless that application is closed. I can't imagine of a reason why that can happen that sounds quite surprising a different app can block Python or TagUI process, but hopefully with the above investigations we can find the root cause and solution.

**Comment by FARBEX97** [comment]
Hi @kensoh thank you for your awesome work.

Here are the results on the tests you suggested:

### 1. `r.debug(True)` before `r.init()`:
```
[RPA][0] - listening for inputs
[RPA][1] - exist_result = exist('PATH_TO_ICON.PNG').toString()
[RPA][1] - listening for inputs
[RPA][2] - dump exist_result to rpa_python.txt
[RPA][2] - listening for inputs
[RPA][3] - click (960,560)
[RPA][3] - listening for inputs
```

### 2. `src\tagui.sikuli` logs:

- `tagui.log` (same content as `tagui_windows.log`)

```
[tagui] START  - listening for inputs

[tagui] INPUT  - [1] present PATH_TO_ICON.PNG
[tagui] ACTION - present PATH_TO_ICON.PNG
[tagui] OUTPUT - [1] SUCCESS

[tagui] INPUT  - [2] dclick PATH_TO_ICON.PNG
[tagui] ACTION - dclick PATH_TO_ICON.PNG
[log] DOUBLE CLICK on L[47,403]@S(0) (1067 msec)
[tagui] OUTPUT - [2] SUCCESS

[tagui] INPUT  - [3] click (960,560)
[tagui] ACTION - click (960,560)
[error] RobotDesktop: checkMousePosition: should be L[960,560]@S(0)
but after move is L[47,403]@S(0)
Possible cause in case you did not touch the mouse while script was running:
 Mouse actions are blocked generally or by the frontmost application.
You might try to run the SikuliX stuff as admin.
[log] CLICK on L[960,560]@S(0) (557 msec)
[tagui] OUTPUT - [3] SUCCESS

[tagui] FINISH - stopped listening
IDE terminated: returned: 0

```
- `tagui_sikuli.txt` (this file is empty)
- `tagui_sikuli.in`
```
finish 
```
- `tagui_sikuli.out`
```
[0] FINISH
```
### 3. Insert a `print('test')` after `r.wait(10)`:
This is my CMD line output:
```
(venv) PATH_TO_SCRIPT> python main.py
test
```
### 4. OS and Application info:
- __OS:__ Windows 10 Enterprise.
- __Application:__ it is a custom developed desktop application by a big software company to my company so I can't be very specific about the details.
  - When the login pop-up is on screen there is no icon in the task bar, but it do appears in the Windows task manager.
  - The login pop-up consists on a little window with two textboxes (user and password) and three buttons (Accept, Cancel, Help).
  - I know that some people have automated some tasks in it using the Win32 API, is this a hint?
  - `python-rpa` works well for me when using it to automate other desktop applications, only happens with this one.
  - When the Application icon is double-clicked manually, the login pop-up is active and if I press any key, it appears in the automatically active user textbox (the intermittent bar is on user), __but__ when I try to do it with any automation, the bar stops blinking and keeps like this: `I` (no-blinking bar). I noticed that  It also ocurres when I run it using `os.system('PATH_TO_APP.EXE')`.

I hope this helps to solve my problem. Could be something related to my Python version? I am using Python3 64 bits, maybe has to do with that.

Thanks a lot for your help.

**Comment by kensoh** [comment]
Hi @FARBEX97 thanks for sharing the detailed findings!

1 and 2 looks ok and acceptable logs for normal operations.

3 is suggesting that the double-clicking didn't hang at that point.

Your findings for 4 are interesting. Works for other desktop apps but not this one. And when ran using automation or os.system() the blinking cursor stops blinking. This seems to suggest some conflict with the app and automation (either Python or Java or TagUI). Whether this conflict is intentional (anti-automation technology built into that app) or is some technical conflict is not clear at this point.

As a next step, can you try out if running TagUI the human language version, the same problem happens?

Syntax is the same as this package except in human language (20+ human languages supported) -
https://github.com/kelaberetiv/TagUI#language-designed-for-rpa

Here is the download link for the human language version -
https://tagui.readthedocs.io/en/latest/setup.html

If the same thing still, happens, then we know the problem is not conflict with Python, but maybe Java (used for the low-level keyboard and mouse control). If issue is with Java, there are 2 other ways I can think of to explore -

1. Try running this automation through Teamviewer for example, so that you automate on the remote desktop screen. This way, there won't be Java automation running on the target PC but actually is running on the automation PC using computer vision on the Teamviewer session.

2. Since if running TagUI human language version also has a problem, see if you can join a weekly Zoom Q&A call I run for TagUI users to ask questions and troubleshoot technical issues. It is every Thursday 10-11am your time in Madrid - https://tagui.readthedocs.io/en/latest/setup.html

**Comment by FARBEX97** [comment]
Hi again @kensoh 

I've been trying [TagUI](https://github.com/kelaberetiv/TagUI ) the human language version and the problem persists. It happens the same way so probably it is not a Python problem.

Unfortunately, the company policy where I work doesn't allow me to do the Teamviewer/remote connection test, so maybe we are too much constrained to have a solution here.

At least we know that it is not a Python issue, more likely an over-protected system issue.

I don't know if this is a dead end. If you have any suggestions that doesn't involve remote connection I will try them and report here.

Anyway, thanks again for your work!

**Comment by kensoh** [comment]
Hi @FARBEX97 thanks for your additional inputs! I see, following are some next possible options to explore -

1. if your company can use [Chrome Remote Desktop](https://remotedesktop.google.com/home), then maybe during the [weekly Zoom call](https://github.com/kelaberetiv/TagUI/issues/914) we can use that to do the troubleshooting.

2. Explore if your scenario is ok for user to login manually first before doing the rest of the automation steps? If you can do something like below to let the login be done manually -
```
r.timeout(300)
r.hover('image_to_look_out_for_confirmation_that_user_has_logged_in.png')
```

3. Consider other automation tools like https://www.autohotkey.com or Microsoft Power Automate Desktop, and use those tools to handle the login sequence, before calling RPA for Python to handle the rest. It is trivially easy for those tools to chain together with this package because they can easily run command line commands ie Python to run your RPA script.

**Comment by FARBEX97** [comment]
Hi @kensoh thanks again for your time on this issue!

### 1. Remote desktop test
Finally I achieved to do the remote desktop test. It worked! It is not the ideal because it needs two computers for a low-value task, but it is good for the sake of the experiment.

### 2-3. Login manually test
I also tested if I could automate tasks once into the app, but this is not the case. The script runs and ends like everything is OK but there is no mouse or keyboard move/stroke, so doesn't matter what automation tool to use for the login, there is some block for Python when this app is running.
***
Is there any other test I could try? Seems like I will have to learn to automate it through the Win32 API.

Maybe a future feature of this package? Idk seems like a lot of work for a very specific case.

**Comment by kensoh** [comment]
Hi @FARBEX97 I see.. From your observations, it looks like that application is either intentionally or by accident blocking either the Python process or the RPA for Python --> TagUI --> SikuliX --> Java process on controlling keyboard and mouse.

In this case, you can -

1. Try using Python Win32 API https://pbpython.com/windows-com.html

2. Or perhaps more easily PyWinAuto https://github.com/pywinauto/pywinauto

RPA for Python will probably not add into API the ability to control Windows apps from Win32, because that feature won't be cross-platform, requires additional dependency, and can already be done by other Python packages like PyWinAuto. 

Another idea I thought of (though troublesome to setup), is you can spin up a Linux image and run on your Windows computer. Then from that Linux use Chrome Remote Desktop to automate controlling your laptop. This way may be able to work using 1 physical computer. But Linux has manual setup steps needed for visual automation to work - 

https://sikulix-2014.readthedocs.io/en/latest/newslinux.html

**Comment by FARBEX97** [comment]
Hi @kensoh 

Anyway thank you for your time, its awesome that people make open projects like this.

I will go for the PyWinAuto path and see what happens.
