### ISSUE TITLE
r.init() return false - network blocking access to download files from github.com

### ISSUE THREAD

**Issue by mawenian** [tebelorg/RPA-Python#290]
I install rpa with:
pip install rpa
then:
pip install -U rpa
but:
import rpa as r
r,init()
return:
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - C:\Users\ASUS\AppData\Roaming
[RPA][ERROR] - failed downloading from https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Windows.zip...
[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
False

**Comment by kensoh** [comment]
Hi @mawenian this is because from your computer network Python can't access the GitHub URL above.

Some ways to explore to solve this -
1. try installing not on your company laptop or intranet
2. try some VPN service which will let you access github.com website
3. try installing on a personal computer which works, then use r.pack() to create a zip and .py file which you can copy to your restricted network laptop to run without internet access

If you have more clues on your company network, let me know.

**Comment by mawenian** [comment]
I am connected to the internet and I can download the file (TagUI_windows.zip). Unzipped to the location but getting same error.

**Comment by kensoh** [comment]
I see, unzipping the files there is insufficient. Can you try using r.pack() from another laptop which works?

This download() function used is using standard Python libraries below, if there is a message saying no response and timeout, then this package won't be able to access those files on GitHub to download and use them. Do you mean clicking on the link https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Windows.zip from your web browser works but not from the package? Is there any special proxy or VPN used in your browser to enable the downloading?

```py
if _python2_env():
    import urllib; urllib.urlretrieve(download_url, filename_to_save)
else:
    import urllib.request; urllib.request.urlretrieve(download_url, filename_to_save)
```

**Comment by shawnaugust** [comment]
1、i want to konw  why always to download the older version     (tagui_zip_url = 'https://github.com/tebelorg/Tump/releases/download/v1.0.0/' + tagui_zip_file)  even i have installed the latest version  (https://github.com/kelaberetiv/TagUI/releases/download/v6.46.0/TagUI_Windows.zip)
2、and then if i have v1.0.0 installed (by the tagui.py ),when i restart the script(sample.py) again,then need to download again......

**Comment by shawnaugust** [comment]
now i comment this section( copy the latest versoin to dest): 
     #   tagui_zip_url = 'https://github.com/tebelorg/Tump/releases/download/v1.0.0/' + tagui_zip_file 
     #   if not download(tagui_zip_url, home_directory + '/' + tagui_zip_file):
     #       # error message is shown by download(), no need for message here 
     #       return False
     #
     #   # unzip downloaded zip file to user home folder
and this section:
  #  for delta_file in delta_list:
  #      tagui_delta_url = 'https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/' + delta_file
  #      tagui_delta_file = 'rpa_update' + '/' + delta_file
  #      if not download(tagui_delta_url, tagui_delta_file): return False

then  i get this error message:

It leads to following output when starting TagUI -
ERROR - use .tag extension for flow filename
ERROR - automation aborted due to above 

need help ,thanks a lot

**Comment by shawnaugust** [comment]
but when i   use command :tagui live,it is ok
cmd command:where tagui shows the same user home dirctory

**Comment by shawnaugust** [comment]
i get this error message:
'C:\Users\admin\AppData\Roaming/tagui/src/end_processes' 不是内部或外部命令，也不是可运行的程序 

could you do me a favor  to upload  those file to this place? i cannot acess this website .thanks a lot  
 https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/
```
    # define list of key tagui files to be downloaded and synced locally
    delta_list = ['tagui', 'tagui.cmd', 'end_processes', 'end_processes.cmd', 
                    'tagui_header.js', 'tagui_parse.php', 'tagui.sikuli/tagui.py']

    for delta_file in delta_list:
        tagui_delta_url = 'https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/' + delta_file
        tagui_delta_file = base_directory + '/' + 'src' + '/' + delta_file
        if not download(tagui_delta_url, tagui_delta_file): return False
```

**Comment by kensoh** [comment]
Hi Shawn, the file is already comes with TagUI zip file. After unzipping it will already be there. Can you check your folder C:\Users\admin\AppData\Roaming\tagui\src to see if there is an end_processes.cmd file there?

If the file is there, try running below in Python to see more info what happens -
```
import os; os.system('"C:\Users\admin\AppData\Roaming/tagui/src/end_processes"')
```
