### ISSUE TITLE
Errors while trying to read image png file - pending checks and more details

### ISSUE THREAD

**Issue by fshabashev** [tebelorg/RPA-Python#294]
I'm trying automate clicking on particular visual element.
But getting a weird error:

```
> os.listdir(".")

['Untitled.ipynb',
 'rpa_python.log',
 'icon_to_click_on.png',
 '.ipynb_checkpoints']
 ```
 
 ```
> r.click('icon_to_click_on.png')

[RPA][ERROR] - cannot find icon_to_click_on.png
```

```
> rpa.__version__
'1.44.1'
```

```
> import platform
> platform.platform()

'Darwin-20.3.0-x86_64-i386-64bit'

```

**Comment by kensoh** [comment]
Hi Fedor, 

If your mac is using retina HD display, try running this once, before your do r.click(). To see if that helps. Mac Retina machines when you take screenshots, the images will be at 2X resolution of actual display.

This step below downsize your image to the real display resolution before finding a match. 

```
r.vision('Settings.AlwaysResize = 0.5')
```
More details - https://github.com/tebelorg/RPA-Python/issues/170#issuecomment-843168745

Also, I assume you are using a single display, because visual automation only works on your primary display, I believe the one with the macOS docking bar. For automating secondary displays, need to send custom SikuliX code - https://github.com/tebelorg/RPA-Python/issues/252#issuecomment-844277454
