### ISSUE TITLE
During r.init(), [RPA][ERROR] - Unable to open file: F:\TagUI_RPA\RPA - pending checks

### ISSUE THREAD

**Issue by wuhao5925968** [tebelorg/RPA-Python#301]
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"D:\TagUI_Windows/tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
Unable to open file: F:\TagUI_RPA\RPA

  phantomjs://code/bootstrap.js:113 in __die
Unable to load script F:\TagUI_RPA\RPA; check file syntax

  phantomjs://code/bootstrap.js:113 in __die

[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using read()

[RPA][ERROR] - use init() before using snap()
[RPA][ERROR] - use init() before using close()

**Comment by kensoh** [comment]
Hi Wu Hao, thanks for reporting this issue!

It seems like for some reason a file can't be opened. Can you try the following -

1. pip install rpa to get the latest version that works with folders having spaces
2. check that you really have a F:\TagUI_RPA\RPA folder and a rpa_python file there
3. try running below command at F:\TagUI_RPA\RPA folder -
`"D:\TagUI_Windows/tagui/src/tagui" rpa_python chrome`

From there we can see what are the next steps to troubleshoot. My guess base on above is maybe your package version is not the latest which has a fix for folder names with spaces.

**Comment by Lamarche-Lam** [comment]
Hello there, I encounter with similar the similar error as following when I try to initiate the rpa package:

RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"D:\TagUI_Windows/tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
Unable to open file: F:\TagUI_RPA\RPA

phantomjs://code/bootstrap.js:113 in __die
Unable to load script F:\TagUI_RPA\RPA; check file syntax

phantomjs://code/bootstrap.js:113 in __die

However, [RAP][ERROR] didn't show in my case.

I wonder whether it is because of no Java environment installed on the computer?

**Comment by Lamarche-Lam** [comment]
> Hi Wu Hao, thanks for reporting this issue!
> 
> It seems like for some reason a file can't be opened. Can you try the following -
> 
> 1. pip install rpa to get the latest version that works with folders having spaces
> 2. check that you really have a F:\TagUI_RPA\RPA folder and a rpa_python file there
> 3. try running below command at F:\TagUI_RPA\RPA folder -
>    `"D:\TagUI_Windows/tagui/src/tagui" rpa_python chrome`
> 
> From there we can see what are the next steps to troubleshoot. My guess base on above is maybe your package version is not the latest which has a fix for folder names with spaces.

I have tried your suggestion but it is still negative. Here is what happened during the trials:
1. I run `"D:\TagUI_Windows/tagui/src/tagui" rpa_python chrome` at the project folder like you suggested in CMD
2. It prompted a dialog window saying the MSVCR110.dll is missing
3. I copied MSVCR110.dll from \System32 to \ SysWOW64 and it worked... sort of
4. I ended up with 0xc000007b error

**Comment by kensoh** [comment]
Oh if MSVCR110.dll is missing or not installed properly, the package will first attempt to auto-install. If it fails, it will show below message to prompt user to install manually. Can you try below link to install and see if that helps?

```
[RPA][INFO] - now installing missing Visual C++ Redistributable dependency
[RPA][INFO] - MSVCR110.dll is still missing, install vcredist_x86.exe from
[RPA][INFO] - the vcredist_x86.exe file in ' + home_directory + '\\tagui or from
[RPA][INFO] - https://www.microsoft.com/en-us/download/details.aspx?id=30679
[RPA][INFO] - after that, TagUI ready for use in your Python environment
```

After installing using above link, try again and share with me the complete error message and when it happens.

**Comment by Lamarche-Lam** [comment]
> Oh if MSVCR110.dll is missing or not installed properly, the package will first attempt to auto-install. If it fails, it will show below message to prompt user to install manually. Can you try below link to install and see if that helps?
> 
> ```
> [RPA][INFO] - now installing missing Visual C++ Redistributable dependency
> [RPA][INFO] - MSVCR110.dll is still missing, install vcredist_x86.exe from
> [RPA][INFO] - the vcredist_x86.exe file in ' + home_directory + '\\tagui or from
> [RPA][INFO] - https://www.microsoft.com/en-us/download/details.aspx?id=30679
> [RPA][INFO] - after that, TagUI ready for use in your Python environment
> ```
> 
> After installing using above link, try again and share with me the complete error message and when it happens.

Thank you for your response. I didn't response on time because of the weak internet. 

I did the following things after my reply this morning: 
1. Deleted all the files related to tag_ui including the rpa modules in site-package file and the 'tag_UI' file unzipped from the windows zip installer.
2. I removed the MSVCR110.dll from Windows\SysWOW64 file and uninstalled visual c++ 2010 x86 redistributable
3. I then reinstall rpa package usiing pip install and run r.init() in the console. It finished the line '[RPA][INFO] - after that, TagUI ready for use in your Python environment' but it terminated again when the 'tagui' rpa_python chrome is executed.
> [RPA][ERROR]  -  following happens when starting TagUI...
>
> The following comand is executed to start TagUI -
>"C:\Users\xxx\AppData\Roaming\tagui/src/tagui" rpa_python chrome
> 
>It leads to following output when starting TagUI -
>Unable to load script D:\coding\RPA\rpa_python.js; check file syntax
>
>    phantomjs://code/bootstrap.js:113 in __die

4. Then I install visual c++ 2010 x64 redistributable and run the code (in Pycharm Console) again but the aforementioned error still persisted. 
5. I tried CMD with administrator authorisation as well and the MSVCR110.dll missing message prompted again for php.exe whether I copy the MSVCR110.dll  to \ SysWOW64 or not. ('0xc000007b error dismissed this time)

I check the rpa_python.js in D:\coding\RPA and find its size at 0 byte, which is highly suspicious.

Weirdly, I can use this package on my Mac without any problems...

**Comment by Lamarche-Lam** [comment]
> Oh if MSVCR110.dll is missing or not installed properly, the package will first attempt to auto-install. If it fails, it will show below message to prompt user to install manually. Can you try below link to install and see if that helps?
> 
> ```
> [RPA][INFO] - now installing missing Visual C++ Redistributable dependency
> [RPA][INFO] - MSVCR110.dll is still missing, install vcredist_x86.exe from
> [RPA][INFO] - the vcredist_x86.exe file in ' + home_directory + '\\tagui or from
> [RPA][INFO] - https://www.microsoft.com/en-us/download/details.aspx?id=30679
> [RPA][INFO] - after that, TagUI ready for use in your Python environment
> ```
> 
> After installing using above link, try again and share with me the complete error message and when it happens.

Thank you for your response. I didn't response on time because of the weak internet. 

I did the following things after my reply this morning: 
1. Deleted all the files related to tag_ui including the rpa modules in site-package file and the 'tag_UI' file unzipped from the windows zip installer.
2. I removed the MSVCR110.dll from Windows\SysWOW64 file and uninstalled visual c++ 2010 x86 redistributable
3. I then reinstall rpa package usiing pip install and run r.init() in the console. It finished the line '[RPA][INFO] - after that, TagUI ready for use in your Python environment' but it terminated again when the 'tagui' rpa_python chrome is executed.
> [RPA][ERROR]  -  following happens when starting TagUI...
>
> The following comand is executed to start TagUI -
>"C:\Users\xxx\AppData\Roaming\tagui/src/tagui" rpa_python chrome
> 
>It leads to following output when starting TagUI -
>Unable to load script D:\coding\RPA\rpa_python.js; check file syntax
>
>    phantomjs://code/bootstrap.js:113 in __die

4. Then I install visual c++ 2010 x64 redistributable and run the code (in Pycharm Console) again but the aforementioned error still persisted. 
5. I tried CMD with administrator authorisation as well and the MSVCR110.dll missing message prompted again for php.exe whether I copy the MSVCR110.dll  to \ SysWOW64 or not. ('0xc000007b error dismissed this time)

I check the rpa_python.js in D:\coding\RPA and find its size at 0 byte, which is highly suspicious.

Weirdly, I can use this package on my Mac without any problems...

**Comment by kensoh** [comment]
Hi @Lamarche-Lam from googling `php 0xc000007b error` it looks like for your Windows system it is missing some DLL which is commonly available on other Windows. You can try this -

1. type print(r.tagui_location()) to see where TagUI is installed
2. from above folder look inside tagui\src folder
3. rename the php folder to php5
4. try unzipping this PHP from here - https://windows.php.net/downloads/releases/php-7.4.24-Win32-vc15-x64.zip
5. and save the folder as php
6. from command prompt go to the php folder and type `php -v` for any errors
7. after that try the package to see if it works now

**Comment by Lamarche-Lam** [comment]
> Hi @Lamarche-Lam from googling `php 0xc000007b error` it looks like for your Windows system it is missing some DLL which is commonly available on other Windows. You can try this -
> 
> 1. type print(r.tagui_location()) to see where TagUI is installed
> 2. from above folder look inside tagui\src folder
> 3. rename the php folder to php5
> 4. try unzipping this PHP from here - https://windows.php.net/downloads/releases/php-7.4.24-Win32-vc15-x64.zip
> 5. and save the folder as php
> 6. from command prompt go to the php folder and type `php -v` for any errors
> 7. after that try the package to see if it works now

Hi  @kensoh,
Good News! I found a way out of this but not in the way you mentioned above.
The missing DLL files gave me some clues: Yes, it did relate to the visual c++ redistributable things and setup() function did try to fix it by installing the visual c++ redistributable things for the user. However, it installed the 2010 version instead of the 2012 version which is used by "TagUI Windows Installer" you created in another project. 
I had the 2012  visual c++ redistributable installed and the code worked fine.

Except.. the r.init() invoked x86 chrome instead of x64 chrome somehow so it seemed to not work for the 64-bit chrome?

**Comment by kensoh** [comment]
It's strange that different versions are installed because both are using the same vcredist_x86.exe installation file. Maybe some environment complications, but no point finding out more. I'll see if more users experience the same problem.

The default used by TagUI is `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`. You can edit the file tagui\src\tagui.cmd to change it to the Chrome you want to run. However, on next update I think your change will revert.

Can you share more why you are having 2 versions of Chrome on the computer? You can also try deleting the x86 version and TagUI should use the x64 one, if it is found at `C:\Program Files\Google\Chrome\Application\chrome.exe` or `%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe`

**Comment by Lamarche-Lam** [comment]
> It's strange that different versions are installed because both are using the same vcredist_x86.exe installation file. Maybe some environment complications, but no point finding out more. I'll see if more users experience the same problem.
> 
> The default used by TagUI is `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`. You can edit the file tagui\src\tagui.cmd to change it to the Chrome you want to run. However, on next update I think your change will revert.
> 
> Can you share more why you are having 2 versions of Chrome on the computer? You can also try deleting the x86 version and TagUI should use the x64 one, if it is found at `C:\Program Files\Google\Chrome\Application\chrome.exe` or `%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe`

I didn't have both version of chrome installed on my computer but r.init() went diretly to the C:\Program Files (x86)\Google\Chrome\Application\chrome.exe somehow... Thus, i assumed it used the 32-bit chrome only yesterday.

**Comment by Lamarche-Lam** [comment]
> It's strange that different versions are installed because both are using the same vcredist_x86.exe installation file. Maybe some environment complications, but no point finding out more. I'll see if more users experience the same problem.
> 
> The default used by TagUI is `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`. You can edit the file tagui\src\tagui.cmd to change it to the Chrome you want to run. However, on next update I think your change will revert.
> 
> Can you share more why you are having 2 versions of Chrome on the computer? You can also try deleting the x86 version and TagUI should use the x64 one, if it is found at `C:\Program Files\Google\Chrome\Application\chrome.exe` or `%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe`

It tested it on my home computer, both error resulted from  different version of visual c++ redistributable and 32-bit chrome disappeared...

I think you're right, enviormnent complications should be the case.  The error was found on my company computer..


Thank you some much.

**Comment by kensoh** [comment]
I see.. You're welcome! Let me know any error messages or blockers you have when running. To get rid of the Visual C++ errors just need a working PHP installation at the tagui\src\php folder. If the one that comes with the package somehow does not work, see if you can unzip the one from above link I give for PHP to see if that works.

**Comment by Lamarche-Lam** [comment]
> I see.. You're welcome! Let me know any error messages or blockers you have when running. To get rid of the Visual C++ errors just need a working PHP installation at the tagui\src\php folder. If the one that comes with the package somehow does not work, see if you can unzip the one from above link I give for PHP to see if that works.

Okay, thx again
