### ISSUE TITLE
init() not completing in scheduled task, might be Chrome changes - pending details

### ISSUE THREAD

**Issue by Timonsies** [tebelorg/RPA-Python#309]
I have a setup on a Windows server where everything works fine as long as I run the process while being logged on and can see the processes run. However when I schedule the task to be ran 'whether the user is logged on or not' it fails. In this case Windows will start processes without them being visible for the current user. 
I see chrome being started and also the php process starts, however the INPUT - [2] {"id":2,"method":"Page.navigate","params":{"url":"about:blank"}}
Never receives an OUTPUT

This setup used to work till about a month ago, not sure what happened to cause this to fail, any ideas?

**Comment by kensoh** [comment]
Hi @Timonsies thanks for raising this! From your datapoints, it sounds like there might be some change in Chrome's behaviour to no longer support such scenario. Because Chrome didn't respond back to TagUI's instruction above.

One way to validate is try running a simple script below. It ask the TagUI engine to save a file, then loads it back from Python process. If this process can run, it suggests that somehow Chrome does not work well with your scenario now.

```
import rpa as r
r.init(chrome_browser = False)
r.send('dump 123 to abc.txt')
print(r.load('abc.txt'))
r.close()
```

If that's the case, some options to explore could be -
1. try `r.init(headless_mode = True)` to see if Chrome headless is still supporting such use case
2. try environmental setup changes like let user account be logged on before running

**Comment by Timonsies** [comment]
@kensoh Thanks for your quick response, running Chrome in headless mode has solved the issue.
