### ISSUE TITLE
close() with option to close TagUI and SikuliX but not Chrome - ideas to explore

### ISSUE THREAD

**Issue by LankaWithanage** [tebelorg/RPA-Python#315]
Any parameters for the close() core function to close TagUI & SikuliX but keep the opened chrome browser ?

**Comment by kensoh** [comment]
I'm afraid not because the code to close all the TagUI processes including Chrome is embedded quite deeply in upstream TagUI engine. Would doing a long r.wait() or an Python input() to wait for user to confirm to continue before closing help?

```
# wait 1 hour
r.wait(3600)
```

```
input('Press Enter key to continue.. ')
r.close()
```

Adding on, let me know more about your usage scenario why this is needed, I'll see if there's any other workarounds.

**Comment by kensoh** [comment]
Oh I see.. Your scenario does not seem to require SikuliX. In that case, you can try doing your automation but just don't include r.close() at the end. The memory and CPU overhead for TagUI should be considered relatively very low.

And the next time you run automation again with r.init(), it will automatically do the clean-up of dead processes before start.

**Comment by kensoh** [comment]
And if you are really interested for a foolproof solution and willing to hack, then you can do the following -

1. print(r.tagui_location())
2. look for a tagui or .tagui folder (depends on your OS)
3. look for src\end_processes (mac/linux) or end_processes.cmd (win)
4. delete the section involving chrome_process_id
5. in your script don't use r.close()
6. but instead do os.system('full path to the end_processes')

Above hack should kill everything except the Chrome browser.
