### ISSUE TITLE
How to change context with popup if string_url is the same - an idea to try

### ISSUE THREAD

**Issue by bgonzalezfractal** [tebelorg/RPA-Python#317]
Hi Kensoh,
I'm having a bit of a problem with a website (.asp), the thing is that is has an authentication login, and then a popup window opens up the information page, the problem is that I can't change the context since the pop url and the login page have exactly the same url.

- First login url: https://www.globalecbusiness.com/elogin.asp (we use r.type and rclick, we have no problem authenticating)
- Pop up page with information url: https://www.globalecbusiness.com/elogin.asp

In this case rpopup doesnt work and when I try to snap the page, the jupyter notebook freezes. If I remove the pop up function then rsnap shows I'm still located in the login tab (pop up is is second tab)

I know it can be resolved with visual automation, but since we are building Docker images in a Linux Debian Environment I don't want to depend on these feature.

Code that freezes:
`r.init(chrome_browser = True, headless_mode=True)`
`r.debug(True)`
`r.url('https://www.globalecbusiness.com/elogin.asp')`
`r.type('//input[@name="Login"]', 'USER')`
`r.type('//input[@name="Clave"]', 'PASSWORD')`
`r.click('//img[@name="Image9"]')`
`r.popup('elogin.asp')`
`r.snap('page','testingpopup.jpg')`

Code that runs but stays in the same context
`r.init(chrome_browser = True, headless_mode=True)`
`r.debug(True)`
`r.url('https://www.globalecbusiness.com/elogin.asp')`
`r.type('//input[@name="Login"]', 'USER')`
`r.type('//input[@name="Clave"]', 'PASSWORD')`
`r.click('//img[@name="Image9"]')`
`r.snap('page','testingpopup.jpg')`

Does anynoe knows how to handle these type of problem?

**Comment by kensoh** [comment]
Hi @bgonzalezfractal I haven't come across this scenario before. And indeed, if the popup tab is having the exact same URL as the parent one, then the tool can't tell Chrome which one to attach the context to.

And because you are not using computer vision and keyboard automation, it is also not possible to close the parent tab in order to make the child tab 'selectable'.

One possibility is you can try modifying the package source code in tagui.py to add some new option to handle this unique scenario. I was trying to explore this but it looks like the current code already selects the latest tab with the URL matched (unless Chrome doesn't order them chronologically).

Can you try running the scenario that hangs and attach the tagui_chrome.log file here? The file can be found this way -

print(r.tagui_location()) --> check for a tagui or .tagui folder --> go to src subfolder

**Comment by kensoh** [comment]
Hmmm, this looks like for some unknown reason, Chrome in the popup tab somehow doesn't return back data to Python.

Is there any way to access that popup tab directly? This scenario is really tricky, especially when OS-level screenshot is not preferred due to running headlessly on Docker.

**Comment by bgonzalezfractal** [comment]
It's actually accessing the pop up right away, once I log in the Chrome UI is viewing the second tab but the problem is the context is still in the login page (first tab), that's why I thought a simple r.popup() would work but its no the case.

I think the easiest way is to use a Windows Server Machine and use visual automation with Docker, I was trying to avoid this method but I was looking at the source code and its not clear why Chrome UI is taking the first tab instead of the second.

The "solution" in visual automation was:
```
r.keyboard('[ctrl][tab]')
r.keyboard('[ctrl][tab]')
r.keyboard('[enter]')
```
Once I use this, the context is still in the first tab, but since the Chrome UI is viewing the second tab, the code is able to click the button using enter and go to the next page.

I think its actually possible to set the context but I would have to try a few things editing the source code, if I find the time I'm gonna be trying a few things and getting back to you incase this helps others.
For now, thx for the help and for creating an amazing RPA open source.

**Comment by kensoh** [comment]
Hi @bgonzalezfractal, thanks for sharing your solution!

I just thought of an idea which can be explored. This is the only idea I have that doesn't require visual automation or hacking the source code of TagUI engine with some JS code to select tabs in other ways.

If the URL for the initial tab and the new tab is the same, and the context is stuck at the original tab, maybe you can do a `r.url('some dummy url')` so that the original tab navigates away.

After that, use `r.popup('text in url of new tab')` to set the context to the new tab.

After all actions are done, use `r.popup('text in some dummy url')` to set context back to the original tab, and perhaps use `r.dom('window.history.back()')` to revert the original tab to the right state.

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem!

**Comment by bgonzalezfractal** [comment]
Confirmed, it's not even necessary to use r.dom(), it's enough with the popup() function.

**Comment by kensoh** [comment]
Thanks @bgonzalezfractal for sharing back here! This is helpful for other users with similar scenarios.
