### ISSUE TITLE
About flow control and error handling

### ISSUE THREAD

**Issue by Alpha-Girl** [tebelorg/RPA-Python#326]
😉Hi, I have been working with RPA-Python ( or  TagUI for Python ) for about two weeks. I used it to back PLC ( Programmable Logic Controller ) program up every day ( or every hour ). TagUI performed well. 

**However, when it comes to error( like timeout, connection error, and so on), TagUI keeps working and results in some unexpected problems.**

**Therefore, I hope to share ideas on these topics, flow control and error handling, with anyone interests in it.**

Methods mentioned below is what I have tried to deal with it.

## Timeout 
as mentioned in [stackoverflow](https://stackoverflow.com/questions/492519/timeout-on-a-function-call)
```Python
from __future__ import print_function
import sys
import threading
from time import sleep
try:
    import thread
except ImportError:
    import _thread as thread

def quit_function(fn_name):
    # print to stderr, unbuffered in Python 2.
    print('{0} took too long'.format(fn_name), file=sys.stderr)
    sys.stderr.flush() # Python 3 stderr is likely buffered.
    thread.interrupt_main() # raises KeyboardInterrupt

def exit_after(s):
    '''
    use as decorator to exit process if 
    function takes longer than s seconds
    '''
    def outer(fn):
        def inner(*args, **kwargs):
            timer = threading.Timer(s, quit_function, args=[fn.__name__])
            timer.start()
            try:
                result = fn(*args, **kwargs)
            finally:
                timer.cancel()
            return result
        return inner
    return outer
```
above define an exit_after decorator. It generate a KeyboardInterrupt .then
```Python
try:
    what_rpa_do()
except KeyboardInterrupt:
    deal_with_timeout()
```
## unexpected error
Until now, I don't have a good idea to deal with it. I just do a step and check some item to ensure the flow works as expected.
```Python
step1()
if is_error_after_step1():
    error_handling() # take a screenshot, record time and something important in log.txt, close windows
    restart_program() # try 3 times
step2()
``` 
Obviously, it's not a good idea. Hope you share some example or idea to deal with these problems.

**Comment by kensoh** [comment]
Hi @Alpha-Girl thanks for raising this and your generous sharing! Yes I agree that the error handling should be improved.

There is an open issue here on this topic, I'll try to explore more when I get some time - https://github.com/tebelorg/RPA-Python/issues/299

In the meantime, by default each step has a timeout of 10 seconds. If the step fails, it will return False. If it works, True. One way to handle error is to explicitly check for errors on the steps which you believe can have chance of failing -

```
if not r.click():
    # do something on failure

if r.click():
    # do something on success
```

Above works but is too troublesome to do for every line, so it can only be done on selected lines. In the #299, I hope to find a better way so that users can use try-except code blocks to perform exception handling.

**Comment by kensoh** [comment]
Closing this issue but leaving #299 open

**Comment by kensoh** [comment]
Adding on, please let me know if you have found better solutions since few months ago!
