### ISSUE TITLE
RPA Python not working in MacOS Monterey - PHP removed, install PHP this way

### ISSUE THREAD

**Issue by 684efs3** [tebelorg/RPA-Python#335]
I just upgraded to MacOS Monterey and my previous RPA Python code no longer works. I am using RPA to open a website  and now I get this:

I am using a Jupyter notebook.

```
import rpa as r

r.init(visual_automation = True)
r.url('https://www.yahoo.com')
r.close()

[RPA][ERROR] - following happens when starting TagUI...


[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using close()
False
```

**Comment by kensoh** [comment]
Hi @684efs3, thanks for reporting this!

I'm seeing early reports of this issue due to the new Mac version removing PHP - https://www.techgenyz.com/2021/06/18/macos-12-monterey-update-built-in-php/

Solution for now is to install PHP manually, until this can be automated (I don't think so, need password to run homebrew) or co-packaged. Below will install Homebrew package manager, then install PHP which is required to run the rpa package.

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install php
```

Try the above to see if that works. I'm using Mac as well but am still keeping it at Catalina version so I can't replicate.

**Comment by 684efs3** [comment]
Fixed - thank you very much!

**Comment by kensoh** [comment]
Adding a note that upstream TagUI has a [fix for newer PHP (eg v8.1.1)](https://github.com/kelaberetiv/TagUI/issues/1137#issuecomment-1016101430) which has some problem with the code used to process datatables and object repositories. However, this is not needed here because for the Python package, those blocks of code are never executed (no concept of datatables or object repositories here).

**Comment by HollandWeng** [comment]
what i should do with the   @kensoh 
first ，i have donwload php this is th version

(Machine_Learning) @MacBook-Pro ~ % php -v
PHP 8.4.1 (cli) (built: Nov 20 2024 09:48:35) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.1, Copyright (c), by Zend Technologies
    
 scond，i download java and amazon corretto
 then i run my code;
 
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"/Users//.tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
/Users//.tagui/src/tagui: line 256: php: command not found
Unable to open file: /Users/hollandweng/Documents/PythonCode/RPA/rpa_python.js

  phantomjs://code/bootstrap.js:113 in __die
Unable to load script /Users//Documents/PythonCode/RPA/rpa_python.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die

[RPA][ERROR] - unknown error encountered
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"/Users//.tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
/Users/hollandweng/.tagui/src/tagui: line 256: php: command not found
Unable to open file: /Users//Documents/PythonCode/RPA/rpa_python.js

  phantomjs://code/bootstrap.js:113 in __die
Unable to load script /Users//Documents/PythonCode/RPA/rpa_python.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die

[RPA][ERROR] - unknown error encountered
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using present()

**Comment by kensoh** [comment]
Hi @HollandWeng I've not come across this situation. The error message says php conmand is not found but you have installed it. Can you try going to the .tagui/src folder and type php to see if the command can be accessed there?

**Comment by HollandWeng** [comment]
@kensoh Thanks for you reply. I open the

**Comment by HollandWeng** [comment]
@kensoh Thanks for your reply, I open .tagui/src and search for php, get the following result. 
BadOpcodeException.php
BadUriException.php
Base.php
Client.php
ConnectionException.php
Exception.php
sleep.php
tagui_chrome.php
tagui_helper.php
tagui_parse.php
tagui_report.php
tagui_runner.php
tagui_service.php
translate.php
transpose.php.  

These files are in that folder,what should I do next? Thank you very much

**Comment by HollandWeng** [comment]
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"/Users/hollandweng/.tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
ERROR - cannot find Chrome at "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
Chrome is at a non-standard location on your macOS, raise an issue on TagUI GitHub page

[RPA][ERROR] - unknown error encountered
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"/Users/hollandweng/.tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
ERROR - cannot find Chrome at "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
Chrome is at a non-standard location on your macOS, raise an issue on TagUI GitHub page

[RPA][ERROR] - unknown error encountered
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using present()


these kind of error occur when I run my code today @kensoh

**Comment by HollandWeng** [comment]
I also found that I have download 2 kinds of java(jdk) by mistake, one is from amazon-corretto, and another is from Oracle Corporation. Do I need to delete java or is just have something wrong with   @kensoh 
/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

**Comment by HollandWeng** [comment]
I also found that I have download 2 kinds of java(jdk) by mistake, one is from amazon-corretto, and another is from Oracle Corporation. Do I need to delete java or is just have something wrong with PHP ? @kensoh
/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

**Comment by HollandWeng** [comment]
After I download google chrome, it seems that I can run my rpa code, but the Java icon appearing in the Dock while I'm running a program, is this because I've installed two Java environments, or is it a normal situation? @kensoh

**Comment by kensoh** [comment]
Hi @HollandWeng it looks like you solved the issue. For Java icon yes this is normal, the package uses SikuliX for visual automation and physical keyboard automation. If you use those type of automation in your script, Java will launch because SikuliX is a Java program.
