### ISSUE TITLE
Accessing Instagram elements - smart identifiers system, ideas to check next

### ISSUE THREAD

**Issue by kameroongod** [tebelorg/RPA-Python#354]
Hello,

I am trying to write a bot for automating stuff on Instagram (likes, follow, etc.)

I used to do it with Selenium, but seems that it doesn't work for too long anymore before I get flagged. So now I am turning to RPA.

I am wondering how do you access web elements by either class/aria-label/ or Xpath?

In Selenium to access the like button for example, I would do something like this

Like_Button = browser.find_element_by_class_name("fr66n")
mouse = webdriver.ActionChains(browser)
mouse.move_to_element(Like_Button).click(Like_Button).perform()

and now I am trying to do the equivalent in rpa by first hovering with rpa.hover and then clicking with rpa.click()

but can't seem to find the right syntax to do it..

I tried 

rpa.hover("//*[@class='_8-yf5 ']")

but doesn't work.

Thanks in advance !

**Comment by kensoh** [comment]
Hi @kameroongod the package automatically access the elements using XPath, CSS, and various attributes. See here for the list and the priority - https://github.com/tebelorg/RPA-Python#element-identifiers

For class you can use `rpa.hover("_8-yf5")` if it is unique enough or `rpa.hover("//*[@class='_8-yf5 ']")`

Also, there is a space after the ytf5, double check that the class really has that space, otherwise it won't match.

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem!
