### ISSUE TITLE
iframe without src or id attributes - use dom() to add attribute then frame()

### ISSUE THREAD

**Issue by lrbsantos** [tebelorg/RPA-Python#359]
Hello Ken,

How can I go inside an iframe that doesn't have src or id attributes? I've tried to use the frame(), but I didn't get it.

Thanks in advance.

Kind regards,

Luiz Ricardo

**Comment by kensoh** [comment]
Hi Luiz, the frame() function can take in `id` or `name`. If the frame does not have either one of them, an alternative is modifying the frame using dom() function to add in an id, so that it can have an id for frame() to switch to.

Is the website you are automating accessible to the public? You will need to write JavaScript code to do that (probably 1 line of JS code to query and add attribute). If it is accessible to public I can have a look.

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem!
