### ISSUE TITLE
Clicking on a button using visual automation does not work - some ideas

### ISSUE THREAD

**Issue by sadimoodi** [tebelorg/RPA-Python#361]
Hello,
Since using the xpath of a button does not allow me to click on it,i tried visual automation:
r.click('button.PNG')
i am getting an error [RPA][ERROR] - cannot find button.PNG 
The image DOES exist inside the directory.
funny enough: when using a random image name: i get a success message! but nothing clicks
whats wrong?!

**Comment by ck81** [comment]
Please refer to #170 

Additional note:
- Double check your screen resolution.
- Try screen resolution of 100%.  It should work
- Once you're certain that 100% works, then you can try other resolutions.  Some laptops will work.  Some will not
- If you have 2 monitors, do not capture on one monitor and then use the image on another.  The screen resolutions for the 2 monitors might be different
- Make sure your image is on your first monitor

**Comment by kensoh** [comment]
Thanks @ck81 for sharing your tips!

Hi @sadimoodi adding on, if you are using Mac, try checking if it is due to Retina display issue and [the solution here](https://github.com/tebelorg/RPA-Python/issues/170#issuecomment-843168745).

If a random image name is used and the file does not exist, the package will look for the UI element with the file name. Eg r.click('File.png') will click on the File menu on the screen, if there is the word "File" on the screen.
