### ISSUE TITLE
r.popup( ) data reads displayed abnormally - pending more info and replication

### ISSUE THREAD

**Issue by IsBeatrice** [tebelorg/RPA-Python#364]
hello @kensoh 
This problem has plagued us for a long time, and we are very eager to get your help.

Before we use this  r.popup( ), the result of the program is always in Chinese, but once we use r.popup( ), the program will no longer display Chinese, but the result  shown like "\\u38af\\u873f\\u125h\\u679g\n". We still need to decode it, which is very troublesome.

Is there any good way to solve this problem so that Chinese can be displayed all the time?
We would appreciate it  if we could get your reply.

**Comment by kensoh** [comment]
Hi @IsBeatrice can you share the Python code to replicate this issue so that I can understand more?

It might be due to the way data is returned to the Python process whenever queries are made on the popup window. There is a limitation related to Google Chrome browser on reading new tabs, but I can check more if there is a suitable solution.

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem!
