### ISSUE TITLE
r.table() command works very slowly - here are some alternatives to explore

### ISSUE THREAD

**Issue by jshah3821** [tebelorg/RPA-Python#368]
Hello,
In my case, i have to fetch more than 10,000's of  lines table to CSV. And I used command r.table().
Actually command works but it fetches data very slowly like 1 line in 1 sec.
Please provide better solution.

**Comment by fi-do** [comment]
Hey @jshah3821,

did you give  r.init(turbo_mode = True) a try?

Greets,
fido

**Comment by jshah3821** [comment]
Yes I already used Turbo_mode = True.
Is there any other function which i can replace in place of r.table() command.
It's ok if output is in any format i.e xls,or database.

**Comment by kensoh** [comment]
Thanks @fi-do! Hi @jshah3821, I'm afraid the table() function has some overheads as it reads the data row by row, cell by cell. Even with turbo mode, it will take some time for large tables. For your website, is there a way to download as .xls or other format? If there is, you can try automating the steps to download that table in the same way you do manually.

Some other ways could be using r.read('page') to get the HTML content directly and use Python requests package or pandas package to do the extraction of the HTML data to table. For eg - https://stackoverflow.com/questions/10556048/how-to-extract-tables-from-websites-in-python

PS - you may still need to use rpa package to get the HTML first because requests package won't render JavaScript and may not work on some dynamic websites.

**Comment by jshah3821** [comment]
Hi @kensoh  Thanks for alternative solution.
