### ISSUE TITLE
Why use PhantomJS as further development is suspended? - for reliability

### ISSUE THREAD

**Issue by andywenk** [tebelorg/RPA-Python#383]
First of all thank's for creating this awesome package. I am on Mac OS and installed all needed stuff (with homebrew). I just had a glimps to the [PhantomJS website](https://phantomjs.org/) and saw, that further development is suspended. So my question is, does it make sense to rely on PhantomJS or would it be a better idea to switch to another headless browser? Like:

* Headless Firefox
* Headless Chrome

All the best

Andy

**Comment by kensoh** [comment]
Hi @andywenk thanks for asking this. Great observations and question.

Indeed Python rpa package automates Chrome in visible and headless mode. The short answer is for reliability.

I created [TagUI open-source RPA](https://github.com/kelaberetiv/TagUI) over the last few years, since late 2016. For that project, I wrote the DevTools protocol code to control Chrome directly through a websocket connection. And I chose PhantomJS over NodeJS as the underlying JavaScript engine to run the code that talks to Chrome.

At that time, PhantomJS was a leading headless project that has binaries on Windows, Mac, Linux. That makes TagUI able to be unzipped and run easily, without the technical barrier / company IT restriction of having to install NodeJS or Python.

In TagUI, PHP is used to convert human language syntax into JavaScript code that is executed by PhantomJS to control Chrome. When I created Python rpa package in 2019, in theory I can rewrite everything in Python. However, as any software engineer can attest to, having reliable production stable software requires putting it onto the hands of a lot of users over a long period of time. TagUI is mature and very stable then.

Thus having a Python wrapper around TagUI is much more reliable to users than rewriting TagUI project in Python. The latter path would involve many iterations and couple of years before it can be as reliable as the former path. Other than creating value fast for users, it is also strategically important. Because losing the initial head start might mean that the rpa package might never take off if some other reliable alternative comes along before it iterates long enough to be stable.

More info on the architecture here - https://github.com/tebelorg/RPA-Python#about--credits

**Comment by kensoh** [comment]
Adding on, the part of PhantomJS that is needed is its binaries to run JavaScript code. Since PhantomJS is already a mature software, I would not expect any OS or environmental big changes to require it being refreshed in order for rpa package to run. Note that the PhantomJS JavaScript engine has nothing to do with the JavaScript that is running on Chrome.

Furthermore, I personally know the maintainer of PhantomJS and I believe it is still being used in production by many users. If there is such a day when a major Windows upgrade, for example, breaks PhantomJS, he and the community would be happy to make the revision required to let it continue to run.

**Comment by kensoh** [comment]
Finally, as a doomsday fallback, the rpa package can be re-written in pure Python without dependency on the underlying TagUI and PhantomJS. And it should be able to be done without compromising breaking existing user Python scripts.

**Comment by andywenk** [comment]
@kensoh thanks a lot for the extensive answer ;-)

I played with TagUI and rpa today and found out how to use it. So everything is cool and really awesome!
