### ISSUE TITLE
How do I use the files generated by pack() - move to intranet and use directly

### ISSUE THREAD

**Issue by HeliangCN** [tebelorg/RPA-Python#384]
Hi @kensoh , May I ask you a few questions? 

I used **rpa.pack()** in **rpa/main.py** file and generated  **rpa.py** and **rpa_python.zip**, but I don't know how it works.
1.  How do I use  **rpa.py** and *rpa_python.zip**  on the target computer. 
2. What objects are packaged? Folder(rpa) or file(main.py)?

The API manual would be better if it were more detailed.

Thank you for reading!

**Comment by kensoh** [comment]
Hi @HeliangCN oh under API general notes, there is the following link on using the package without Internet. It shows the step by step how to use the rpa.py and rpa_python.zip files - 

https://github.com/tebelorg/RPA-Python/issues/36#issuecomment-543670292

There is also help message after running pack(), I'll see if the message can be improved and be more verbose of the steps.

**Comment by kensoh** [comment]
Adding on, the following info messages will appear after running pack(). I think they are quite clear on how to use the generated files, so I won't be changing it.

Note that your python script must be in the same folder as the rpa.py file to work. Because of lack of intranet, I'm not relying on having pip command available to install package normally. So users have to have a copy of the rpa.py file in the same folder as the Python automation script.

>[RPA][INFO] - done. copy rpa_python.zip and rpa.py to your target computer.
>[RPA][INFO] - then install and use with import rpa as r followed by r.init()

**Comment by kensoh** [comment]
Closing issue for time being until further inputs
