### ISSUE TITLE
click() function sometimes fails - pending replication details, Chrome zoom %?

### ISSUE THREAD

**Issue by JJery-web** [tebelorg/RPA-Python#385]
I feel amazed again for this outstanding project.

These days when I did some tests I found it seemed sometimes fail during using **r.click() function**. All other functions were available except r.click(). So I had to use **r.dom()** to execute the onclick() function.

Because I am a beginner, I can not do anything to improve the code or giving corresponding solution. But actually I find it is not stable for the r.click() function.

Thanks. Best wish.
-----
_Example:_
r.dom("""document.querySelector("#react-project-comments > div > button").click()""") #  performability
r.click('//*[@id="react-project-comments"]/div/button')  # not performability

**Comment by kensoh** [comment]
Thanks Jerry for sharing your encouragement!

click() is done in the best-practice way by scrolling the webpage to the UI element, hovering on it, before clicking on it. In usual situations, it should perform better and more accurately than the dom() method to trigger click() event. This is because it tries to mimic a user's steps more closely by doing all those steps.

I can only think of a situation where it will fail. Check if your Chrome browser zoom % is set to 100%. Otherwise, the clicking will be done on the wrong (x,y) coordinates on the webpage and not work correctly. Also, if you have a simple replication script of how click() is failing and on what webpage, that will be helpful to troubleshoot further.

**Comment by JJery-web** [comment]
> 

Exactly. I fixed the size to 100% and the function is available now. Thank you very much. I wish you a happy life.

**Comment by JJery-web** [comment]
> Thanks Jerry for sharing your encouragement!
> 
> click() is done in the best-practice way by scrolling the webpage to the UI element, hovering on it, before clicking on it. In usual situations, it should perform better and more accurately than the dom() method to trigger click() event. This is because it tries to mimic a user's steps more closely by doing all those steps.
> 
> I can only think of a situation where it will fail. Check if your Chrome browser zoom % is set to 100%. Otherwise, the clicking will be done on the wrong (x,y) coordinates on the webpage and not work correctly. Also, if you have a simple replication script of how click() is failing and on what webpage, that will be helpful to troubleshoot further.

Exactly. I fixed the size to 100% and the function is available now. Thank you very much. I wish you a happy life.

**Comment by kensoh** [comment]
You are welcome, I hope you enjoy using the rpa package :)
