### ISSUE TITLE
after popup(), can't snap original page - side effect of Chrome rendering

### ISSUE THREAD

**Issue by jaff521** [tebelorg/RPA-Python#390]
I am learning how to use popup function, and reach a problem. When click a link, and success to popup to the new tab, but fail to go back the main page, and no time out exception after a long time.

```
import rpa as r

r.init()

r.url('https://tebel.org')

r.click('//*[@id="header"]/p/a[1]')

r.popup('interface_automation')
r.wait(1)
r.snap('page','page.png')

r.popup()
r.wait(1)
r.snap('page','page1.png')
r.close()
```

**Comment by kensoh** [comment]
Oh I think it is a peculiar side effect of Chrome. When trying to do screenshots, if the tab is not in focus, rpa package will need to keep waiting for Chrome. This is because that original page is not rendered in Chrome and the image data can't be sent back. For other actions like click() it works. See below example. wait() is generally not needed as there is auto-wait of 10 seconds, which can be changed with timeout().


```py
import rpa as r  
r.init()
r.url('https://tebel.org')
r.click('Process automation')
r.popup('interface_automation')
r.snap('page','page1.png')
r.popup()
r.click('Open-source')
r.wait()
r.close()
```

**Comment by kensoh** [comment]
Adding on, if you really need to do a snapshot of the original page, you can use keyboard() or click() to use keyboard shortcut or visually click to close the new tab. Make sure to do a click() visually to make Chrome in focus.

**Comment by jaff521** [comment]
Thanks for reply!
still need some more practices.
