### ISSUE TITLE
SikuliX Engine Crashing - pending more clues from the SikuliX log files

### ISSUE THREAD

**Issue by Mavericks334** [tebelorg/RPA-Python#401]
Hi @kensoh ,

SikuliX Engine is constantly crashing. It start well once the url is launched after a minute or two it shuts down. This never happened before. Currently i'm on Chrome version 100.00 and using TAGUI Version 1.43.

Could you please let me know what could be the issue.

Regards,
Ren.

**Comment by kensoh** [comment]
Hi Ren, I see, there isn't such a feedback like this from users before. You can check the SikuliX log files to look for clues.

From your description, it sounds like maybe something in your OS or environment or apps has changed. Because the rpa package and SikuliX didn't change. You check `print(r.tagui_location())`, inside that folder there is a .tagui or tagui folder depending on your OS. Inside that folder check src/tagui.sikuli folder for the logs.

You can attach or copy the log contents here.

**Comment by Mavericks334** [comment]
Today it just worked fine. I will continue to monitor if the crash happens again or it was just for that particular day

**Comment by kensoh** [comment]
Sure feel free to reopen issue if the problem crops up again!
