### ISSUE TITLE
When starting TagUI, /usr/bin/env: ‘python’: No such file or directory - try this

### ISSUE THREAD

**Issue by terencejackson8000** [tebelorg/RPA-Python#416]
Hello,

when I am running a simple script for PRA-Python I am getting the following output:
```
RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"/home/xxx/.tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
/usr/bin/env: ‘python’: No such file or directory

[RPA][ERROR] - unknown error encountered
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using read()

[RPA][ERROR] - use init() before using snap()
[RPA][ERROR] - use init() before using close()
```

My script is:
```
import rpa as r

r.init()
r.url('https://www.google.com')
r.type('//*[@name="q"]', 'decentralisation[enter]')
print(r.read('result-stats'))
r.snap('page', 'results.png')
r.close()
```

I have already set an alias for python. Typing in python to the command line gives me:
![image](https://user-images.githubusercontent.com/14046007/182032768-ae21a1e6-2ba6-4315-babb-831fedab90b3.png)

I am running the script on a Ubuntu 22.04.

So I think, this should not be the problem. Can you help me how to solve this?

**Comment by kensoh** [comment]
There's a dependency on Python by one of rpa package's components, CasperJS (`~/.tagui/src/casperjs/bin/casperjs`)

In above file, it starts with this line -
```
#!/usr/bin/env python
```

Can you try to set up your system so that there is a symbolic link (`ln` command) to the `python` command? For eg, set up the link at `/usr/bin/python` to point to your Python. This is because an alias may perhaps only work within your user shell, but may not work when a script is ran that invokes a fresh shell, like what above might do.

**Comment by terencejackson8000** [comment]
Thanks, this helped!

```sudo ln -s /usr/bin/python3 /usr/bin/python```
