### ISSUE TITLE
Automation stuck on about:blank if i set proxies (Raspbian) - some next steps

### ISSUE THREAD

**Issue by zell180** [tebelorg/RPA-Python#426]
`proxy = FreeProxy(https=True, rand=True).get()
os.environ['http_proxy'] = proxy
os.environ['https_proxy'] = proxy

r.tagui_location('/home/mocorasp/projects/ilmito_archives_uploader/tagui')
r.error(True)
r.init(headless_mode=False)
r.url("https://www.filesend.jp/l/en-US/")`

If i remove proxy settings automation works

**Comment by kensoh** [comment]
Can you share more on what is the error message?

If error is happening at init() step, it might be the proxy does not work with Python standard libraries for downloading stuffs. The code used by the package to download the dependencies is standard Python library. See here. Depending on your Python 2 or 3, you can try to run the following line directly and replicate the problem.

https://github.com/tebelorg/RPA-Python/blob/master/tagui.py#L1468

If the error is around r.url(), I don't think setting proxy this way affects the web automation part, because Chrome doesn't care about these proxy settings. You'll have to use visual automation or any other means to change the proxy settings for Chrome / Chromium to use the proxy you have defined.
