### ISSUE TITLE
rpa_python is missing when setup TagUI again - pending checks and more details

### ISSUE THREAD

**Issue by kevin3** [tebelorg/RPA-Python#433]
Hi I didn't have this issue previously but I am setting up in anaconda in another laptop and I get this similar error 

r.init()

[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"C:\Users\Molinares_S\AppData\Roaming/tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -

[RPA][ERROR] - unknown error encountered
False

I ran in the DOS for 
and it seems like rpa_python is missing

**Comment by kensoh** [comment]
Saw your other thread and replied there, but replying here since this is the open issue:

---

This normally happens if PHP is missing and user missed out manual set up steps.

1. What is your OS? (Mac, Ubuntu, Windows have specific steps to enable PHP)
2. try r.debug(True) before doing r.init() to see if there are other clue

**Comment by kevin3** [comment]
I was running this in Jupyter notebook from Anaconda (Win10) so perhaps that wasn't a good idea. I tried to delete the folder then launched a console (from Jupyter again) but I still don't see rpa_python. Maybe I will try to do this another way. Thanks though

**Comment by kevin3** [comment]
ok so I realised I needed to launch CMD.exe Prompt to run the same to get it to work properly. Thanks!
