### ISSUE TITLE
r.init() seems will be running forever - likely company IT policy blocking processes

### ISSUE THREAD

**Issue by Weak-Chicken** [tebelorg/RPA-Python#434]
Hi all, on my virtual machine, I ran `r.init()` and it looks like that it will run forever. I gave it about 5 mins but it is still running. There's no errors or logs. I've also tried to run tagui command: `\path\to\tagui rpa_python chrome`, and that command also seems will be running forever. Again, there's no logs or errors.

Just wondering that is there anyone has the same problem like me?

Many thanks.

**Comment by kensoh** [comment]
Hi @Weak-Chicken the most common reason for this is network policy blocking auto-download from github.com domain.

Could you try r.debug(True) before r.init() to see if there are other clues? Can you also try on other laptops (personal laptop or another colleague laptop), to see if the root cause can be isolated?

The other possibility is the company IT policy blocks automation of Chrome. The package on init() will try to connect to the Chrome browser from an opened websocket port. If the IT policy blocks such activity, the package will keep trying to connect non-stop but still cannot connect, thus not showing any error but hangs there.
