### ISSUE TITLE
Cannot run multi-thread with RPA - try turbo mode r.init(turbo_mode = True) ?

### ISSUE THREAD

**Issue by bbbbho** [tebelorg/RPA-Python#435]
using .init() in different thread with the threading library.
It cannot run the RPA separately in multiple windows to execute the RPA tasks in parallel.

**Comment by kensoh** [comment]
Hi @bbbbho I'm afraid this is not supported out of the box.

Because rpa package is built on TagUI engine, and that engine isn't tested and designed for parallel processing. The goal of that project was to replicate user's actions on the UI, thus it doesn't make sense to have parallel processing on the same web browser or desktop. You can try to use turbo mode to considerably speed up.

**Comment by kensoh** [comment]
(closing issue for now, but please feel free to open or share any thoughts or questions)
