### ISSUE TITLE
Visual automation in Colab template - require installing Linux libraries, see this

### ISSUE THREAD

**Issue by LucasValentimCamara** [tebelorg/RPA-Python#436]
Hi, 

I'm using the colab code (https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing) to learn more about RPA. I changed the file to enter a site, take a snap from a button and click on the button with this image, after the site load the new page take another snap. 

I can see the file being saved in colab and I saved it on the drive (just in case), but when i use r.click('result.png') it does not work. It just keep processing, no error message, no result.

`r.init(visual_automation = True)`
`r.url('https://http.cat/')`
`r.snap('/html/body/div[1]/div/ul/li[1]/div/a/div[2]', 'result.png')`
`r.click('result.png')`
`r.snap('page', 'results.png')`

![image](https://user-images.githubusercontent.com/112654407/201352589-a7ec2445-d6f8-4c99-95bd-b6667d941a7e.png)

Regards.

**Comment by kensoh** [comment]
Hi @LucasValentimCamara! Oh this is because for Colab which is running on Linux, the visual automation part relies on some Linux libraries to be installed manually. See below link to see if that helps. If the image libraries below like OpenCV and others are installed, hopefully the Xvfb mode used by the Colab template is able to reliable automate using computer vision.

https://sikulix-2014.readthedocs.io/en/latest/newslinux.html

**Comment by kensoh** [comment]
(closing issue for now, but please feel free to open or share any thoughts or questions)
