### ISSUE TITLE
Input text in login prompts while on headless mode - try if Xvfb in Linux works

### ISSUE THREAD

**Issue by frederick0291** [tebelorg/RPA-Python#443]
Hi,

I am currently trying to access an internal site using python-rpa and I am stuck on the login prompt.
![image](https://user-images.githubusercontent.com/40852439/207572471-f34d101f-4d80-4b87-b3c2-50df80de15c2.png)

How do I input details on this type of prompts when I am on headless mode?

I tried r.type() but it needs to have a target, r.keyboard() needs to have visual init but I am on headless mode.

Thanks,
Fred

**Comment by kensoh** [comment]
Hi @frederick0291, I'm afraid in the headless mode this can't work for rpa package. The reason is because it depends on TagUI engine, which would wait until Chrome responds back to the instruction. But an alert popup would be a blocking process that would not return the control back to the engine until users click it.

If you are on Linux, can you try running with virtual display? See below Colab example. The virtual display would allow using computer vision to click on something. However, this is not tested before and you probably need to install OpenCV and Tesseract manually in this way - https://sikulix-2014.readthedocs.io/en/latest/newslinux.html

https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

**Comment by frederick0291** [comment]
Thanks @kensoh. 

I discovered that you can actually bypass login prompts by passing the username and password to the URL like this:

`https://{username}:{password}@internalwebsite.com`

You need to url escape your user and password though so every special character gets converted. No need to handle the prompt.

**Comment by kensoh** [comment]
Thanks @frederick0291 this is a great tip! I'll keep this in mind for future users' questions.

There is another use case which above still might not work, those popup with a button to click Ok or Yes.
