### ISSUE TITLE
Change browser settings - ideas on setting browser size, agent, cookies

### ISSUE THREAD

**Issue by JoseZamora97** [tebelorg/RPA-Python#445]
Hi, Its any way to change browser screen resolution, and other browser params such user-agent?

**Comment by daimengxiaozhi** [comment]
have news？  another is how do you set up the proxy.  This also would be really helpful.

**Comment by kensoh** [comment]
There isn't a way change change these settings from API, but you could either modify some config files or write some code to do it.

For browser resolution, check the folder returned by r.tagui_location() --> there should be a tagui folder (Windows) or .tagui folder (Linux, Mac) under that location. Then go to src/tagui_config.txt file to modify the browser size.

For maximising Chrome and setting proxy, using visual automation mode and keyboard() to automate the manual actions required to maximise window or set proxy in Chrome. The proxy has to be set in Chrome this way. Alternatively, modify the file src/tagui.cmd (Windows) or src/tagui (Linux, Mac) so that the chrome command launches with the right proxy parameters.

For browser cookies, the is the src/chrome/tagui_user_profile folder which is actually your Chrome user and cookies. You can manually back it up and move it back before running r.init(), for Chrome to pick up the user saved settings and cookies. Alternatively, you could hack the tagui.cmd or tagui file to run Chrome with a specific user profile directory.

**Comment by kensoh** [comment]
Tagging @JoseZamora97 @Kendsito @daimengxiaozhi
