### ISSUE TITLE
Feature suggestion: run TagUI files in RPA for Python - to retire

### ISSUE THREAD

**Issue by RaulMed** [tebelorg/RPA-Python#452]
One of the advantages I see in tagui is that we (developers) can delegate on final users the creation and maintenance of desktop interactions and we only take care of the business logic.

I am also afraid of advanced users who always ends making a big mess when they try to do sophisticated applications from rudimentary technology / lack of knowledge (ie: people who make big applications based on excel macros or access forms). I'm currently not a low-code believer.
So my approach is to leave the easy and tedious part to them:  the desktop interaction. That is the part that they best know because is the business part. So I'd leave that tagui code blocks ("methods")  to them, so they can write, modify, maintain by themselves and save the algorithmic and the control to me.

So it would be great if we could run tagui files from python, as well as there were a way for the users to run their tagui files in an exec file (tiny python script) so they would be able to create and debug those files. Not forgetting also to provide a live mode.

**Comment by kensoh** [comment]
Thanks @RaulMed! I think it would be great to be able to run TagUI's human language workflows (.tagui) with Python rpa package, given that AI Singapore is ending maintenance for TagUI. There are some key limitations below, but on balance I think it would be a great feature to add.

1. use of JavaScript in TagUI would not be accurately mapped to working Python code, thus this would be out of scope
2. features like datatables, object repositories, excel integration etc would not make sense in Python, has to exclude
3. company intranet may not allow the use of Python to be installed, even if TagUI RPA can run on the network

Possibly a new function r.tagui() can be created to run .tagui workflow files. If debug() mode is on, the intermediary .py file could be retain for debugging purposes. No ETA due to work and family commitments. I'll ping you on Telegram to ask for which gift card you would like. I'm appreciating users of rpa package by US$100 gift card if they raise a feature request that makes sense to be added and accepted.

**Comment by kensoh** [comment]
Thank you very much @RaulMed, sent!
![image](https://user-images.githubusercontent.com/10379601/230748891-9ce657aa-4aa7-4bdc-bc3f-f9089195beab.png)

**Comment by kensoh** [comment]
Hi @RaulMed, after thinking through, and considering that there are still areas which Python rpa package can improve (the couple of open bugs), I believe it's better to focus limited time on improving Python rpa package vs committing a lot of time to get this feature right. Thus closing the issue for now. Thanks for making the suggestion nevertheless!!
