### ISSUE TITLE
Feature suggestion: simple IDE for TagUI users - there's existing mature plugin

### ISSUE THREAD

**Issue by RaulMed** [tebelorg/RPA-Python#453]
Related to [issue 452](https://github.com/tebelorg/RPA-Python/issues/452), I propose to create a simple GUI for users to edit, and run tagUI files.
This would consist a python desktop application withTKinter with:

- A big textbox for code
- A column of buttons at one side to write each command.
- A button for screenshot taking: This could ask for a name and after saving in a default folder for pics, add the name.png to the code, all in one step
- A button to run
- Some checkboxes for launching options: Turbo, headless, visual, firefox ...
- File operations: new, open, save, save as...
- A button to create shortcut (deploy)

That way the user doesn't have to remember the command names and doesn't have to open a console window

![taguiIDE](https://user-images.githubusercontent.com/65129443/228662517-6e137dd2-36fa-4bc6-b274-39d7e13ba47e.png)

**Comment by kensoh** [comment]
Thanks @RaulMed for raising this and sharing these details! The idea is great but I'm afraid I'll have to drop this suggestion.

The reason is there is already an existing MS Word plugin by TagUI that does exactly what you showed above and more.

https://github.com/aisingapore/TagUI/blob/master/src/office/README.md

Furthermore, adding this would require other dependencies to capture screenshot. This feature would not bring any new benefit to TagUI users (due to the existing mature MS Word plug-in above), while making rpa package heavier for the rest of the Python rpa users.

As for doing the same thing for Python users, I would think using Jupyter notebook is a more efficient and intuitive way to develop than having an interface like this to generate the Python code to do the rpa. Since most actions are intuitively named click(), type(), the users don't really need to remember much to cover most use cases.

**Comment by kensoh** [comment]
Closing issue for now, but please continue to share your thoughts!
