### ISSUE TITLE
Wait for download to complete - wait longer or check if download completes

### ISSUE THREAD

**Issue by uditijain** [tebelorg/RPA-Python#462]
Hi, i have a use case where i click on a download button and the files gets downloaded automatically(no save file dialog appears), i have inserted an explicit wait for 4 secs here. After which i copy this file and rename it to corresponding file id and the loop continues. The issue here is sometimes the download takes more than 4 secs and it copies the previously downloaded file with new file id which makes our process wrong. Please refer the code snippet : The following is in a loop 
```
 r.click("xpath")
 r.wait(3.5)
 src_dir = "....\reportTable.xlsx"
 dst_dir = "...\\"+filename
 shutil.copy(src_dir, dst_dir)
```

**Comment by kensoh** [comment]
Some ideas would be increasing the wait time, or using a while loop to keep checking for signs to show that the file download has been completed. Signs could be whether the filename exist, whether there is valid file size etc. The easiest solution would be increasing wait time. Since it is automation, taking longer time to run is better than having unreliable automation.

Unless there are ways that you can tell if the download is completed, for eg checking file size and file name, or use visual automation to visually detected something that you yourself manually will see to know that download is completed.
