### ISSUE TITLE
Please provide help, thanks - likely having TagUI version installed in wrong location

### ISSUE THREAD

**Issue by lixiao888** [tebelorg/RPA-Python#465]
1. win10系统在utf-8环境下(Active code page: 65001)如果执行python代码文件的路径名包含中文则click，type这些函数无法执行(执行后没反应，换成非中文路径正常)，希望能修复，谢谢。

2. 希望后续能提供滚动鼠标的功能函数

**Comment by kensoh** [comment]
Hi @lixiao888 for 1, can you share with me a sample script that can replicate the error and what is the error message? Can you also set r.debug(True) when you run the Python script to see if there are any other errors?

For 2, you can use vision() and send the custom command to scroll the mouse. Take note to use visual automation to click on the window you want first to make sure the OS focus is on that window.
```py
r.init(True)
r.vision('Mouse.wheel(WHEEL_UP, 1)')
r.vision('Mouse.wheel(WHEEL_DOWN, 5)')
```

**Comment by kensoh** [comment]
The 1 and 5 above means the number of steps to scroll the mouse.

**Comment by lixiao888** [comment]
问题1代码如下：
import rpa as r
r.init()
r.url('https://duckduckgo.com')
r.type('//*[@name="q"]', 'decentralisation[enter]')
r.wait() # ensure results are fully loaded
r.snap('page', 'results.png')
r.close()

错误日志如下：
START - automation started - Wed Apr 19 2023 16:18:35 GMT+0800 (中国标准时间)

LIVE MODE - type done to quit
 [RPA][STARTED]
[RPA][0] - listening for inputs
[RPA][1] - https://duckduckgo.com
[RPA][1] - listening for inputs
ERROR - inconsistent quotes in text
ERROR - can't find variable: exist
[RPA][2] - listening for inputs
[RPA][3] - dump exist_result to rpa_python.txt
ERROR - can't find variable: exist_result
[RPA][3] - listening for inputs

**Comment by kensoh** [comment]
@lixiao888 the error messages from issue 3 looks to suggest that you are not using the TagUI that comes with the Python package but the TagUI human language version. Because the error is syntax differences.

Check this location print(r.tagui_location()) and in that folder, delete the tagui folder. Then run again to let rpa package auto-downloads the right TagUI engine to use in the background.

Do you have TagUI installed separately?

**Comment by lixiao888** [comment]
感谢，问题3已解决，问题1还是不行

**Comment by kensoh** [comment]
@lixiao888, 
I think you haven't share the run log for problem 1 after fixing problem 3. Can you share the run log and a sample script that creates the problem?

**Comment by lixiao888** [comment]
![image](https://user-images.githubusercontent.com/16163394/233890042-0a35a3da-d470-4219-8a81-78a614ff04e3.png)
问题1错误日志如下：
START - automation started - Wed Apr 19 2023 16:18:35 GMT+0800 (中国标准时间)

LIVE MODE - type done to quit
�[RPA][STARTED]
[RPA][0] - listening for inputs
[RPA][1] - https://duckduckgo.com/
[RPA][1] - listening for inputs
ERROR - inconsistent quotes in text
ERROR - can't find variable: exist
[RPA][2] - listening for inputs
[RPA][3] - dump exist_result to rpa_python.txt
ERROR - can't find variable: exist_result
[RPA][3] - listening for inputs

代码如下：
import rpa as r
r.init()
r.url('https://duckduckgo.com')
r.type('//*[@name="q"]', 'decentralisation[enter]')
r.wait()
r.snap('page', 'results.png')
r.close()

**Comment by kensoh** [comment]
@lixiao888 the error messages from above looks to suggest that you are not using the TagUI that comes with the Python package but the TagUI human language version. Because the error is syntax differences.

Do you have TagUI installed separately?

Check this location print(r.tagui_location()) and in that folder, delete the tagui folder. Then run again to let rpa package auto-downloads the right TagUI engine to use in the background.

**Comment by kensoh** [comment]
Closing for time being until further inputs
