### ISSUE TITLE
Fixed window size, how? - adjust Windows size by modifying tagui_config.txt

### ISSUE THREAD

**Issue by zailaib** [tebelorg/RPA-Python#473]
![image](https://github.com/tebelorg/RPA-Python/assets/10792685/3f6a497e-a420-4632-b339-afc36dd0e78a)

this make the window size could not flexible

**Comment by kensoh** [comment]
@zailaib, print(r.tagui_location()) to get location of TagUI engine. There will be a .tagui folder there for Mac/Linux and tagui folder for Windows. Under that folder, open src/tagui_config.txt and you can change the width and height values of browser.

You could also write that in your code to modify that file and change the values accordingly. The default values are recommended for best compatibility with websites because that is a standard size web developers use to design their sites.
