### ISSUE TITLE
How RPA gets an open browser window for operations - some options

### ISSUE THREAD

**Issue by pdbeta** [tebelorg/RPA-Python#474]
How RPA gets an open browser window for subsequent operations

**Comment by LucasValentimCamara** [comment]
Can you explain a little further and give an example? 

Usually you close the browser before open another window with another process

**Comment by kensoh** [comment]
Without further context, there are 2 options, 1 is to use visual automation mode to visually automate the browser.

The 2nd option requires you to run the browser with a specific parameter in order to open the WebSocket backdoor for rpa package to read, write and control the browser. For example, editing the browser shortcut to launch it with the websocket port open. I'll discourage this method because it un-necessarily opens up the port for any other malicious activities when the user is using browser on his own when no need for automation.

Tagging @pdbeta and @LucasValentimCamara
