### ISSUE TITLE
dom() can't access frame(), click() not working in some cases - pending replication

### ISSUE THREAD

**Issue by sharmaniki11** [tebelorg/RPA-Python#480]
1. I am facing issue with dom() inside iframe. I am trying to add some style to element using dom that is inside frame, but nothing happening after running code. 

Please see below sample code:
```
r.frame("frame_main")
r.wait()
if(r.exist('//*[@id="mydiv"]')):
   r.dom("return document.querySelectorAll('#mydiv td').forEach(function(el){el.style.width = '35px'})")
```

2. Also there is an issue with click() :  I am trying to click link inside td but its not working

`r.click('//*[@id="mydiv"]/div[2]/table[1]/tbody[1]/tr['+str(tr+1)+']/td[1]/a')`
Note that i am able to read the data from same element but cannot click!

Please let me know what mistake i am doing.
Thanks in advance.

**Comment by kensoh** [comment]
Hi @sharmaniki11, I'm not sure if dom() could work across a different frame(). It might or might now, or require referencing the frame node directly instead of using "document" as starting node. Is there a public website which you can share a simple replication case of above observation? So that I can have a look at the logs and see if this is something is achievable.

**Comment by kensoh** [comment]
Closing issue for now, but do share back here!
