### ISSUE TITLE
Using Chrome extensions while running RPA similar to Selenium - try this way

### ISSUE THREAD

**Issue by damebash** [tebelorg/RPA-Python#483]
I'm wondering if there's a way to use the .crx file of a Chrome extension to be able to use it while running a script. This is how it's done in Selenium:

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument("--disable-notifications")
options.add_argument("--headless")
options.add_extension(r"C:\Py\instant data scrapper.crx")

driver = webdriver.Chrome(options=options)

Thanks!

**Comment by kensoh** [comment]
@damebash, I don't think this is doable, and not the goal of the project to use API to activate extensions since users will be manually activating from the UI. What you can try is simply do a wait(300) on first run, then download and setup and activate that extension for your user profile. The next time it runs will have that extension running because there is a specific Chrome user profile saved for the Python rpa package.

**Comment by kensoh** [comment]
Selenium's goal is for testing websites so it has a wide and sophisticated API to do all kinds of things.

rpa package merely aims to let user automate repetitive process they do manually with a simple API.

**Comment by marcelocecin** [comment]
I use extensions, I installed them by running the command to open some url and then the wait command to install it manually in chrome

**Comment by kensoh** [comment]
Closing issue for now but do continue the discussion and let us know if that works for you!

**Comment by damebash** [comment]
Thanks for the quick replies!
