### ISSUE TITLE
About mouse_xy() query - try running Python in live mode, also see what the logs say

### ISSUE THREAD

**Issue by Vic-Lau** [tebelorg/RPA-Python#485]
Hi @kensoh Mr.Kensoh, When I tested mouse_xy(), I found a little problem.

**First, I got the desktop ‘test folder’ coordinates: (150,417)**

![坐标截图](https://github.com/tebelorg/RPA-Python/assets/21170982/87102c81-f959-443f-bf19-0c6ab13c2311)

**Then I run script and get a wrong coordinates: (717,202)**

```Python
# -*- coding: utf-8 -*-
import rpa as r
import tagui as tagui
    
def test1():
    r.init(visual_automation = True, chrome_browser = False)
    r.wait(3)
    print(r.mouse_xy())
    r.dclick(r.mouse_xy())
    r.close()
    
if __name__ == '__main__':
    test1()
```

![错误坐标截图](https://github.com/tebelorg/RPA-Python/assets/21170982/fed761a6-214e-4ccc-9a8a-6b286139b34f)

**I found that I couldn't get the exact coordinates because the mouse moved when executing mouse_xy(), Is this normal?**

![坐标视频](https://github.com/tebelorg/RPA-Python/assets/21170982/6f7df343-f7f5-43f8-a978-e1c1c43abf6a)

**Comment by kensoh** [comment]
Hi @Vic-Lau can you tell me more what you are trying to do? If you are trying to grab coordinates so that you can use in your script, try to run in Python interactive mode with just python command or use Jupyter notebook. That way you can test r.mouse_xy() after moving the mouse to where you want, alt+tab and run r.mouse_xy()

This feature is based on the SikuliX engine. You can share the log files from r.tagui_location() + 'tagui/src/tagui.sikuli' folder to see what is going on. But there is limited that can be done because it is a 3rd-party open-source library that I don't have influence over if there is a bug or incompatibility with your OS environment.

**Comment by Vic-Lau** [comment]
Oh, I see, I always get the coordinates with python, So, that's ok, thanks for your reply.
