### ISSUE TITLE
RPA-Python can‘t use browsers other than Chrome - this is by design

### ISSUE THREAD

**Issue by bravohaha** [tebelorg/RPA-Python#487]
But TagUI does support other chrome。
According to the issue:https://github.com/aisingapore/TagUI/issues/946，
Can you please add this feature in RPA-Python?

**Comment by kensoh** [comment]
TagUI supports Chrome, Edge, Firefox old version 59. But Python rpa package's goal is only to automate repetitive tasks. So it only aims to support the most commonly used browser Chrome. Chrome is similar to Edge, both are using Chromium browser underneath.

For more browser options, consider using Selenium which is designed for testing and it supports all browsers I believe.

**Comment by kensoh** [comment]
Closing issue for now but please feel free to reply and share your thoughts!

**Comment by TheBoojah** [comment]
Hi!
I previously used the 'hack' referenced in the tagui thread to run my automation in edge. 
Just like the op here I'd like to use RPA-python to automate processes in Edge because my company has disabled chrome completely. But that doesn't work with the latest tagui package, even though it's configured to use edge. 

I don't necessarily need a python side option to choose between different browsers (again not doing testing automation, so I don't need to switch browsers). I only need the ability to configure eg. Tagui.cmd to launch edge from a RPA call. Or if Chrome doesn't exist try Edge. 

Thanks!

**Comment by kensoh** [comment]
Hi @TheBoojah, you can check the tagui.cmd or tagui below depending on whether you are using Windows or Linux/Mac -

https://github.com/aisingapore/TagUI/tree/master/src

Then you check the tagui directory installed by Python RPA package. using `r.tagui_location()`.

For Windows there is a tagui folder for mac and linux there is a .tagui folder. Then go to the src directory.

You search for the references for `edge` in the link above, then try making similar changes for your local copy.
