### ISSUE TITLE
How to clear the login status and clear the cache? - add logout into your script

### ISSUE THREAD

**Issue by monty8800** [tebelorg/RPA-Python#490]
I performed the login operation. When I tried to change the account to perform the operation, I used the cache of my last login by default.
I need to clear the login status after each execution, and the cache is cleared

**Comment by kensoh** [comment]
@monty8800, there are generally 3 ways:

1. After each login, you script the code to log out. Or at the start of your code, make a check if the account is in logged in status, then logout before you start the workflow.
2. There is a Chrome user profile folder in r.tagui_location() --> tagui or .tagui folder depending on your OS and --> src/chrome/tagui_user_profile --> you can write code to delete this whole folder at the end of each run to remove all the cached login and history
3. 3rd way is hack source code of the TagUI engine used by rpa package, to launch Chrome in incognito mode, but this is hacky and you may have to rehack each time you upgrade the package. Also, you need to start a new Python run in order to clear the cache in the incognito mode.

I'll recommend 1 because it is more representative of a normal user workflow, rather than playing around with the cache.
