### ISSUE TITLE
TagUI error while starting python bot - pending details of brackets in path

### ISSUE THREAD

**Issue by joker21212** [tebelorg/RPA-Python#493]
PS D:\Oracle SaaS Platform\BackEnd (6)\BackEnd> python ChartOfAccountMapping.py
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"C:\Users\vijay.kakade\AppData\Roaming/tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
\BackEnd\rpa_python.log' was unexpected at this time.

[RPA][ERROR] - unknown error encountered
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using close()
PS D:\Oracle SaaS Platform\BackEnd (6)\BackEnd>

**Comment by Vic-Lau** [comment]
It looks like you need add r.init().

**Comment by abc-africa** [comment]
I am facing the same issue on using windows 11

(pythonrpa) C:\Users\oct.azure\Codes\pythonrpa>python create_invoice.py
The system cannot find the path specified.
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"C:\Users\myusername\AppData\Roaming/tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
The system cannot find the path specified.

[RPA][ERROR] - unknown error encountered
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using close()

**Comment by joker21212** [comment]
> It looks like you need add r.init().

That is already written below.

**Comment by kensoh** [comment]
Adding on, for @joker21212 can you try using another folder? Maybe some folder without space that you have write access to. Your error message seems to be saying that the BackEnd folder has some issue creating the log file.

For @abc-africa , it might be somehow your intranet blocks downloading TagUI RPA engine, because your error message says that it cannot find the specified path. Try running manually the command in previous message to see what happens.

**Comment by hanyuanzhong** [comment]
Hello, @kensoh I also encountered this problem, I have two computers, it works fine on one computer, but it will have problems on the other computer, run the above command "C:\Users\ user name \AppData\Roaming/tagui/src/tagui" rpa_python chrome, result: ERROR - cannot find rpa,

**Comment by hanyuanzhong** [comment]
> 你好@joker21212和@abc-africa,
> 
> 您可以打开命令提示符并运行各自的命令来看看会发生什么吗？
> 
> “C:\Users\vijay.kakade\AppData\Roaming/tagui/src/tagui” rpa_python chrome
> 
> “C:\Users\myusername\AppData\Roaming/tagui/src/tagui” rpa_python chrome
> 
> 这将揭示为什么TagUI RPA引擎无法正确调用的原因。

hello @kensoh  I was able to run it in the pycharm editor, I packaged the code as an exe file, then double-click to run the problem, as I said in the last comment, I have two computers, one is having problems, one is working, I created an empty folder, run it Command C:\Users\vijay.kakade\AppData\Roaming/tagui/src/tagui "rpa_python chrome, ERROR - cannot find rpa,

**Comment by hanyuanzhong** [comment]
> > 你好@joker21212和@abc-africa,
> > 您可以打开命令提示符并运行各自的命令来看看会发生什么？
> > “C:\Users\vijay.kakade\AppData\Roaming/tagui/src/tagui” rpa_python chrome
> > “C:\Users\myusername\AppData\Roaming/tagui/src/tagui” rpa_python chrome
> > 这将揭示为什么TagUI RPA引擎无法调用正确的原因。
> 
> 你好@kensoh 我能够在pycharm编辑器中运行它，我将代码打包为exe文件，然后双击运行出现问题，正如我在上一条评论中所说，我有两台电脑，一台有问题，一台正在工作，我创建了一个空文件夹，运行它命令 C:\Users\vijay.kakade\AppData\Roaming/tagui/src/tagui "rpa_python chrome, 错误 - 找不到 rpa_python,

你好 @kensoh I've figured out why, because there are parentheses in the path, even in English

**Comment by kensoh** [comment]
Hi @hanyuanzhong thank you for updating back here! It sounds like somewhere in the code or its dependencies do not work well with the brackets. Can you share more what is the full path with the bracket? Because above example is referring to "C:\Users\vijay.kakade\AppData\Roaming/tagui/src/tagui "
