### ISSUE TITLE
r.read() is wrong for chinese and tamil characters on new tab - limitation, try this

### ISSUE THREAD

**Issue by lookang** [tebelorg/RPA-Python#494]
Greetings, Ken!
It's been a while since we last had a chat. I believe I've stumbled upon an issue. It seems that after using the command `r.popup('contentmap/view/')`, the `r.read` command doesn't handle Chinese and Tamil font characters correctly. To illustrate this, here's an example:

The text "72 is \u517b\u6210\u8fb9\u8bfb\u8fb9\u601d\u8003\u7684\u4e60\u60ef
SEC 3 CHINESE LANGUAGE (NA) (2021)" is not being processed correctly by `r.read` after the r.popup('contentmap/view/') which is the second Chrome tab then.

see first rows and /, towards the end, the chinese characters are correctly r.read
[SEC 3 CHINESE LANGUAGE (NA) (2021).csv](https://github.com/tebelorg/RPA-Python/files/12876721/SEC.3.CHINESE.LANGUAGE.NA.2021.csv)

To work around this problem, I can take a less time-efficient approach by sending the URL back to the initial first Chrome browser tab. This way, the `r.read` command will be able to handle the text correctly.
the text will be "72 养成边读边思考的习惯"

Please release a fix so I can use the more efficient *.py to use import rpa as r and less of original flavor of Tagui.
:)

**How i was able to convert to .py from .tag**
By the way, I am amazed how https://chat.openai.com/ can convert *.tag to *.py accurately up to 90%, then I can clean up later the rest of 10% of the code. 

**Another Request faor openai API call?**
I wonder if there an API call to https://chat.openai.com/ that we can use? I hope to harness the power of GenAI to check the question text against the syllabus learning objectives (LO) and ask GenAI to give me the number of the LO , for example 72, using the above example, so I can automate the questions tagging to LO. This can save a lot of manhours manually tagging

**Comment by kensoh** [comment]
Hi @lookang, thanks for raising this! And the PR to improve the readme. Yes it has been a long time since we last spoke...

There is a limitation here where I have to grab all the html content of the popup tab before parsing it. I think the special encoding would not work correctly because of that. For your use case, would clicking to open the page in the current tab to do the processing, and then using `r.dom('history.back()')` to go back to the initial page work?

Oh wow, this is amazing! Can you share some prompt tips you have to do that in https://github.com/tebelorg/RPA-Python/issues/484 ? I'm not sure how many users are migrating from TagUI to Python rpa package. Using ChatGPT to do 90% of the work sounds like a great time-saver!

OpenAI ChatGPT API is a paid service, so I don't plan to integrate with it. Can you use case be achieved by writing Python code using rpa package to automate you using ChatGPT from the web-browser to get the info you want?
