### ISSUE TITLE
Shift issue - probably doable using r.vision() to use custom SikuliX commands

### ISSUE THREAD

**Issue by JesusJordan97** [tebelorg/RPA-Python#498]
Hi Ken Soh, 

I have been playing with some keystrokes and I have found an issue while using shift key, I am trying to select a whole line using the combination of shift and home button:

r.keyboard('[shift][home]')

Trying this I noticed that it is not working for whatever reason, do you know what could be the issue?

Thank you in advance.

**Comment by kensoh** [comment]
Hi @JesusJordan97 , I suspect it's because the syntax you use means to press shift+home. Using r.vision() it is possible to send special keys like holding down shift, then press home, then letting go of shift key. But that involves reading SikuliX doc.

Would [ctrl]a work for you to select all the text, then you process the text after that? Can you share more on the scenario so I could see if there are other ways to achieve the outcome you want?
