### ISSUE TITLE
Intercept request/cookies - dom() might work but most likely not, use case not supported

### ISSUE THREAD

**Issue by Yuro12345** [tebelorg/RPA-Python#501]
I need to intercept a request on my browser, is it possible?

**Comment by kensoh** [comment]
Hi @Yuro12345, I'm afraid that's not possible, the package is primarily designed for automating manual repetitive processes, and not so much for interacting with the browser on API level. For that, web and test automation packages like Selenium, Puppeteer, PlayWright etc should be a better fit.

That said, can you tell me more about your use case, and I can see within the constraint of the rpa package, is there a way to achieve that. Maybe you can do something with r.dom() which sends custom JavaScript commands to the browser. But most likely not, because it's not designed and tested for that low-level interactions.
