### ISSUE TITLE
运行报错,弹出错误窗口"IDE not useable" - possibly due to copying directly to new PC

### ISSUE THREAD

**Issue by hanyuanzhong** [tebelorg/RPA-Python#502]
Hello,  @kensoh I am running on a new computer, but there is an error.

Pop-up error window :IDE not useable,

Error :"Neither Jython nor JRuby available

IDE not yet useable with JavaScript only Please consult the docs for a solution"

**Comment by kensoh** [comment]
Hi @hanyuanzhong, the issue is most likely caused when copying TagUI engine directly from 1 PC to another.

On first run, Jython will be moved to some system folder and will no longer be in the TagUI source folder.

You can try to do a fresh installation on the new PC or use r.pack() to copy the files to the new computer.
