### ISSUE TITLE
After python is packaged as an exe, an error occurs - try using .bat .cmd or shell script

### ISSUE THREAD

**Issue by hanyuanzhong** [tebelorg/RPA-Python#507]
hello 
After python is packaged as an exe, an error occurs and the application cannot be started 0xc000012d. Click OK to close the application

![image](https://github.com/tebelorg/RPA-Python/assets/48727363/aa673200-3e29-45fd-892e-62871a305fed)

**Comment by kensoh** [comment]
Hi @hanyuanzhong, `curl` is used by TagUI RPA engine to connect to the Chrome websocket connection. The rpa package is not designed to be packaged as an .exe. There are other components and dependencies that does not allow it to be packaged as a single exe and run out-of-the-box.

An alternative is instead of using packaged .exe you can create a .cmd or .bat file on Windows or a script file on Linux or Mac, to run the specific Python script and with the specific parameters you want. That way, you can still double-click to run a specific automated process, in the same way as a Python packaged exe.
