### ISSUE TITLE
Out of memory problem - Chrome browser is memory hog, can explore that angle

### ISSUE THREAD

**Issue by yucongshub** [tebelorg/RPA-Python#510]
If my RPA script frequently accesses web pages and downloads attachments, it will take up a lot of memory and may eventually cause OOM. Is there a way to release the memory usage, or support the chrome://restart command?

I only ran one RPA script and below is the memory usage, its memory is still growing

![image](https://github.com/tebelorg/RPA-Python/assets/62985119/17ac3093-b5a1-497c-bbc7-7483e1cb60f6)

**Comment by yucongshub** [comment]
![E7FWTQ02VJJM_N@`B1GUHT0](https://github.com/tebelorg/RPA-Python/assets/62985119/f28ceecc-8a79-4aa0-ba55-95463bcb8860)
After 10 minutes, they added a total of 1GB of memory.

**Comment by yucongshub** [comment]
![image](https://github.com/tebelorg/RPA-Python/assets/62985119/559d7a33-a1af-40d1-afe0-b273ebbbc2b4)
When PID19907 disappears, the entire RPA script no longer continues execution, but no exceptions or logs are thrown.

**Comment by kensoh** [comment]
The main memory hog is Chrome. The phantomjs JavaScript engine is light. You could explore more on Chrome memory usage in Linux, but might not make much headway because Chrome really is hungry for memory. The package uses Chrome because that is the most commonly used web browser and will most likely work with different websites.

There is possibility to hack some files to use Chromium or Edge, but it is not supported. Related issue - https://github.com/tebelorg/RPA-Python/issues/471

**Comment by yucongshub** [comment]
@kensoh Thanks, my current solution is to execute r.close() and then r.init() after visiting hundreds of pages, thus releasing the memory occupied by chrome. I will also test using the Chromium browser according to the method you provided to see if it can solve the problem of excessive memory usage.

**Comment by yucongshub** [comment]
@kensoh, I will also try turning this option on to see if it allows me to access more pages.
![)4)E$EUKBO}4L$BS5BITTS](https://github.com/tebelorg/RPA-Python/assets/62985119/1c64620a-c181-4f70-bfa2-e969e11893ec)

**Comment by kensoh** [comment]
That Chrome option may not be helpful if you only have 1 tab. If you design to close() and init() after a certain number pages, that should be a good solution. Or alternatively, you can design to close() and init() after each page. Because this can help to slow down the automation and not cause the website to block your automation server IP.
