### ISSUE TITLE
click() with a xpath ending the script without error - pending log and replication

### ISSUE THREAD

**Issue by carlos-negrao-tlp** [tebelorg/RPA-Python#530]
I am finding a strange problem where upon calling click() with a xpath, the click event is being sent and the download expected starts, but immediately the script dies for no apparent reason, with the tagui's console window staying up.

There are no errors nor exception to capture, so I'm stumped here.

Am I missing something? Is there any info I can provide?

**Comment by kensoh** [comment]
Hi @carlos-negrao-tlp , can you run with r.debug(True), and attach the rpa_python.log here?

Also, there is a tagui_chrome.log which you can find in the folder `r.tagui_location()` --> tagui folder --> src folder

I have not come across this issue or hear other users report something like this before. Any info would help troubleshooting.

Also, can you share a simple replication script so that I can try to see if it also crashes for me.

What about other websites, does it crash for you?

**Comment by carlos-negrao-tlp** [comment]
Thank you responding.
Unfortunately, I had to give up on the approach due to time constraints.
I didn't bother trying with other sites, since it would have been pointless (for me, at least), and neither have the code anymore, since I throw away experiments that go nowhere.
What I can say is the website I had been trying to scrap seems to have been made with GWT, which you may know is a pain to scrap.
