### ISSUE TITLE
Upload on website - try using upload() or visual automation and keyboard() 

### ISSUE THREAD

**Issue by fengzstrong** [tebelorg/RPA-Python#538]
Is there an example where you click to upload a file, which prompts a dialog showing the operating system's file system, allowing you to select and upload a file?

Thanks for your great job again !

**Comment by kensoh** [comment]
Hi @fengzstrong either use upload() step

https://github.com/tebelorg/RPA-Python?tab=readme-ov-file#pro-functions

Or use visual automation and keyboard() to visually click on upload button and choose the file. See API reference section on examples of visual automation. For eg click('upload.png').

Above is because pop up dialog will take away control from the automation, so need to use workaround above.
