### ISSUE TITLE
Issue with keyboard Enter, how to assess popup - try XPath again or [enter], try these

### ISSUE THREAD

**Issue by PGaurav5** [tebelorg/RPA-Python#541]
Hi,
There are 2 issues I am facing.
1.
 Xpath for one of the field is not working correctly, so I am using Keyboard function but when it reached to required field, even passing Enter command it is not working, Please guide.
_r.keyboard('[tab][tab][tab][tab][tab][tab][tab][tab][tab][tab][tab][tab][Enter]')_ 
Even I tried -
_r.keyboard('[tab][tab][tab][tab][tab][tab][tab][tab][tab][tab][tab][tab]')
r.wait(4)
r.keyboard('[Enter]')

2. After click on required field it opens up a small window to select and download the report. The new window does not have any URL, how to navigate to it and then click on export button. See, popup image as below.
![RPA_error](https://github.com/user-attachments/assets/18f39315-f653-4369-9c2b-65b7e4851904)

Can you please suggest on this. Thank you!

Regards,
Gaurav

**Comment by kensoh** [comment]
Hi @PGaurav5 for question 1,

See if you can find the XPath in another way. Maybe it is in an iframe so you need to use r.frame() first? For `[Enter]`, have you tried `[enter]` I recall the syntax is lowercase? I can't think of other ways to solve without access to your website.

For question 2, there should be an URL but just that it is not shown because there is no address bar in the popup. You can try inspecting the window to see if there is clue what is the real URL and then use r.popup(). Alternatively, just use r.click('export.png') visual automation method by supplying image snapshot of what to click.

**Comment by PGaurav5** [comment]
Thank you @kensoh for the quick reply. Yes 'enter' with small "e" works. Thank you!I am trying to get Xpath that could work but still issues.Let me explore more about it.
for Q(2) - r.popup('Export') worked and able to click on 'Export' button. It automatically download at path where Tagui installed, Can we provide specific folder where it can save the exported document.
Thank you inadvance!

**Comment by kensoh** [comment]
Hi @PGaurav5 I think it downloads to the starting folder or folder of the python script. You can use r.download_location() to pick another folder.

**Comment by PGaurav5** [comment]
Thank you, really helpful @kensoh.
