### ISSUE TITLE
Issue of space in username or folder name - use another folder or acct

### ISSUE THREAD

**Issue by prempchandran** [tebelorg/RPA-Python#98]
Hi Ken,
I am new to TagUI and currently attending CK 's lesson as part of my course. If TagUI is installed in a folder path with a space, is there any way to make it work?

The error message i get is
_**[TAGUI][INFO] - to use TagUI for Python on Windows, avoid space in folder path name**_

Thank you

**Comment by kensoh** [comment]
Hi @prempchandran, is it your Windows user name has a space?

If not, it means you are running from a folder location where there is a space. Try running from another folder without space in the pathname.

If your user name has a space there isn't a simple workaround, will need to hack 3 lines of this package to a specific folder you choose to make it work. But this is not recommended because anytime you upgrade to a new version this change will be lost. Alternatively, try to create a dummy user without a name in the user name, and run this tool in that acct to see if that works.

There is a limitation in the CasperJS / PhantomJS components of TagUI and thus folders with spaces is not able to work correctly on Windows. In a future TagUI release, the feasibility of migrating the execution engine to Node.js is being explored and this issue can be resolved.

**Comment by prempchandran** [comment]
Hi Ken,
Thanks for the reply. I created a dummy user with no space as you suggested and now it works fine.
If you can include the hackaround of 3 lines that you mentioned , that will be useful to.

Thanks.

**Comment by kensoh** [comment]
Great! Let's say you want to install to C:\tagui folder.

Edit tagui.py (location can be found with t.\_\_file\_\_ after you import tagui as t). Search for the text `os.environ['APPDATA']` and replace with `'C:'`

There should be 4 replacements, let me if that works for you or if there's problem.

**Comment by prempchandran** [comment]
Hi Ken, 
Sorry if am blur about this, but it seems like tagui.py does not download or show up in my folder after running the " import tagui as t ". I've tried searching for it too.
If its bit complicated to explain, no worries, I can just work with the dummy user environment for now.

**Comment by kensoh** [comment]
Hi @prempchandran you can run below to get the location that pip installed this package on your computer. Once you have the file, you can modify and then restart Python to have the changes.

```py
import tagui as t
print(t.__file__)
```

**Comment by kensoh** [comment]
Closing issue for now until further inputs!
